// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// BLEConfigRPC is generated from the Shelly API documentation.
type BLEConfigRPC struct {
	// Enable true if rpc service is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// BLEConfig is generated from the Shelly API documentation.
type BLEConfig struct {
	RPC *BLEConfigRPC `json:"rpc,omitempty"`
}

// BLEGetConfigRequest requests the configuration of the BLE component.
type BLEGetConfigRequest struct {
}

func (r *BLEGetConfigRequest) Method() string { return "BLE.GetConfig" }

func (r *BLEGetConfigRequest) NewTypedResponse() *BLEConfig { return &BLEConfig{} }

func (r *BLEGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *BLEGetConfigRequest) Do(client *resty.Client) (*BLEConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// BLESetConfigRequest updates the configuration of the BLE component.
type BLESetConfigRequest struct {
	// Config that the method takes.
	Config BLEConfig `json:"config"`
}

func (r *BLESetConfigRequest) Method() string { return "BLE.SetConfig" }

func (r *BLESetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *BLESetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *BLESetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
