// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// CCTConfigNightMode is generated from the Shelly API documentation.
type CCTConfigNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit when night mode is active. null overrides
	// night_mode.brightness with current brightness when night mode starts. Default
	// value 50.
	Brightness *float64 `json:"brightness,omitempty"`

	// Ct color temperature level limit (in Kelvin) when night mode is active. null
	// overrides night_mode.ct value with current ct value when night mode starts.
	// Default value: 50% of ct_range. For DuoBulbG3: 4600
	Ct *float64 `json:"ct,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optinal leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// CCTConfigButtonPresetsButtonDoublepush is generated from the Shelly API documentation.
type CCTConfigButtonPresetsButtonDoublepush struct {
	// Brightness brightness level (in percent) set on double click (if applicable).
	// null overrides brightness with current brightness when preset is applied.
	// Default: 100
	Brightness *float64 `json:"brightness,omitempty"`

	// Ct color temperature level (in Kelvin) set on double click (if applicable). null
	// overrides ct with current ct when preset is applied. Default: max setting of
	// ct_range (device specific)
	Ct *float64 `json:"ct,omitempty"`
}

// CCTConfigButtonPresets is generated from the Shelly API documentation.
type CCTConfigButtonPresets struct {
	ButtonDoublepush *CCTConfigButtonPresetsButtonDoublepush `json:"button_doublepush,omitempty"`
}

// CCTConfig is generated from the Shelly API documentation.
type CCTConfig struct {
	// ID id of the CCT component instance
	ID int `json:"id"`

	// Name name of the CCT instance
	Name *string `json:"name,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// TransitionDuration transition time (in seconds) - time to change from 0% to 100%
	// of brightness (if applicable)
	TransitionDuration *float64 `json:"transition_duration,omitempty"`

	// MinBrightnessOnToggle brightness level (in percent) applied when there is a
	// toggle and current brightness is lower than min_brightness_on_toggle.
	MinBrightnessOnToggle *float64 `json:"min_brightness_on_toggle,omitempty"`

	NightMode *CCTConfigNightMode `json:"night_mode,omitempty"`
	// ButtonFadeRate controls how quickly the output level changes while a button is
	// held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is
	// fastest, 1 is slowest
	ButtonFadeRate *float64 `json:"button_fade_rate,omitempty"`

	ButtonPresets *CCTConfigButtonPresets `json:"button_presets,omitempty"`
	// RangeMap remaps output 0%-100% range to values in array (if applicable). First
	// value in array is min setting, second value is max setting. Array elements are
	// of type number. Accepted range for values is from 0% to 100%. Default values are
	// [0, 100]. max must be greater than min.
	RangeMap json.RawMessage `json:"range_map,omitempty"`

	// CtRange sets the color temperature operating range in Kelvin (if applicable).
	// First value in array is min setting, second value is max setting. Array elements
	// are of type number. Accepted range for values is from 1000K to 10000K. Default
	// values are device specific. Default values for DuoBulbG3: [2700, 6500]. max must
	// be greater than min.
	CtRange json.RawMessage `json:"ct_range,omitempty"`

	// CurrentLimit limit (in Amperes) over which overcurrent condition occurs (shown
	// if applicable). For specific devices applies for color channels, not CCT
	// component
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	// PowerLimit limit (in Watts) over which overpower condition occurs (shown if
	// applicable)
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit limit (in Volts) over which overvoltage condition occurs (shown if
	// applicable)
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`
}

// CCTGetConfigRequest requests the configuration of the CCT component.
type CCTGetConfigRequest struct {
	// ID of the CCT component instance.
	ID int `json:"id"`
}

func (r *CCTGetConfigRequest) Method() string { return "CCT.GetConfig" }

func (r *CCTGetConfigRequest) NewTypedResponse() *CCTConfig { return &CCTConfig{} }

func (r *CCTGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CCTGetConfigRequest) Do(client *resty.Client) (*CCTConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// CCTSetConfigRequest updates the configuration of the CCT component.
type CCTSetConfigRequest struct {
	// ID of the CCT component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config CCTConfig `json:"config"`
}

func (r *CCTSetConfigRequest) Method() string { return "CCT.SetConfig" }

func (r *CCTSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *CCTSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CCTSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
