// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// CoverConfigMotor is generated from the Shelly API documentation.
type CoverConfigMotor struct {
	// IdlePowerThr watts, threshold below which the motor is considered stopped
	IdlePowerThr *float64 `json:"idle_power_thr,omitempty"`

	// IdleConfirmPeriod seconds, the minimum period of time in idle state before the
	// state is confirmed
	IdleConfirmPeriod *float64 `json:"idle_confirm_period,omitempty"`
}

// CoverConfigObstructionDetection is generated from the Shelly API documentation.
type CoverConfigObstructionDetection struct {
	// Enable true when obstruction detection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Direction the direction of motion for which the safety switch should be
	// monitored, one of open, close, both
	Direction *string `json:"direction,omitempty"`

	// PowerThr watts, power consumption above this threshold should be interpreted as
	// objects obstructing Cover movement. This property is editable at any time, but
	// note that during the cover calibration procedure (Cover.Calibrate), power_thr
	// will be automatically set to the peak power consumption + 15%, overwriting the
	// current value. The automatic setup of power_thr during calibration will only
	// start tracking power values when the holdoff time (see below) has elapsed
	PowerThr *float64 `json:"power_thr,omitempty"`

	// Holdoff seconds, time to wait after Cover starts moving before obstruction
	// detection is activated (to avoid false detections because of the initial power
	// consumption spike)
	Holdoff *float64 `json:"holdoff,omitempty"`
}

// CoverConfigSafetySwitch is generated from the Shelly API documentation.
type CoverConfigSafetySwitch struct {
	// Enable true when the safety switch is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Direction the direction of motion for which the safety switch should be
	// monitored, one of open, close, both
	Direction *string `json:"direction,omitempty"`
}

// CoverConfigSlat is generated from the Shelly API documentation.
type CoverConfigSlat struct {
	// Enable true when slat control is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// OpenTime time it takes for slats to move from fully closed (0%) to fully open
	// (100%) position, seconds. Must be manually configured by the user. Accepted
	// range: [0.5..30]s
	OpenTime *float64 `json:"open_time,omitempty"`

	// CloseTime time it takes for slats to move from fully open (100%) to fully closed
	// (100%) position, seconds. Must be manually configured by the user. Accepted
	// range: [0.5..30]s
	CloseTime *float64 `json:"close_time,omitempty"`

	// Step single step movement spread, represented as % from the full range (used
	// only when slats are controlled via inputs). Accepted range: [1..100]%
	Step *float64 `json:"step,omitempty"`

	// RetainPos whether to retain slat position when cover (vertical) position is
	// changed
	RetainPos *bool `json:"retain_pos,omitempty"`

	// PreciseCtl this property only applies when cover (vertical) position is less
	// than one full slat rotation away from the fully closed position. If this
	// condition is met, any slat movement will always go through fully closed position
	// first. This improves slat positioning accuracy, yet is slower to execute.
	PreciseCtl *bool `json:"precise_ctl,omitempty"`
}

// CoverConfig is generated from the Shelly API documentation.
type CoverConfig struct {
	// ID the numeric ID of the Cover component instance
	ID int `json:"id"`

	// Name name of the Cover component instance
	Name *string `json:"name,omitempty"`

	// InLocked if True, all changes to physical inputs are ignored, regardless of
	// mode.
	InLocked *bool `json:"in_locked,omitempty"`

	// InitialState defines Cover target state on power-on, one of open (Cover will
	// fully open), closed (Cover will fully close) or stopped (Cover will not change
	// its position)
	InitialState *string `json:"initial_state,omitempty"`

	// PowerLimit watts, a limit that must be exceeded to trigger an overpower error
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit volts, a limit that must be exceeded to trigger an overvoltage
	// error
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`

	// UndervoltageLimit volts, a limit that must be subceeded to trigger an
	// undervoltage error
	UndervoltageLimit *float64 `json:"undervoltage_limit,omitempty"`

	// CurrentLimit amperes, a limit that must be exceeded to trigger an overcurrent
	// error
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	Motor *CoverConfigMotor `json:"motor,omitempty"`
	// MaxtimeOpen default timeout after which Cover will stop moving in open direction
	MaxtimeOpen *float64 `json:"maxtime_open,omitempty"`

	// MaxtimeClose default timeout after which Cover will stop moving in a close
	// direction
	MaxtimeClose *float64 `json:"maxtime_close,omitempty"`

	ObstructionDetection *CoverConfigObstructionDetection `json:"obstruction_detection,omitempty"`
	SafetySwitch         *CoverConfigSafetySwitch         `json:"safety_switch,omitempty"`
	Slat                 *CoverConfigSlat                 `json:"slat,omitempty"`
}

// CoverGetConfigRequest requests the configuration of the Cover component.
type CoverGetConfigRequest struct {
	// ID of the Cover component instance.
	ID int `json:"id"`
}

func (r *CoverGetConfigRequest) Method() string { return "Cover.GetConfig" }

func (r *CoverGetConfigRequest) NewTypedResponse() *CoverConfig { return &CoverConfig{} }

func (r *CoverGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CoverGetConfigRequest) Do(client *resty.Client) (*CoverConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// CoverSetConfigRequest updates the configuration of the Cover component.
type CoverSetConfigRequest struct {
	// ID of the Cover component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config CoverConfig `json:"config"`
}

func (r *CoverSetConfigRequest) Method() string { return "Cover.SetConfig" }

func (r *CoverSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *CoverSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CoverSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
