// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// EM1ConfigAlarms is generated from the Shelly API documentation.
type EM1ConfigAlarms struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EM1Config is generated from the Shelly API documentation.
type EM1Config struct {
	// ID id of the EM1 component instance
	ID int `json:"id"`

	// Name name of the EM1 instance
	Name *string `json:"name,omitempty"`

	// Reverse reverse CT measurement direction of active power and energy for the EM1
	// component. setting the reverse option requires restart
	Reverse *bool `json:"reverse,omitempty"`

	// CtType select the type of Shelly current transformer attached to the device.
	CtType *string `json:"ct_type,omitempty"`

	Alarms *EM1ConfigAlarms `json:"alarms,omitempty"`
}

// EM1GetConfigRequest requests the configuration of the EM1 component.
type EM1GetConfigRequest struct {
	// ID of the EM1 component instance.
	ID int `json:"id"`
}

func (r *EM1GetConfigRequest) Method() string { return "EM1.GetConfig" }

func (r *EM1GetConfigRequest) NewTypedResponse() *EM1Config { return &EM1Config{} }

func (r *EM1GetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1GetConfigRequest) Do(client *resty.Client) (*EM1Config, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EM1SetConfigRequest updates the configuration of the EM1 component.
type EM1SetConfigRequest struct {
	// ID of the EM1 component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config EM1Config `json:"config"`
}

func (r *EM1SetConfigRequest) Method() string { return "EM1.SetConfig" }

func (r *EM1SetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *EM1SetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1SetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
