// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// EM1ConfigAlarms is generated from the Shelly API documentation.
type EM1ConfigAlarms struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EM1Config is generated from the Shelly API documentation.
type EM1Config struct {
	// ID id of the EM1 component instance
	ID int `json:"id"`

	// Name name of the EM1 instance
	Name *string `json:"name,omitempty"`

	// Reverse reverse CT measurement direction of active power and energy for the EM1
	// component. setting the reverse option requires restart
	Reverse *bool `json:"reverse,omitempty"`

	// CtType select the type of Shelly current transformer attached to the device.
	CtType *string `json:"ct_type,omitempty"`

	Alarms *EM1ConfigAlarms `json:"alarms,omitempty"`
}

// EM1GetConfigRequest requests the configuration of the EM1 component.
type EM1GetConfigRequest struct {
	// ID of the EM1 component instance.
	ID int `json:"id"`
}

func (r *EM1GetConfigRequest) Method() string { return "EM1.GetConfig" }

func (r *EM1GetConfigRequest) NewTypedResponse() *EM1Config { return &EM1Config{} }

func (r *EM1GetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1GetConfigRequest) Do(client *resty.Client) (*EM1Config, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EM1SetConfigRequest updates the configuration of the EM1 component.
type EM1SetConfigRequest struct {
	// ID of the EM1 component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config EM1Config `json:"config"`
}

func (r *EM1SetConfigRequest) Method() string { return "EM1.SetConfig" }

func (r *EM1SetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *EM1SetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1SetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EM1Status is generated from the Shelly API documentation.
type EM1Status struct {
	// ID id of the EM1 component instance
	ID int `json:"id"`

	// Current current measurement value, [A]
	Current *float64 `json:"current,omitempty"`

	// Voltage voltage measurement value, [V]
	Voltage *float64 `json:"voltage,omitempty"`

	// ActPower active power measurement value, [W]
	ActPower *float64 `json:"act_power,omitempty"`

	// AprtPower apparent power measurement value, [VA] (if applicable)
	AprtPower *float64 `json:"aprt_power,omitempty"`

	// Pf power factor measurement value (if applicable)
	Pf *float64 `json:"pf,omitempty"`

	// Freq network frequency measurement value (if applicable)
	Freq *float64 `json:"freq,omitempty"`

	// Calibration indicates factory calibration or which EM1:id is the source for
	// calibration
	Calibration *string `json:"calibration,omitempty"`

	// Errors eM1 component error conditions. May contain power_meter_failure,
	// out_of_range:act_power, out_of_range:aprt_power, out_of_range:voltage,
	// out_of_range:current or ct_type_not_set. Present in status only if not empty.
	Errors json.RawMessage `json:"errors,omitempty"`

	// Flags communicates present conditions, shown if at least one flag is set.
	// Depending on component capabilities may contain: count_disabled, undervoltage,
	// overvoltage, undercurrent, overcurrent, underpower, overpower
	Flags json.RawMessage `json:"flags,omitempty"`
}

// EM1GetStatusRequest requests the status of the EM1 component.
type EM1GetStatusRequest struct {
	// ID of the EM1 component instance.
	ID int `json:"id"`
}

func (r *EM1GetStatusRequest) Method() string { return "EM1.GetStatus" }

func (r *EM1GetStatusRequest) NewTypedResponse() *EM1Status { return &EM1Status{} }

func (r *EM1GetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1GetStatusRequest) Do(client *resty.Client) (*EM1Status, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
