// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// EMConfigReverse is generated from the Shelly API documentation.
type EMConfigReverse struct {
	// A when set to true reverse CT measurement direction of active power and energy
	// for phase A. shown if true
	A *bool `json:"a,omitempty"`

	// B when set to true reverse CT measurement direction of active power and energy
	// for phase B. shown if true
	B *bool `json:"b,omitempty"`

	// C when set to true reverse CT measurement direction of active power and energy
	// for phase C. shown if true
	C *bool `json:"c,omitempty"`
}

// EMConfigAlarmsA is generated from the Shelly API documentation.
type EMConfigAlarmsA struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EMConfigAlarmsB is generated from the Shelly API documentation.
type EMConfigAlarmsB struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EMConfigAlarmsC is generated from the Shelly API documentation.
type EMConfigAlarmsC struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EMConfigAlarms is generated from the Shelly API documentation.
type EMConfigAlarms struct {
	A *EMConfigAlarmsA `json:"a,omitempty"`
	B *EMConfigAlarmsB `json:"b,omitempty"`
	C *EMConfigAlarmsC `json:"c,omitempty"`
}

// EMConfig is generated from the Shelly API documentation.
type EMConfig struct {
	// ID id of the EM component instance
	ID int `json:"id"`

	// Name name of the energy meter instance
	Name *string `json:"name,omitempty"`

	// BlinkModeSelector select the electrical quantity that drives the LED. Range of
	// values: active_energy, apparent_energy
	BlinkModeSelector *string `json:"blink_mode_selector,omitempty"`

	// PhaseSelector select witch phase controls the LED. Range of values: a, b, c, all
	PhaseSelector *string `json:"phase_selector,omitempty"`

	// MonitorPhaseSequence set this to show phase_sequence error in GetStatus if
	// three-phase power system is used and the wires are not connected correctly to
	// the device.
	MonitorPhaseSequence *bool `json:"monitor_phase_sequence,omitempty"`

	Reverse *EMConfigReverse `json:"reverse,omitempty"`
	Alarms  *EMConfigAlarms  `json:"alarms,omitempty"`
	// CtType select the type of Shelly current transformer attached to the device.
	CtType *string `json:"ct_type,omitempty"`
}

// EMGetConfigRequest requests the configuration of the EM component.
type EMGetConfigRequest struct {
	// ID of the EM component instance.
	ID int `json:"id"`
}

func (r *EMGetConfigRequest) Method() string { return "EM.GetConfig" }

func (r *EMGetConfigRequest) NewTypedResponse() *EMConfig { return &EMConfig{} }

func (r *EMGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMGetConfigRequest) Do(client *resty.Client) (*EMConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EMSetConfigRequest updates the configuration of the EM component.
type EMSetConfigRequest struct {
	// ID of the EM component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config EMConfig `json:"config"`
}

func (r *EMSetConfigRequest) Method() string { return "EM.SetConfig" }

func (r *EMSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *EMSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
