// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// EMDataConfig is generated from the Shelly API documentation.
type EMDataConfig struct {
	// ID id of the EMData component instance
	ID int `json:"id"`

	// ATotalActEnergy total active energy on phase A, Wh
	ATotalActEnergy *float64 `json:"a_total_act_energy,omitempty"`

	// ATotalActRetEnergy total active returned energy on phase A, Wh
	ATotalActRetEnergy *float64 `json:"a_total_act_ret_energy,omitempty"`

	// BTotalActEnergy total active energy on phase B, Wh
	BTotalActEnergy *float64 `json:"b_total_act_energy,omitempty"`

	// BTotalActRetEnergy total active returned energy on phase B, Wh
	BTotalActRetEnergy *float64 `json:"b_total_act_ret_energy,omitempty"`

	// CTotalActEnergy total active energy on phase C, Wh
	CTotalActEnergy *float64 `json:"c_total_act_energy,omitempty"`

	// CTotalActRetEnergy total active returned energy on phase C, Wh
	CTotalActRetEnergy *float64 `json:"c_total_act_ret_energy,omitempty"`

	// TotalAct total active energy on all phases, Wh
	TotalAct *float64 `json:"total_act,omitempty"`

	// TotalActRet total active returned energy on all phases, Wh
	TotalActRet *float64 `json:"total_act_ret,omitempty"`

	// Errors error condition occurred. May contain database_error or ct_type_not_set,
	// (shown if the error is present).
	Errors json.RawMessage `json:"errors,omitempty"`
}

// EMDataGetConfigRequest requests the configuration of the EMData component.
type EMDataGetConfigRequest struct {
	// ID of the EMData component instance.
	ID int `json:"id"`
}

func (r *EMDataGetConfigRequest) Method() string { return "EMData.GetConfig" }

func (r *EMDataGetConfigRequest) NewTypedResponse() *EMDataConfig { return &EMDataConfig{} }

func (r *EMDataGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMDataGetConfigRequest) Do(client *resty.Client) (*EMDataConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EMDataSetConfigRequest updates the configuration of the EMData component.
type EMDataSetConfigRequest struct {
	// ID of the EMData component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config EMDataConfig `json:"config"`
}

func (r *EMDataSetConfigRequest) Method() string { return "EMData.SetConfig" }

func (r *EMDataSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *EMDataSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMDataSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EMDataStatus is generated from the Shelly API documentation.
type EMDataStatus struct {
	// ID id of the EMData component instance
	ID int `json:"id"`

	// ATotalActEnergy total active energy on phase A, Wh
	ATotalActEnergy *float64 `json:"a_total_act_energy,omitempty"`

	// ATotalActRetEnergy total active returned energy on phase A, Wh
	ATotalActRetEnergy *float64 `json:"a_total_act_ret_energy,omitempty"`

	// BTotalActEnergy total active energy on phase B, Wh
	BTotalActEnergy *float64 `json:"b_total_act_energy,omitempty"`

	// BTotalActRetEnergy total active returned energy on phase B, Wh
	BTotalActRetEnergy *float64 `json:"b_total_act_ret_energy,omitempty"`

	// CTotalActEnergy total active energy on phase C, Wh
	CTotalActEnergy *float64 `json:"c_total_act_energy,omitempty"`

	// CTotalActRetEnergy total active returned energy on phase C, Wh
	CTotalActRetEnergy *float64 `json:"c_total_act_ret_energy,omitempty"`

	// TotalAct total active energy on all phases, Wh
	TotalAct *float64 `json:"total_act,omitempty"`

	// TotalActRet total active returned energy on all phases, Wh
	TotalActRet *float64 `json:"total_act_ret,omitempty"`

	// Errors error condition occurred. May contain database_error or ct_type_not_set,
	// (shown if the error is present).
	Errors json.RawMessage `json:"errors,omitempty"`
}

// EMDataGetStatusRequest requests the status of the EMData component.
type EMDataGetStatusRequest struct {
	// ID of the EMData component instance.
	ID int `json:"id"`
}

func (r *EMDataGetStatusRequest) Method() string { return "EMData.GetStatus" }

func (r *EMDataGetStatusRequest) NewTypedResponse() *EMDataStatus { return &EMDataStatus{} }

func (r *EMDataGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMDataGetStatusRequest) Do(client *resty.Client) (*EMDataStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
