// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// EthConfig is generated from the Shelly API documentation.
type EthConfig struct {
	// Enable true if the connection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// ServerMode true if the inerface is configured to operate in server mode, false
	// if in client mode
	ServerMode *bool `json:"server_mode,omitempty"`

	// Ipv4mode iPv4 mode. Range of values: dhcp, static. Applicable only for client
	// mode. Can be omitted if once set
	Ipv4mode *string `json:"ipv4mode,omitempty"`

	// IP iP in the network for client mode static and for server mode enabled.
	// Required if not already set
	IP *string `json:"ip,omitempty"`

	// Netmask netmask of the network for client mode static and for server mode
	// enabled. Optional, defaults to 255.255.255.0
	Netmask *string `json:"netmask,omitempty"`

	// Gw gateway of the network for client mode static and for server mode enabled.
	// Optional, set to null to clear
	Gw *string `json:"gw,omitempty"`

	// Nameserver nameserver to use for client mode static and for server mode enabled.
	// Optional, set to null to clear
	Nameserver *string `json:"nameserver,omitempty"`

	// DhcpStart dHCP range starting IP address for the DHCP server in server mode.
	// Applicable only for server mode. Required if not already set
	DhcpStart *string `json:"dhcp_start,omitempty"`

	// DhcpEnd dHCP range ending IP address for the DHCP server in server mode.
	// Applicable only for server mode. Required if not already set
	DhcpEnd *string `json:"dhcp_end,omitempty"`
}

// EthGetConfigRequest requests the configuration of the Eth component.
type EthGetConfigRequest struct {
}

func (r *EthGetConfigRequest) Method() string { return "Eth.GetConfig" }

func (r *EthGetConfigRequest) NewTypedResponse() *EthConfig { return &EthConfig{} }

func (r *EthGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EthGetConfigRequest) Do(client *resty.Client) (*EthConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EthSetConfigRequest updates the configuration of the Eth component.
type EthSetConfigRequest struct {
	// Config that the method takes.
	Config EthConfig `json:"config"`
}

func (r *EthSetConfigRequest) Method() string { return "Eth.SetConfig" }

func (r *EthSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *EthSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EthSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// EthStatus is generated from the Shelly API documentation.
type EthStatus struct {
	// IP iP of the device in the network
	IP *string `json:"ip,omitempty"`
}

// EthGetStatusRequest requests the status of the Eth component.
type EthGetStatusRequest struct {
}

func (r *EthGetStatusRequest) Method() string { return "Eth.GetStatus" }

func (r *EthGetStatusRequest) NewTypedResponse() *EthStatus { return &EthStatus{} }

func (r *EthGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EthGetStatusRequest) Do(client *resty.Client) (*EthStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
