// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// FloodConfig is generated from the Shelly API documentation.
type FloodConfig struct {
	// ID id of the Flood component instance
	ID int `json:"id"`

	// Name name of the Flood instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`

	// AlarmMode configuration of sound made on alarm. Accepted values are disabled,
	// normal, intense and rain. When cable is unplugged value is null
	AlarmMode *string `json:"alarm_mode,omitempty"`

	// ReportHoldoff time waited before reporting flood status. For this period status
	// must be steady. Accepted values are between 0-60 sec with step 5 sec
	ReportHoldoff *float64 `json:"report_holdoff,omitempty"`
}

// FloodGetConfigRequest requests the configuration of the Flood component.
type FloodGetConfigRequest struct {
	// ID of the Flood component instance.
	ID int `json:"id"`
}

func (r *FloodGetConfigRequest) Method() string { return "Flood.GetConfig" }

func (r *FloodGetConfigRequest) NewTypedResponse() *FloodConfig { return &FloodConfig{} }

func (r *FloodGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *FloodGetConfigRequest) Do(client *resty.Client) (*FloodConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// FloodSetConfigRequest updates the configuration of the Flood component.
type FloodSetConfigRequest struct {
	// ID of the Flood component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config FloodConfig `json:"config"`
}

func (r *FloodSetConfigRequest) Method() string { return "Flood.SetConfig" }

func (r *FloodSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *FloodSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *FloodSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// FloodStatus is generated from the Shelly API documentation.
type FloodStatus struct {
	// ID id of the Flood component instance
	ID int `json:"id"`

	// Alarm alarm state
	Alarm *bool `json:"alarm,omitempty"`

	// Mute mute state
	Mute *bool `json:"mute,omitempty"`

	// Errors error conditions occurred. May contain cable_unplugged, (shown if at
	// least one error is present)
	Errors json.RawMessage `json:"errors,omitempty"`
}

// FloodGetStatusRequest requests the status of the Flood component.
type FloodGetStatusRequest struct {
	// ID of the Flood component instance.
	ID int `json:"id"`
}

func (r *FloodGetStatusRequest) Method() string { return "Flood.GetStatus" }

func (r *FloodGetStatusRequest) NewTypedResponse() *FloodStatus { return &FloodStatus{} }

func (r *FloodGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *FloodGetStatusRequest) Do(client *resty.Client) (*FloodStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
