// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// HumidityConfig is generated from the Shelly API documentation.
type HumidityConfig struct {
	// ID id of the Humidity component instance
	ID int `json:"id"`

	// Name name of the Humidity instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`

	// ReportThr humidity report threshold in %. Accepted range is device-specific,
	// default [1.0..20.0]% unless specified otherwise
	ReportThr *float64 `json:"report_thr,omitempty"`

	// Offset humidity offset in %. Value is applied to measured humidity. Accepted
	// range is device-specific, default [-50.0..50.0]% unless specified otherwise
	Offset *float64 `json:"offset,omitempty"`
}

// HumidityGetConfigRequest requests the configuration of the Humidity component.
type HumidityGetConfigRequest struct {
	// ID of the Humidity component instance.
	ID int `json:"id"`
}

func (r *HumidityGetConfigRequest) Method() string { return "Humidity.GetConfig" }

func (r *HumidityGetConfigRequest) NewTypedResponse() *HumidityConfig { return &HumidityConfig{} }

func (r *HumidityGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *HumidityGetConfigRequest) Do(client *resty.Client) (*HumidityConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// HumiditySetConfigRequest updates the configuration of the Humidity component.
type HumiditySetConfigRequest struct {
	// ID of the Humidity component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config HumidityConfig `json:"config"`
}

func (r *HumiditySetConfigRequest) Method() string { return "Humidity.SetConfig" }

func (r *HumiditySetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *HumiditySetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *HumiditySetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// HumidityStatus is generated from the Shelly API documentation.
type HumidityStatus struct {
	// ID id of the Humidity component instance
	ID int `json:"id"`

	// Rh relative humidity in % (null if valid value could not be obtained)
	Rh *float64 `json:"rh,omitempty"`

	// Errors shown only if at least one error is present. May contain out_of_range,
	// read when there is problem reading sensor
	Errors json.RawMessage `json:"errors,omitempty"`
}

// HumidityGetStatusRequest requests the status of the Humidity component.
type HumidityGetStatusRequest struct {
	// ID of the Humidity component instance.
	ID int `json:"id"`
}

func (r *HumidityGetStatusRequest) Method() string { return "Humidity.GetStatus" }

func (r *HumidityGetStatusRequest) NewTypedResponse() *HumidityStatus { return &HumidityStatus{} }

func (r *HumidityGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *HumidityGetStatusRequest) Do(client *resty.Client) (*HumidityStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
