// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// IlluminanceConfig is generated from the Shelly API documentation.
type IlluminanceConfig struct {
	// ID id of the Illuminance component instance
	ID int `json:"id"`

	// Name name of the Illuminance instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`

	// DarkThr threshold in lux. Accepted range is device-specific
	DarkThr *float64 `json:"dark_thr,omitempty"`

	// BrightThr bright threshold in lux. Accepted range is device-specific
	BrightThr *float64 `json:"bright_thr,omitempty"`
}

// IlluminanceGetConfigRequest requests the configuration of the Illuminance component.
type IlluminanceGetConfigRequest struct {
	// ID of the Illuminance component instance.
	ID int `json:"id"`
}

func (r *IlluminanceGetConfigRequest) Method() string { return "Illuminance.GetConfig" }

func (r *IlluminanceGetConfigRequest) NewTypedResponse() *IlluminanceConfig {
	return &IlluminanceConfig{}
}

func (r *IlluminanceGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *IlluminanceGetConfigRequest) Do(client *resty.Client) (*IlluminanceConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// IlluminanceSetConfigRequest updates the configuration of the Illuminance component.
type IlluminanceSetConfigRequest struct {
	// ID of the Illuminance component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config IlluminanceConfig `json:"config"`
}

func (r *IlluminanceSetConfigRequest) Method() string { return "Illuminance.SetConfig" }

func (r *IlluminanceSetConfigRequest) NewTypedResponse() *SetConfigResponse {
	return &SetConfigResponse{}
}

func (r *IlluminanceSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *IlluminanceSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
