// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// MatterConfig is generated from the Shelly API documentation.
type MatterConfig struct {
	// Enable set true to enable.
	Enable *bool `json:"enable,omitempty"`
}

// MatterGetConfigRequest requests the configuration of the Matter component.
type MatterGetConfigRequest struct {
}

func (r *MatterGetConfigRequest) Method() string { return "Matter.GetConfig" }

func (r *MatterGetConfigRequest) NewTypedResponse() *MatterConfig { return &MatterConfig{} }

func (r *MatterGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MatterGetConfigRequest) Do(client *resty.Client) (*MatterConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// MatterSetConfigRequest updates the configuration of the Matter component.
type MatterSetConfigRequest struct {
	// Config that the method takes.
	Config MatterConfig `json:"config"`
}

func (r *MatterSetConfigRequest) Method() string { return "Matter.SetConfig" }

func (r *MatterSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *MatterSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MatterSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
