// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// MbRtuClientConfig is generated from the Shelly API documentation.
type MbRtuClientConfig struct {
}

// MbRtuClientGetConfigRequest requests the configuration of the MbRtuClient component.
type MbRtuClientGetConfigRequest struct {
}

func (r *MbRtuClientGetConfigRequest) Method() string { return "MbRtuClient.GetConfig" }

func (r *MbRtuClientGetConfigRequest) NewTypedResponse() *MbRtuClientConfig {
	return &MbRtuClientConfig{}
}

func (r *MbRtuClientGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MbRtuClientGetConfigRequest) Do(client *resty.Client) (*MbRtuClientConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// MbRtuClientSetConfigRequest updates the configuration of the MbRtuClient component.
type MbRtuClientSetConfigRequest struct {
	// Config that the method takes.
	Config MbRtuClientConfig `json:"config"`
}

func (r *MbRtuClientSetConfigRequest) Method() string { return "MbRtuClient.SetConfig" }

func (r *MbRtuClientSetConfigRequest) NewTypedResponse() *SetConfigResponse {
	return &SetConfigResponse{}
}

func (r *MbRtuClientSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MbRtuClientSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
