// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// ModbusConfig is generated from the Shelly API documentation.
type ModbusConfig struct {
	// Enable set true to enable.
	Enable *bool `json:"enable,omitempty"`
}

// ModbusGetConfigRequest requests the configuration of the Modbus component.
type ModbusGetConfigRequest struct {
}

func (r *ModbusGetConfigRequest) Method() string { return "Modbus.GetConfig" }

func (r *ModbusGetConfigRequest) NewTypedResponse() *ModbusConfig { return &ModbusConfig{} }

func (r *ModbusGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ModbusGetConfigRequest) Do(client *resty.Client) (*ModbusConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// ModbusSetConfigRequest updates the configuration of the Modbus component.
type ModbusSetConfigRequest struct {
	// Config that the method takes.
	Config ModbusConfig `json:"config"`
}

func (r *ModbusSetConfigRequest) Method() string { return "Modbus.SetConfig" }

func (r *ModbusSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *ModbusSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ModbusSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
