// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// MQTTConfig is generated from the Shelly API documentation.
type MQTTConfig struct {
	// Enable true if MQTT connection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Server host name of the MQTT server. Can be followed by port number - host:port
	Server *string `json:"server,omitempty"`

	// User username
	User *string `json:"user,omitempty"`

	// RPCNtf enables RPC notifications (NotifyStatus and NotifyEvent) to be published
	// on <device_id|topic_prefix>/events/rpc (<topic_prefix> when a custom prefix is
	// set, <device_id> otherwise). Default value: true.
	RPCNtf *bool `json:"rpc_ntf,omitempty"`

	// StatusNtf enables publishing the complete component status on
	// <device_id|topic_prefix>/status/<component>:<id> (<topic_prefix> when a custom
	// prefix is set, <device_id> otherwise). The complete status will be published if
	// a signifficant change occurred. Default value: false
	StatusNtf *bool `json:"status_ntf,omitempty"`

	// UseClientCert enable or diable usage of client certifactes to use MQTT with
	// encription, default: false
	UseClientCert *bool `json:"use_client_cert,omitempty"`

	// EnableControl enable the MQTT control feature. Defalut value: true
	EnableControl *bool `json:"enable_control,omitempty"`
}

// MQTTGetConfigRequest requests the configuration of the Mqtt component.
type MQTTGetConfigRequest struct {
}

func (r *MQTTGetConfigRequest) Method() string { return "MQTT.GetConfig" }

func (r *MQTTGetConfigRequest) NewTypedResponse() *MQTTConfig { return &MQTTConfig{} }

func (r *MQTTGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MQTTGetConfigRequest) Do(client *resty.Client) (*MQTTConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// MQTTSetConfigRequest updates the configuration of the Mqtt component.
type MQTTSetConfigRequest struct {
	// Config that the method takes.
	Config MQTTConfig `json:"config"`
}

func (r *MQTTSetConfigRequest) Method() string { return "MQTT.SetConfig" }

func (r *MQTTSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *MQTTSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MQTTSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
