// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// PM1ConfigAlarms is generated from the Shelly API documentation.
type PM1ConfigAlarms struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// PM1Config is generated from the Shelly API documentation.
type PM1Config struct {
	// ID id of the PM1 component instance
	ID int `json:"id"`

	// Name name of the PM1 instance
	Name *string `json:"name,omitempty"`

	// Reverse reverse measurement direction of active power and energy for the PM1
	// component. setting the reverse option requires restart
	Reverse *bool `json:"reverse,omitempty"`

	Alarms *PM1ConfigAlarms `json:"alarms,omitempty"`
}

// PM1GetConfigRequest requests the configuration of the PM1 component.
type PM1GetConfigRequest struct {
	// ID of the PM1 component instance.
	ID int `json:"id"`
}

func (r *PM1GetConfigRequest) Method() string { return "PM1.GetConfig" }

func (r *PM1GetConfigRequest) NewTypedResponse() *PM1Config { return &PM1Config{} }

func (r *PM1GetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PM1GetConfigRequest) Do(client *resty.Client) (*PM1Config, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// PM1SetConfigRequest updates the configuration of the PM1 component.
type PM1SetConfigRequest struct {
	// ID of the PM1 component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config PM1Config `json:"config"`
}

func (r *PM1SetConfigRequest) Method() string { return "PM1.SetConfig" }

func (r *PM1SetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *PM1SetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PM1SetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
