// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// PresenceZoneConfig is generated from the Shelly API documentation.
type PresenceZoneConfig struct {
	// ID id of the component instance
	ID int `json:"id"`

	// Name name of the component instance
	Name *string `json:"name,omitempty"`

	// Enable activate or deactivate zone
	Enable *bool `json:"enable,omitempty"`

	// Color preview color defined in format [R, G, B] where every color element is
	// within limit of 0 to 255
	Color json.RawMessage `json:"color,omitempty"`

	// PresenceDelay active period of presence before trigger (in seconds)
	PresenceDelay *float64 `json:"presence_delay,omitempty"`

	// AbsenceDelay active period of absence before trigger (in seconds)
	AbsenceDelay *float64 `json:"absence_delay,omitempty"`

	// Area zone area definition
	Area json.RawMessage `json:"area,omitempty"`
}

// PresenceZoneGetConfigRequest requests the configuration of the PresenceZone component.
type PresenceZoneGetConfigRequest struct {
	// ID of the PresenceZone component instance.
	ID int `json:"id"`
}

func (r *PresenceZoneGetConfigRequest) Method() string { return "PresenceZone.GetConfig" }

func (r *PresenceZoneGetConfigRequest) NewTypedResponse() *PresenceZoneConfig {
	return &PresenceZoneConfig{}
}

func (r *PresenceZoneGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PresenceZoneGetConfigRequest) Do(client *resty.Client) (*PresenceZoneConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// PresenceZoneSetConfigRequest updates the configuration of the PresenceZone component.
type PresenceZoneSetConfigRequest struct {
	// ID of the PresenceZone component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config PresenceZoneConfig `json:"config"`
}

func (r *PresenceZoneSetConfigRequest) Method() string { return "PresenceZone.SetConfig" }

func (r *PresenceZoneSetConfigRequest) NewTypedResponse() *SetConfigResponse {
	return &SetConfigResponse{}
}

func (r *PresenceZoneSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PresenceZoneSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// PresenceZoneStatus is generated from the Shelly API documentation.
type PresenceZoneStatus struct {
	// ID id of the component instance
	ID int `json:"id"`

	// Value state of zone presence
	Value *bool `json:"value,omitempty"`

	// NumObjects number of objects located in zone
	NumObjects *float64 `json:"num_objects,omitempty"`
}

// PresenceZoneGetStatusRequest requests the status of the PresenceZone component.
type PresenceZoneGetStatusRequest struct {
	// ID of the PresenceZone component instance.
	ID int `json:"id"`
}

func (r *PresenceZoneGetStatusRequest) Method() string { return "PresenceZone.GetStatus" }

func (r *PresenceZoneGetStatusRequest) NewTypedResponse() *PresenceZoneStatus {
	return &PresenceZoneStatus{}
}

func (r *PresenceZoneGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PresenceZoneGetStatusRequest) Do(client *resty.Client) (*PresenceZoneStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
