// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// PresenceConfigSensorState is generated from the Shelly API documentation.
type PresenceConfigSensorState struct {
	// DetActThr motion activation threshold
	DetActThr *float64 `json:"det_act_thr,omitempty"`

	// DetFreeThr motion release threshold
	DetFreeThr *float64 `json:"det_free_thr,omitempty"`

	// ActFreeThr tracking loss threshold
	ActFreeThr *float64 `json:"act_free_thr,omitempty"`

	// StatFreeThr stillness tracking threshold
	StatFreeThr *float64 `json:"stat_free_thr,omitempty"`

	// SleepFreeThr stillness timeout threshold
	SleepFreeThr *float64 `json:"sleep_free_thr,omitempty"`
}

// PresenceConfigSensor is generated from the Shelly API documentation.
type PresenceConfigSensor struct {
	// Flipped sensor is flipped by 180 degrees
	Flipped *bool `json:"flipped,omitempty"`

	// Height mount height of sensor (in meters)
	Height *float64 `json:"height,omitempty"`

	// Tilt sensor vertical tilt (see note)
	Tilt *float64 `json:"tilt,omitempty"`

	// Points object recognition threshold
	Points *float64 `json:"points,omitempty"`

	// Velocity velocity threshold
	Velocity *float64 `json:"velocity,omitempty"`

	// Snr sNR threshold
	Snr *float64 `json:"snr,omitempty"`

	// MaxVelocity max velocity difference
	MaxVelocity *float64 `json:"max_velocity,omitempty"`

	// Position mount position of sensor in room can be 'left', 'center' or 'right'
	Position *string `json:"position,omitempty"`

	// Power power of sensor. Can be 'low', 'medium' or 'high'
	Power *string `json:"power,omitempty"`

	// Sensitivity sensor sensitivity. Can be 'low', 'medium' or 'high'
	Sensitivity *string `json:"sensitivity,omitempty"`

	State *PresenceConfigSensorState `json:"state,omitempty"`
}

// PresenceConfigUI is generated from the Shelly API documentation.
type PresenceConfigUI struct {
	// Imperial units are in imeprial system, otherwise units are in metric system
	Imperial *bool `json:"imperial,omitempty"`
}

// PresenceConfigLedsNightMode is generated from the Shelly API documentation.
type PresenceConfigLedsNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit when night mode is active.
	Brightness *float64 `json:"brightness,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optional leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// PresenceConfigLeds is generated from the Shelly API documentation.
type PresenceConfigLeds struct {
	// Brightness max brightness of led
	Brightness *bool `json:"brightness,omitempty"`

	NightMode *PresenceConfigLedsNightMode `json:"night_mode,omitempty"`
}

// PresenceConfig is generated from the Shelly API documentation.
type PresenceConfig struct {
	// Enable enable or disable tracking sensor
	Enable *bool `json:"enable,omitempty"`

	// Zmin lower detection limit in meters
	Zmin *float64 `json:"zmin,omitempty"`

	// Zmax upper detection limit in meters
	Zmax *float64 `json:"zmax,omitempty"`

	Sensor *PresenceConfigSensor `json:"sensor,omitempty"`
	UI     *PresenceConfigUI     `json:"ui,omitempty"`
	// Blind blind zone that sensor will ignore objects (see PresenceZone area
	// configuration)
	Blind json.RawMessage `json:"blind,omitempty"`

	Leds *PresenceConfigLeds `json:"leds,omitempty"`
	// MainZone default presence zone key. (readonly)
	MainZone *string `json:"main_zone,omitempty"`
}

// PresenceGetConfigRequest requests the configuration of the Presence component.
type PresenceGetConfigRequest struct {
}

func (r *PresenceGetConfigRequest) Method() string { return "Presence.GetConfig" }

func (r *PresenceGetConfigRequest) NewTypedResponse() *PresenceConfig { return &PresenceConfig{} }

func (r *PresenceGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PresenceGetConfigRequest) Do(client *resty.Client) (*PresenceConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// PresenceSetConfigRequest updates the configuration of the Presence component.
type PresenceSetConfigRequest struct {
	// Config that the method takes.
	Config PresenceConfig `json:"config"`
}

func (r *PresenceSetConfigRequest) Method() string { return "Presence.SetConfig" }

func (r *PresenceSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *PresenceSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PresenceSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// PresenceStatusLiveTrack is generated from the Shelly API documentation.
type PresenceStatusLiveTrack struct {
	// TimerStartedAt unix timestamp, start time of live tracking (in UTC)
	TimerStartedAt *float64 `json:"timer_started_at,omitempty"`

	// TimerDuration duration of live tracking before stop (in seconds)
	TimerDuration *float64 `json:"timer_duration,omitempty"`

	// Interval interval between events (in seconds)
	Interval *float64 `json:"interval,omitempty"`
}

// PresenceStatus is generated from the Shelly API documentation.
type PresenceStatus struct {
	LiveTrack *PresenceStatusLiveTrack `json:"live_track,omitempty"`
}

// PresenceGetStatusRequest requests the status of the Presence component.
type PresenceGetStatusRequest struct {
}

func (r *PresenceGetStatusRequest) Method() string { return "Presence.GetStatus" }

func (r *PresenceGetStatusRequest) NewTypedResponse() *PresenceStatus { return &PresenceStatus{} }

func (r *PresenceGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PresenceGetStatusRequest) Do(client *resty.Client) (*PresenceStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
