// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// RGBConfigNightMode is generated from the Shelly API documentation.
type RGBConfigNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit (in percent) when night mode is active. null
	// overrides night_mode.brightness with current brightness when night mode starts.
	// Default value 50.
	Brightness *float64 `json:"brightness,omitempty"`

	// RGB color level when night mode is active. Red, Green, Blue [r,g,b] - each value
	// represents level between 0..255. null overrides night_mode.rgb array with
	// current rgb array when night mode starts. Default value 255 for each color
	RGB json.RawMessage `json:"rgb,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optinal leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// RGBConfigButtonPresetsButtonDoublepush is generated from the Shelly API documentation.
type RGBConfigButtonPresetsButtonDoublepush struct {
	// Brightness brightness level (in percent) set on double click (if applicable).
	// null overrides brightness with current brightness when preset is applied.
	// Default 100
	Brightness *float64 `json:"brightness,omitempty"`

	// RGB color level set on double click (if applicable). Red, Green, Blue [r,g,b] -
	// each value represents level between 0..255. null overrides rgb array with
	// current rgb array when preset is applied. Default value 255 for each color
	RGB json.RawMessage `json:"rgb,omitempty"`
}

// RGBConfigButtonPresets is generated from the Shelly API documentation.
type RGBConfigButtonPresets struct {
	ButtonDoublepush *RGBConfigButtonPresetsButtonDoublepush `json:"button_doublepush,omitempty"`
}

// RGBConfig is generated from the Shelly API documentation.
type RGBConfig struct {
	// ID id of the RGB component instance
	ID int `json:"id"`

	// Name name of the RGB instance
	Name *string `json:"name,omitempty"`

	// InMode mode of the associated input. Range of values: follow, flip, activate,
	// detached, dim
	InMode *string `json:"in_mode,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// TransitionDuration transition time (in seconds) - time to change from 0% to 100%
	// of brightness or RGB levels
	TransitionDuration *float64 `json:"transition_duration,omitempty"`

	// MinBrightnessOnToggle brightness level (in percent) applied when there is a
	// toggle and current brightness is lower than min_brightness_on_toggle.
	MinBrightnessOnToggle *float64 `json:"min_brightness_on_toggle,omitempty"`

	NightMode *RGBConfigNightMode `json:"night_mode,omitempty"`
	// ButtonFadeRate controls how quickly the output level changes while a button is
	// held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is
	// fastest, 1 is slowest
	ButtonFadeRate *float64 `json:"button_fade_rate,omitempty"`

	ButtonPresets *RGBConfigButtonPresets `json:"button_presets,omitempty"`
	// CurrentLimit limit (in Amperes) over which overcurrent condition occurs (shown
	// if applicable). For specific devices applies for color channels, not RGB
	// component
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	// PowerLimit limit (in Watts) over which overpower condition occurs (shown if
	// applicable)
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit limit (in Volts) over which overvoltage condition occurs (shown if
	// applicable)
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`
}

// RGBGetConfigRequest requests the configuration of the RGB component.
type RGBGetConfigRequest struct {
	// ID of the RGB component instance.
	ID int `json:"id"`
}

func (r *RGBGetConfigRequest) Method() string { return "RGB.GetConfig" }

func (r *RGBGetConfigRequest) NewTypedResponse() *RGBConfig { return &RGBConfig{} }

func (r *RGBGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBGetConfigRequest) Do(client *resty.Client) (*RGBConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// RGBSetConfigRequest updates the configuration of the RGB component.
type RGBSetConfigRequest struct {
	// ID of the RGB component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config RGBConfig `json:"config"`
}

func (r *RGBSetConfigRequest) Method() string { return "RGB.SetConfig" }

func (r *RGBSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *RGBSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
