// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"

	"resty.dev/v3"
)

// RGBCCTConfigNightMode is generated from the Shelly API documentation.
type RGBCCTConfigNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit (in percent) when night mode is active. null
	// overrides night_mode.brightness with current brightness when night mode starts.
	// Default value 50.
	Brightness *float64 `json:"brightness,omitempty"`

	// RGB color level when night mode is active. Red, Green, Blue [r,g,b] - each value
	// represents level between 0..255. null overrides night_mode.rgb array with
	// current rgb array when night mode starts. Default value 255 for each color
	RGB json.RawMessage `json:"rgb,omitempty"`

	// Ct color temperature level limit (in Kelvin) when night mode is active. null
	// overrides night_mode.ct value with current ct value when night mode starts.
	// Default value: 50% of ct_range. For DuoBulbG3: 4600
	Ct *float64 `json:"ct,omitempty"`

	// Mode operating mode of the light output when night mode is active. Range of
	// values: rgb, cct or null. null overrides night_mode.mode value with current mode
	// when night mode starts. Default value: rgb
	Mode *string `json:"mode,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optinal leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// RGBCCTConfig is generated from the Shelly API documentation.
type RGBCCTConfig struct {
	// ID id of the RGBCCT component instance
	ID int `json:"id"`

	// Name name of the RGBCCT instance
	Name *string `json:"name,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// TransitionDuration transition time (in seconds) - time to change from 0% to 100%
	// of brightness, RGB levels or color temperature value
	TransitionDuration *float64 `json:"transition_duration,omitempty"`

	// MinBrightnessOnToggle brightness level (in percent) applied when there is a
	// toggle and current brightness is lower than min_brightness_on_toggle.
	MinBrightnessOnToggle *float64 `json:"min_brightness_on_toggle,omitempty"`

	NightMode *RGBCCTConfigNightMode `json:"night_mode,omitempty"`
}

// RGBCCTGetConfigRequest requests the configuration of the RGBCCT component.
type RGBCCTGetConfigRequest struct {
	// ID of the RGBCCT component instance.
	ID int `json:"id"`
}

func (r *RGBCCTGetConfigRequest) Method() string { return "RGBCCT.GetConfig" }

func (r *RGBCCTGetConfigRequest) NewTypedResponse() *RGBCCTConfig { return &RGBCCTConfig{} }

func (r *RGBCCTGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBCCTGetConfigRequest) Do(client *resty.Client) (*RGBCCTConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// RGBCCTSetConfigRequest updates the configuration of the RGBCCT component.
type RGBCCTSetConfigRequest struct {
	// ID of the RGBCCT component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config RGBCCTConfig `json:"config"`
}

func (r *RGBCCTSetConfigRequest) Method() string { return "RGBCCT.SetConfig" }

func (r *RGBCCTSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *RGBCCTSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBCCTSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
