// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// ScriptConfig is generated from the Shelly API documentation.
type ScriptConfig struct {
	// ID id of the script
	ID int `json:"id"`

	// Name name of the script
	Name *string `json:"name,omitempty"`

	// Enable true if the script runs by default on boot, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// ScriptGetConfigRequest requests the configuration of the Script component.
type ScriptGetConfigRequest struct {
	// ID of the Script component instance.
	ID int `json:"id"`
}

func (r *ScriptGetConfigRequest) Method() string { return "Script.GetConfig" }

func (r *ScriptGetConfigRequest) NewTypedResponse() *ScriptConfig { return &ScriptConfig{} }

func (r *ScriptGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ScriptGetConfigRequest) Do(client *resty.Client) (*ScriptConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// ScriptSetConfigRequest updates the configuration of the Script component.
type ScriptSetConfigRequest struct {
	// ID of the Script component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config ScriptConfig `json:"config"`
}

func (r *ScriptSetConfigRequest) Method() string { return "Script.SetConfig" }

func (r *ScriptSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *ScriptSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ScriptSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
