// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"
	"fmt"

	"resty.dev/v3"
)

// ShellyGetStatusResponse is the aggregate status of every component, returned by Shelly.GetStatus.
type ShellyGetStatusResponse struct {
	BLE           *BLEStatus            `json:"ble,omitempty"`
	Cloud         *CloudStatus          `json:"cloud,omitempty"`
	DALI          *DALIStatus           `json:"dali,omitempty"`
	Eth           *EthStatus            `json:"eth,omitempty"`
	Matter        *MatterStatus         `json:"matter,omitempty"`
	MbRtuClient   *MbRtuClientStatus    `json:"mbrtuclient,omitempty"`
	Modbus        *ModbusStatus         `json:"modbus,omitempty"`
	MQTT          *MQTTStatus           `json:"mqtt,omitempty"`
	Pill          *PillStatus           `json:"pill,omitempty"`
	Presence      *PresenceStatus       `json:"presence,omitempty"`
	Sys           *SysStatus            `json:"sys,omitempty"`
	Wifi          *WifiStatus           `json:"wifi,omitempty"`
	Ws            *WsStatus             `json:"ws,omitempty"`
	Zigbee        *ZigbeeStatus         `json:"zigbee,omitempty"`
	CCTs          []*CCTStatus          `json:"ccts,omitempty"`
	Covers        []*CoverStatus        `json:"covers,omitempty"`
	DevicePowers  []*DevicePowerStatus  `json:"devicepowers,omitempty"`
	EMs           []*EMStatus           `json:"ems,omitempty"`
	EM1s          []*EM1Status          `json:"em1s,omitempty"`
	EM1Datas      []*EM1DataStatus      `json:"em1datas,omitempty"`
	EMDatas       []*EMDataStatus       `json:"emdatas,omitempty"`
	Floods        []*FloodStatus        `json:"floods,omitempty"`
	Humidities    []*HumidityStatus     `json:"humidities,omitempty"`
	Illuminances  []*IlluminanceStatus  `json:"illuminances,omitempty"`
	Inputs        []*InputStatus        `json:"inputs,omitempty"`
	Lights        []*LightStatus        `json:"lights,omitempty"`
	PM1s          []*PM1Status          `json:"pm1s,omitempty"`
	PresenceZones []*PresenceZoneStatus `json:"presencezones,omitempty"`
	RGBs          []*RGBStatus          `json:"rgbs,omitempty"`
	RGBCCTs       []*RGBCCTStatus       `json:"rgbccts,omitempty"`
	RGBWs         []*RGBWStatus         `json:"rgbws,omitempty"`
	Scripts       []*ScriptStatus       `json:"scripts,omitempty"`
	Smokes        []*SmokeStatus        `json:"smokes,omitempty"`
	Switches      []*SwitchStatus       `json:"switches,omitempty"`
	Temperatures  []*TemperatureStatus  `json:"temperatures,omitempty"`
	Voltmeters    []*VoltmeterStatus    `json:"voltmeters,omitempty"`
}

func (r *ShellyGetStatusResponse) UnmarshalJSON(b []byte) error {
	raw := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["ble"]; ok {
		var s BLEStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.BLE = &s
	}
	if v, ok := raw["cloud"]; ok {
		var s CloudStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Cloud = &s
	}
	if v, ok := raw["dali"]; ok {
		var s DALIStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DALI = &s
	}
	if v, ok := raw["eth"]; ok {
		var s EthStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Eth = &s
	}
	if v, ok := raw["matter"]; ok {
		var s MatterStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Matter = &s
	}
	if v, ok := raw["mbrtuclient"]; ok {
		var s MbRtuClientStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MbRtuClient = &s
	}
	if v, ok := raw["modbus"]; ok {
		var s ModbusStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Modbus = &s
	}
	if v, ok := raw["mqtt"]; ok {
		var s MQTTStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MQTT = &s
	}
	if v, ok := raw["pill"]; ok {
		var s PillStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Pill = &s
	}
	if v, ok := raw["presence"]; ok {
		var s PresenceStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Presence = &s
	}
	if v, ok := raw["sys"]; ok {
		var s SysStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Sys = &s
	}
	if v, ok := raw["wifi"]; ok {
		var s WifiStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Wifi = &s
	}
	if v, ok := raw["ws"]; ok {
		var s WsStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Ws = &s
	}
	if v, ok := raw["zigbee"]; ok {
		var s ZigbeeStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Zigbee = &s
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cct:%d", i)]
		if !ok {
			break
		}
		var s CCTStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.CCTs = append(r.CCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cover:%d", i)]
		if !ok {
			break
		}
		var s CoverStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Covers = append(r.Covers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("devicepower:%d", i)]
		if !ok {
			break
		}
		var s DevicePowerStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DevicePowers = append(r.DevicePowers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em:%d", i)]
		if !ok {
			break
		}
		var s EMStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMs = append(r.EMs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1:%d", i)]
		if !ok {
			break
		}
		var s EM1Status
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1s = append(r.EM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1data:%d", i)]
		if !ok {
			break
		}
		var s EM1DataStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1Datas = append(r.EM1Datas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("emdata:%d", i)]
		if !ok {
			break
		}
		var s EMDataStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMDatas = append(r.EMDatas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("flood:%d", i)]
		if !ok {
			break
		}
		var s FloodStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Floods = append(r.Floods, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("humidity:%d", i)]
		if !ok {
			break
		}
		var s HumidityStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Humidities = append(r.Humidities, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("illuminance:%d", i)]
		if !ok {
			break
		}
		var s IlluminanceStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Illuminances = append(r.Illuminances, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("input:%d", i)]
		if !ok {
			break
		}
		var s InputStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Inputs = append(r.Inputs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("light:%d", i)]
		if !ok {
			break
		}
		var s LightStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Lights = append(r.Lights, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("pm1:%d", i)]
		if !ok {
			break
		}
		var s PM1Status
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PM1s = append(r.PM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("presencezone:%d", i)]
		if !ok {
			break
		}
		var s PresenceZoneStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PresenceZones = append(r.PresenceZones, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgb:%d", i)]
		if !ok {
			break
		}
		var s RGBStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBs = append(r.RGBs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbcct:%d", i)]
		if !ok {
			break
		}
		var s RGBCCTStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBCCTs = append(r.RGBCCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbw:%d", i)]
		if !ok {
			break
		}
		var s RGBWStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBWs = append(r.RGBWs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("script:%d", i)]
		if !ok {
			break
		}
		var s ScriptStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Scripts = append(r.Scripts, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("smoke:%d", i)]
		if !ok {
			break
		}
		var s SmokeStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Smokes = append(r.Smokes, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("switch:%d", i)]
		if !ok {
			break
		}
		var s SwitchStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Switches = append(r.Switches, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("temperature:%d", i)]
		if !ok {
			break
		}
		var s TemperatureStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Temperatures = append(r.Temperatures, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("voltmeter:%d", i)]
		if !ok {
			break
		}
		var s VoltmeterStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Voltmeters = append(r.Voltmeters, &s)
	}
	return nil
}

// ShellyGetStatusRequest requests the aggregate status of every component.
type ShellyGetStatusRequest struct{}

func (r *ShellyGetStatusRequest) Method() string { return "Shelly.GetStatus" }

func (r *ShellyGetStatusRequest) NewTypedResponse() *ShellyGetStatusResponse {
	return &ShellyGetStatusResponse{}
}

func (r *ShellyGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ShellyGetStatusRequest) Do(client *resty.Client) (*ShellyGetStatusResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// ShellyGetConfigResponse is the aggregate config of every component, returned by Shelly.GetConfig.
type ShellyGetConfigResponse struct {
	BLE           *BLEConfig            `json:"ble,omitempty"`
	Cloud         *CloudConfig          `json:"cloud,omitempty"`
	DALI          *DALIConfig           `json:"dali,omitempty"`
	Eth           *EthConfig            `json:"eth,omitempty"`
	Matter        *MatterConfig         `json:"matter,omitempty"`
	MbRtuClient   *MbRtuClientConfig    `json:"mbrtuclient,omitempty"`
	Modbus        *ModbusConfig         `json:"modbus,omitempty"`
	MQTT          *MQTTConfig           `json:"mqtt,omitempty"`
	Pill          *PillConfig           `json:"pill,omitempty"`
	Presence      *PresenceConfig       `json:"presence,omitempty"`
	Sys           *SysConfig            `json:"sys,omitempty"`
	Ui            *UiConfig             `json:"ui,omitempty"`
	Wifi          *WifiConfig           `json:"wifi,omitempty"`
	Ws            *WsConfig             `json:"ws,omitempty"`
	Zigbee        *ZigbeeConfig         `json:"zigbee,omitempty"`
	CCTs          []*CCTConfig          `json:"ccts,omitempty"`
	Covers        []*CoverConfig        `json:"covers,omitempty"`
	DevicePowers  []*DevicePowerConfig  `json:"devicepowers,omitempty"`
	EMs           []*EMConfig           `json:"ems,omitempty"`
	EM1s          []*EM1Config          `json:"em1s,omitempty"`
	EM1Datas      []*EM1DataConfig      `json:"em1datas,omitempty"`
	EMDatas       []*EMDataConfig       `json:"emdatas,omitempty"`
	Floods        []*FloodConfig        `json:"floods,omitempty"`
	Humidities    []*HumidityConfig     `json:"humidities,omitempty"`
	Illuminances  []*IlluminanceConfig  `json:"illuminances,omitempty"`
	Inputs        []*InputConfig        `json:"inputs,omitempty"`
	Lights        []*LightConfig        `json:"lights,omitempty"`
	PM1s          []*PM1Config          `json:"pm1s,omitempty"`
	PresenceZones []*PresenceZoneConfig `json:"presencezones,omitempty"`
	RGBs          []*RGBConfig          `json:"rgbs,omitempty"`
	RGBCCTs       []*RGBCCTConfig       `json:"rgbccts,omitempty"`
	RGBWs         []*RGBWConfig         `json:"rgbws,omitempty"`
	Scripts       []*ScriptConfig       `json:"scripts,omitempty"`
	Serials       []*SerialConfig       `json:"serials,omitempty"`
	Smokes        []*SmokeConfig        `json:"smokes,omitempty"`
	Switches      []*SwitchConfig       `json:"switches,omitempty"`
	Temperatures  []*TemperatureConfig  `json:"temperatures,omitempty"`
	Voltmeters    []*VoltmeterConfig    `json:"voltmeters,omitempty"`
}

func (r *ShellyGetConfigResponse) UnmarshalJSON(b []byte) error {
	raw := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["ble"]; ok {
		var s BLEConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.BLE = &s
	}
	if v, ok := raw["cloud"]; ok {
		var s CloudConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Cloud = &s
	}
	if v, ok := raw["dali"]; ok {
		var s DALIConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DALI = &s
	}
	if v, ok := raw["eth"]; ok {
		var s EthConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Eth = &s
	}
	if v, ok := raw["matter"]; ok {
		var s MatterConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Matter = &s
	}
	if v, ok := raw["mbrtuclient"]; ok {
		var s MbRtuClientConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MbRtuClient = &s
	}
	if v, ok := raw["modbus"]; ok {
		var s ModbusConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Modbus = &s
	}
	if v, ok := raw["mqtt"]; ok {
		var s MQTTConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MQTT = &s
	}
	if v, ok := raw["pill"]; ok {
		var s PillConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Pill = &s
	}
	if v, ok := raw["presence"]; ok {
		var s PresenceConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Presence = &s
	}
	if v, ok := raw["sys"]; ok {
		var s SysConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Sys = &s
	}
	if v, ok := raw["ui"]; ok {
		var s UiConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Ui = &s
	}
	if v, ok := raw["wifi"]; ok {
		var s WifiConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Wifi = &s
	}
	if v, ok := raw["ws"]; ok {
		var s WsConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Ws = &s
	}
	if v, ok := raw["zigbee"]; ok {
		var s ZigbeeConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Zigbee = &s
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cct:%d", i)]
		if !ok {
			break
		}
		var s CCTConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.CCTs = append(r.CCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cover:%d", i)]
		if !ok {
			break
		}
		var s CoverConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Covers = append(r.Covers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("devicepower:%d", i)]
		if !ok {
			break
		}
		var s DevicePowerConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DevicePowers = append(r.DevicePowers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em:%d", i)]
		if !ok {
			break
		}
		var s EMConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMs = append(r.EMs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1:%d", i)]
		if !ok {
			break
		}
		var s EM1Config
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1s = append(r.EM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1data:%d", i)]
		if !ok {
			break
		}
		var s EM1DataConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1Datas = append(r.EM1Datas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("emdata:%d", i)]
		if !ok {
			break
		}
		var s EMDataConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMDatas = append(r.EMDatas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("flood:%d", i)]
		if !ok {
			break
		}
		var s FloodConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Floods = append(r.Floods, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("humidity:%d", i)]
		if !ok {
			break
		}
		var s HumidityConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Humidities = append(r.Humidities, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("illuminance:%d", i)]
		if !ok {
			break
		}
		var s IlluminanceConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Illuminances = append(r.Illuminances, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("input:%d", i)]
		if !ok {
			break
		}
		var s InputConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Inputs = append(r.Inputs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("light:%d", i)]
		if !ok {
			break
		}
		var s LightConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Lights = append(r.Lights, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("pm1:%d", i)]
		if !ok {
			break
		}
		var s PM1Config
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PM1s = append(r.PM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("presencezone:%d", i)]
		if !ok {
			break
		}
		var s PresenceZoneConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PresenceZones = append(r.PresenceZones, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgb:%d", i)]
		if !ok {
			break
		}
		var s RGBConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBs = append(r.RGBs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbcct:%d", i)]
		if !ok {
			break
		}
		var s RGBCCTConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBCCTs = append(r.RGBCCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbw:%d", i)]
		if !ok {
			break
		}
		var s RGBWConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBWs = append(r.RGBWs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("script:%d", i)]
		if !ok {
			break
		}
		var s ScriptConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Scripts = append(r.Scripts, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("serial:%d", i)]
		if !ok {
			break
		}
		var s SerialConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Serials = append(r.Serials, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("smoke:%d", i)]
		if !ok {
			break
		}
		var s SmokeConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Smokes = append(r.Smokes, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("switch:%d", i)]
		if !ok {
			break
		}
		var s SwitchConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Switches = append(r.Switches, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("temperature:%d", i)]
		if !ok {
			break
		}
		var s TemperatureConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Temperatures = append(r.Temperatures, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("voltmeter:%d", i)]
		if !ok {
			break
		}
		var s VoltmeterConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Voltmeters = append(r.Voltmeters, &s)
	}
	return nil
}

// ShellyGetConfigRequest requests the aggregate config of every component.
type ShellyGetConfigRequest struct{}

func (r *ShellyGetConfigRequest) Method() string { return "Shelly.GetConfig" }

func (r *ShellyGetConfigRequest) NewTypedResponse() *ShellyGetConfigResponse {
	return &ShellyGetConfigResponse{}
}

func (r *ShellyGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ShellyGetConfigRequest) Do(client *resty.Client) (*ShellyGetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
