// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import (
	"encoding/json"
	"fmt"

	"github.com/DonRobo/shelly-go/components"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// ShellyGetStatusResponse is the aggregate status of every component, returned by Shelly.GetStatus.
type ShellyGetStatusResponse struct {
	BLE           *components.BLEStatus            `json:"ble,omitempty"`
	Cloud         *components.CloudStatus          `json:"cloud,omitempty"`
	DALI          *components.DALIStatus           `json:"dali,omitempty"`
	Eth           *components.EthStatus            `json:"eth,omitempty"`
	Matter        *components.MatterStatus         `json:"matter,omitempty"`
	MbRtuClient   *components.MbRtuClientStatus    `json:"mbrtuclient,omitempty"`
	Modbus        *components.ModbusStatus         `json:"modbus,omitempty"`
	MQTT          *components.MQTTStatus           `json:"mqtt,omitempty"`
	Pill          *components.PillStatus           `json:"pill,omitempty"`
	Presence      *components.PresenceStatus       `json:"presence,omitempty"`
	Sys           *components.SysStatus            `json:"sys,omitempty"`
	Wifi          *components.WifiStatus           `json:"wifi,omitempty"`
	Ws            *components.WsStatus             `json:"ws,omitempty"`
	Zigbee        *components.ZigbeeStatus         `json:"zigbee,omitempty"`
	CCTs          []*components.CCTStatus          `json:"ccts,omitempty"`
	Covers        []*components.CoverStatus        `json:"covers,omitempty"`
	DevicePowers  []*components.DevicePowerStatus  `json:"devicepowers,omitempty"`
	EMs           []*components.EMStatus           `json:"ems,omitempty"`
	EM1s          []*components.EM1Status          `json:"em1s,omitempty"`
	EM1Datas      []*components.EM1DataStatus      `json:"em1datas,omitempty"`
	EMDatas       []*components.EMDataStatus       `json:"emdatas,omitempty"`
	Floods        []*components.FloodStatus        `json:"floods,omitempty"`
	Humidities    []*components.HumidityStatus     `json:"humidities,omitempty"`
	Illuminances  []*components.IlluminanceStatus  `json:"illuminances,omitempty"`
	Inputs        []*components.InputStatus        `json:"inputs,omitempty"`
	Lights        []*components.LightStatus        `json:"lights,omitempty"`
	PM1s          []*components.PM1Status          `json:"pm1s,omitempty"`
	PresenceZones []*components.PresenceZoneStatus `json:"presencezones,omitempty"`
	RGBs          []*components.RGBStatus          `json:"rgbs,omitempty"`
	RGBCCTs       []*components.RGBCCTStatus       `json:"rgbccts,omitempty"`
	RGBWs         []*components.RGBWStatus         `json:"rgbws,omitempty"`
	Scripts       []*components.ScriptStatus       `json:"scripts,omitempty"`
	Smokes        []*components.SmokeStatus        `json:"smokes,omitempty"`
	Switches      []*components.SwitchStatus       `json:"switches,omitempty"`
	Temperatures  []*components.TemperatureStatus  `json:"temperatures,omitempty"`
	Voltmeters    []*components.VoltmeterStatus    `json:"voltmeters,omitempty"`
}

func (r *ShellyGetStatusResponse) UnmarshalJSON(b []byte) error {
	raw := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["ble"]; ok {
		var s components.BLEStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.BLE = &s
	}
	if v, ok := raw["cloud"]; ok {
		var s components.CloudStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Cloud = &s
	}
	if v, ok := raw["dali"]; ok {
		var s components.DALIStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DALI = &s
	}
	if v, ok := raw["eth"]; ok {
		var s components.EthStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Eth = &s
	}
	if v, ok := raw["matter"]; ok {
		var s components.MatterStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Matter = &s
	}
	if v, ok := raw["mbrtuclient"]; ok {
		var s components.MbRtuClientStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MbRtuClient = &s
	}
	if v, ok := raw["modbus"]; ok {
		var s components.ModbusStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Modbus = &s
	}
	if v, ok := raw["mqtt"]; ok {
		var s components.MQTTStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MQTT = &s
	}
	if v, ok := raw["pill"]; ok {
		var s components.PillStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Pill = &s
	}
	if v, ok := raw["presence"]; ok {
		var s components.PresenceStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Presence = &s
	}
	if v, ok := raw["sys"]; ok {
		var s components.SysStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Sys = &s
	}
	if v, ok := raw["wifi"]; ok {
		var s components.WifiStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Wifi = &s
	}
	if v, ok := raw["ws"]; ok {
		var s components.WsStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Ws = &s
	}
	if v, ok := raw["zigbee"]; ok {
		var s components.ZigbeeStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Zigbee = &s
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cct:%d", i)]
		if !ok {
			break
		}
		var s components.CCTStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.CCTs = append(r.CCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cover:%d", i)]
		if !ok {
			break
		}
		var s components.CoverStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Covers = append(r.Covers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("devicepower:%d", i)]
		if !ok {
			break
		}
		var s components.DevicePowerStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DevicePowers = append(r.DevicePowers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em:%d", i)]
		if !ok {
			break
		}
		var s components.EMStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMs = append(r.EMs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1:%d", i)]
		if !ok {
			break
		}
		var s components.EM1Status
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1s = append(r.EM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1data:%d", i)]
		if !ok {
			break
		}
		var s components.EM1DataStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1Datas = append(r.EM1Datas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("emdata:%d", i)]
		if !ok {
			break
		}
		var s components.EMDataStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMDatas = append(r.EMDatas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("flood:%d", i)]
		if !ok {
			break
		}
		var s components.FloodStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Floods = append(r.Floods, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("humidity:%d", i)]
		if !ok {
			break
		}
		var s components.HumidityStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Humidities = append(r.Humidities, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("illuminance:%d", i)]
		if !ok {
			break
		}
		var s components.IlluminanceStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Illuminances = append(r.Illuminances, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("input:%d", i)]
		if !ok {
			break
		}
		var s components.InputStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Inputs = append(r.Inputs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("light:%d", i)]
		if !ok {
			break
		}
		var s components.LightStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Lights = append(r.Lights, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("pm1:%d", i)]
		if !ok {
			break
		}
		var s components.PM1Status
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PM1s = append(r.PM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("presencezone:%d", i)]
		if !ok {
			break
		}
		var s components.PresenceZoneStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PresenceZones = append(r.PresenceZones, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgb:%d", i)]
		if !ok {
			break
		}
		var s components.RGBStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBs = append(r.RGBs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbcct:%d", i)]
		if !ok {
			break
		}
		var s components.RGBCCTStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBCCTs = append(r.RGBCCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbw:%d", i)]
		if !ok {
			break
		}
		var s components.RGBWStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBWs = append(r.RGBWs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("script:%d", i)]
		if !ok {
			break
		}
		var s components.ScriptStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Scripts = append(r.Scripts, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("smoke:%d", i)]
		if !ok {
			break
		}
		var s components.SmokeStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Smokes = append(r.Smokes, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("switch:%d", i)]
		if !ok {
			break
		}
		var s components.SwitchStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Switches = append(r.Switches, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("temperature:%d", i)]
		if !ok {
			break
		}
		var s components.TemperatureStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Temperatures = append(r.Temperatures, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("voltmeter:%d", i)]
		if !ok {
			break
		}
		var s components.VoltmeterStatus
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Voltmeters = append(r.Voltmeters, &s)
	}
	return nil
}

// ShellyGetStatusRequest requests the aggregate status of every component.
type ShellyGetStatusRequest struct{}

func (r *ShellyGetStatusRequest) Method() string { return "Shelly.GetStatus" }

func (r *ShellyGetStatusRequest) NewTypedResponse() *ShellyGetStatusResponse {
	return &ShellyGetStatusResponse{}
}

func (r *ShellyGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ShellyGetStatusRequest) Do(client *resty.Client) (*ShellyGetStatusResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// ShellyGetConfigResponse is the aggregate config of every component, returned by Shelly.GetConfig.
type ShellyGetConfigResponse struct {
	BLE           *components.BLEConfig            `json:"ble,omitempty"`
	Cloud         *components.CloudConfig          `json:"cloud,omitempty"`
	DALI          *components.DALIConfig           `json:"dali,omitempty"`
	Eth           *components.EthConfig            `json:"eth,omitempty"`
	Matter        *components.MatterConfig         `json:"matter,omitempty"`
	MbRtuClient   *components.MbRtuClientConfig    `json:"mbrtuclient,omitempty"`
	Modbus        *components.ModbusConfig         `json:"modbus,omitempty"`
	MQTT          *components.MQTTConfig           `json:"mqtt,omitempty"`
	Pill          *components.PillConfig           `json:"pill,omitempty"`
	Presence      *components.PresenceConfig       `json:"presence,omitempty"`
	Sys           *components.SysConfig            `json:"sys,omitempty"`
	Ui            *components.UiConfig             `json:"ui,omitempty"`
	Wifi          *components.WifiConfig           `json:"wifi,omitempty"`
	Ws            *components.WsConfig             `json:"ws,omitempty"`
	Zigbee        *components.ZigbeeConfig         `json:"zigbee,omitempty"`
	CCTs          []*components.CCTConfig          `json:"ccts,omitempty"`
	Covers        []*components.CoverConfig        `json:"covers,omitempty"`
	DevicePowers  []*components.DevicePowerConfig  `json:"devicepowers,omitempty"`
	EMs           []*components.EMConfig           `json:"ems,omitempty"`
	EM1s          []*components.EM1Config          `json:"em1s,omitempty"`
	EM1Datas      []*components.EM1DataConfig      `json:"em1datas,omitempty"`
	EMDatas       []*components.EMDataConfig       `json:"emdatas,omitempty"`
	Floods        []*components.FloodConfig        `json:"floods,omitempty"`
	Humidities    []*components.HumidityConfig     `json:"humidities,omitempty"`
	Illuminances  []*components.IlluminanceConfig  `json:"illuminances,omitempty"`
	Inputs        []*components.InputConfig        `json:"inputs,omitempty"`
	Lights        []*components.LightConfig        `json:"lights,omitempty"`
	PM1s          []*components.PM1Config          `json:"pm1s,omitempty"`
	PresenceZones []*components.PresenceZoneConfig `json:"presencezones,omitempty"`
	RGBs          []*components.RGBConfig          `json:"rgbs,omitempty"`
	RGBCCTs       []*components.RGBCCTConfig       `json:"rgbccts,omitempty"`
	RGBWs         []*components.RGBWConfig         `json:"rgbws,omitempty"`
	Scripts       []*components.ScriptConfig       `json:"scripts,omitempty"`
	Serials       []*components.SerialConfig       `json:"serials,omitempty"`
	Smokes        []*components.SmokeConfig        `json:"smokes,omitempty"`
	Switches      []*components.SwitchConfig       `json:"switches,omitempty"`
	Temperatures  []*components.TemperatureConfig  `json:"temperatures,omitempty"`
	Voltmeters    []*components.VoltmeterConfig    `json:"voltmeters,omitempty"`
}

func (r *ShellyGetConfigResponse) UnmarshalJSON(b []byte) error {
	raw := make(map[string]json.RawMessage)
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["ble"]; ok {
		var s components.BLEConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.BLE = &s
	}
	if v, ok := raw["cloud"]; ok {
		var s components.CloudConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Cloud = &s
	}
	if v, ok := raw["dali"]; ok {
		var s components.DALIConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DALI = &s
	}
	if v, ok := raw["eth"]; ok {
		var s components.EthConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Eth = &s
	}
	if v, ok := raw["matter"]; ok {
		var s components.MatterConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Matter = &s
	}
	if v, ok := raw["mbrtuclient"]; ok {
		var s components.MbRtuClientConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MbRtuClient = &s
	}
	if v, ok := raw["modbus"]; ok {
		var s components.ModbusConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Modbus = &s
	}
	if v, ok := raw["mqtt"]; ok {
		var s components.MQTTConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.MQTT = &s
	}
	if v, ok := raw["pill"]; ok {
		var s components.PillConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Pill = &s
	}
	if v, ok := raw["presence"]; ok {
		var s components.PresenceConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Presence = &s
	}
	if v, ok := raw["sys"]; ok {
		var s components.SysConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Sys = &s
	}
	if v, ok := raw["ui"]; ok {
		var s components.UiConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Ui = &s
	}
	if v, ok := raw["wifi"]; ok {
		var s components.WifiConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Wifi = &s
	}
	if v, ok := raw["ws"]; ok {
		var s components.WsConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Ws = &s
	}
	if v, ok := raw["zigbee"]; ok {
		var s components.ZigbeeConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Zigbee = &s
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cct:%d", i)]
		if !ok {
			break
		}
		var s components.CCTConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.CCTs = append(r.CCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("cover:%d", i)]
		if !ok {
			break
		}
		var s components.CoverConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Covers = append(r.Covers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("devicepower:%d", i)]
		if !ok {
			break
		}
		var s components.DevicePowerConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.DevicePowers = append(r.DevicePowers, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em:%d", i)]
		if !ok {
			break
		}
		var s components.EMConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMs = append(r.EMs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1:%d", i)]
		if !ok {
			break
		}
		var s components.EM1Config
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1s = append(r.EM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("em1data:%d", i)]
		if !ok {
			break
		}
		var s components.EM1DataConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EM1Datas = append(r.EM1Datas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("emdata:%d", i)]
		if !ok {
			break
		}
		var s components.EMDataConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.EMDatas = append(r.EMDatas, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("flood:%d", i)]
		if !ok {
			break
		}
		var s components.FloodConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Floods = append(r.Floods, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("humidity:%d", i)]
		if !ok {
			break
		}
		var s components.HumidityConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Humidities = append(r.Humidities, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("illuminance:%d", i)]
		if !ok {
			break
		}
		var s components.IlluminanceConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Illuminances = append(r.Illuminances, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("input:%d", i)]
		if !ok {
			break
		}
		var s components.InputConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Inputs = append(r.Inputs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("light:%d", i)]
		if !ok {
			break
		}
		var s components.LightConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Lights = append(r.Lights, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("pm1:%d", i)]
		if !ok {
			break
		}
		var s components.PM1Config
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PM1s = append(r.PM1s, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("presencezone:%d", i)]
		if !ok {
			break
		}
		var s components.PresenceZoneConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.PresenceZones = append(r.PresenceZones, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgb:%d", i)]
		if !ok {
			break
		}
		var s components.RGBConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBs = append(r.RGBs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbcct:%d", i)]
		if !ok {
			break
		}
		var s components.RGBCCTConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBCCTs = append(r.RGBCCTs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("rgbw:%d", i)]
		if !ok {
			break
		}
		var s components.RGBWConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.RGBWs = append(r.RGBWs, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("script:%d", i)]
		if !ok {
			break
		}
		var s components.ScriptConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Scripts = append(r.Scripts, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("serial:%d", i)]
		if !ok {
			break
		}
		var s components.SerialConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Serials = append(r.Serials, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("smoke:%d", i)]
		if !ok {
			break
		}
		var s components.SmokeConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Smokes = append(r.Smokes, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("switch:%d", i)]
		if !ok {
			break
		}
		var s components.SwitchConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Switches = append(r.Switches, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("temperature:%d", i)]
		if !ok {
			break
		}
		var s components.TemperatureConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Temperatures = append(r.Temperatures, &s)
	}
	for i := 0; ; i++ {
		v, ok := raw[fmt.Sprintf("voltmeter:%d", i)]
		if !ok {
			break
		}
		var s components.VoltmeterConfig
		if err := json.Unmarshal(v, &s); err != nil {
			return err
		}
		r.Voltmeters = append(r.Voltmeters, &s)
	}
	return nil
}

// ShellyGetConfigRequest requests the aggregate config of every component.
type ShellyGetConfigRequest struct{}

func (r *ShellyGetConfigRequest) Method() string { return "Shelly.GetConfig" }

func (r *ShellyGetConfigRequest) NewTypedResponse() *ShellyGetConfigResponse {
	return &ShellyGetConfigResponse{}
}

func (r *ShellyGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ShellyGetConfigRequest) Do(client *resty.Client) (*ShellyGetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// ShellyGetDeviceInfoResponse is generated from the Shelly API documentation.
type ShellyGetDeviceInfoResponse struct {
	// ID id of the device
	ID string `json:"id"`

	// MAC mac address of the device
	MAC *string `json:"mac,omitempty"`

	// Model model of the device
	Model *string `json:"model,omitempty"`

	// Gen generation of the device
	Gen *float64 `json:"gen,omitempty"`

	// FWID id of the firmware of the device
	FWID *string `json:"fw_id,omitempty"`

	// Ver version of the firmware of the device
	Ver *string `json:"ver,omitempty"`

	// App application name
	App *string `json:"app,omitempty"`

	// Profile name of the device profile (only applicable for multi-profile devices)
	Profile *string `json:"profile,omitempty"`

	// AuthEn true if authentication is enabled, false otherwise
	AuthEn *bool `json:"auth_en,omitempty"`

	// AuthDomain name of the domain (null if authentication is not enabled)
	AuthDomain *string `json:"auth_domain,omitempty"`

	// Discoverable present only when false. If true, device is shown in 'Discovered
	// devices'. If false, the device is hidden.
	Discoverable *bool `json:"discoverable,omitempty"`

	// Provision (since 1.7.5) Indicates the provisioning state of the device. Possible
	// values: "pending" (initial unprovisioned state: open AP & BLE RPC are available
	// for 15 minutes setup window, or 3 minutes on battery-powered devices),
	// "confirmed" (first IP acquisition over Wi-Fi/Ethernet: open AP & BLE RPC are
	// available for 5 minutes grace window; on battery-powered devices, the original
	// 3-minute setup timer continues instead), "complete" (grace window expired: AP
	// (unless protected with a password) & BLE RPC are disabled), "locked" (initial
	// setup window expired without going online: AP (unless protected with a password)
	// & BLE RPC are temporarily shut down until device is power-cycled, a
	// factory/network reset occurs, or user button is pressed (latter only applicable
	// to battery-powered devices)). See Secure provisioning for more details.
	Provision *string `json:"provision,omitempty"`

	// Key cloud key of the device (see note below), present only when the ident
	// parameter is set to true
	Key *string `json:"key,omitempty"`

	// Batch batch used to provision the device, present only when the ident parameter
	// is set to true
	Batch *string `json:"batch,omitempty"`

	// FWSbits shelly internal flags, present only when the ident parameter is set to
	// true
	FWSbits *string `json:"fw_sbits,omitempty"`
}

// ShellyGetDeviceInfoRequest requests static device information via Shelly.GetDeviceInfo.
type ShellyGetDeviceInfoRequest struct {
	// Ident includes extra identifying fields (key, batch, fw_sbits) when true.
	Ident *bool `json:"ident,omitempty"`
}

func (r *ShellyGetDeviceInfoRequest) Method() string { return "Shelly.GetDeviceInfo" }

func (r *ShellyGetDeviceInfoRequest) NewTypedResponse() *ShellyGetDeviceInfoResponse {
	return &ShellyGetDeviceInfoResponse{}
}

func (r *ShellyGetDeviceInfoRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ShellyGetDeviceInfoRequest) Do(client *resty.Client) (*ShellyGetDeviceInfoResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
