// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// UiConfig is generated from the Shelly API documentation.
type UiConfig struct {
	// IdleBrightness brightness of the device's screen while idle, in percent (0-100).
	// Not documented by Shelly; sourced via device introspection.
	IdleBrightness *int `json:"idle_brightness,omitempty"`
}

// UiGetConfigRequest requests the configuration of the Ui component.
type UiGetConfigRequest struct {
}

func (r *UiGetConfigRequest) Method() string { return "Ui.GetConfig" }

func (r *UiGetConfigRequest) NewTypedResponse() *UiConfig { return &UiConfig{} }

func (r *UiGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *UiGetConfigRequest) Do(client *resty.Client) (*UiConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// UiSetConfigRequest updates the configuration of the Ui component.
type UiSetConfigRequest struct {
	// Config that the method takes.
	Config UiConfig `json:"config"`
}

func (r *UiSetConfigRequest) Method() string { return "Ui.SetConfig" }

func (r *UiSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *UiSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *UiSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
