// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// WsConfig is generated from the Shelly API documentation.
type WsConfig struct {
	// Enable true if websocket outbound connection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Server name of the server to which the device is connected. When prefixed with
	// wss:// a TLS socket will be used
	Server *string `json:"server,omitempty"`
}

// WsGetConfigRequest requests the configuration of the Ws component.
type WsGetConfigRequest struct {
}

func (r *WsGetConfigRequest) Method() string { return "Ws.GetConfig" }

func (r *WsGetConfigRequest) NewTypedResponse() *WsConfig { return &WsConfig{} }

func (r *WsGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WsGetConfigRequest) Do(client *resty.Client) (*WsConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// WsSetConfigRequest updates the configuration of the Ws component.
type WsSetConfigRequest struct {
	// Config that the method takes.
	Config WsConfig `json:"config"`
}

func (r *WsSetConfigRequest) Method() string { return "Ws.SetConfig" }

func (r *WsSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *WsSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WsSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
