// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package shelly

import "resty.dev/v3"

// ZigbeeConfig is generated from the Shelly API documentation.
type ZigbeeConfig struct {
	// Enable true if Zigbee connectivity is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// ZigbeeGetConfigRequest requests the configuration of the Zigbee component.
type ZigbeeGetConfigRequest struct {
}

func (r *ZigbeeGetConfigRequest) Method() string { return "Zigbee.GetConfig" }

func (r *ZigbeeGetConfigRequest) NewTypedResponse() *ZigbeeConfig { return &ZigbeeConfig{} }

func (r *ZigbeeGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ZigbeeGetConfigRequest) Do(client *resty.Client) (*ZigbeeConfig, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// ZigbeeSetConfigRequest updates the configuration of the Zigbee component.
type ZigbeeSetConfigRequest struct {
	// Config that the method takes.
	Config ZigbeeConfig `json:"config"`
}

func (r *ZigbeeSetConfigRequest) Method() string { return "Zigbee.SetConfig" }

func (r *ZigbeeSetConfigRequest) NewTypedResponse() *SetConfigResponse { return &SetConfigResponse{} }

func (r *ZigbeeSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ZigbeeSetConfigRequest) Do(client *resty.Client) (*SetConfigResponse, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}

// ZigbeeStatus is generated from the Shelly API documentation.
type ZigbeeStatus struct {
	// NetworkState status of the connection. Range of values: disabled, initializing,
	// steering, joined, failed
	NetworkState *string `json:"network_state,omitempty"`
}

// ZigbeeGetStatusRequest requests the status of the Zigbee component.
type ZigbeeGetStatusRequest struct {
}

func (r *ZigbeeGetStatusRequest) Method() string { return "Zigbee.GetStatus" }

func (r *ZigbeeGetStatusRequest) NewTypedResponse() *ZigbeeStatus { return &ZigbeeStatus{} }

func (r *ZigbeeGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ZigbeeGetStatusRequest) Do(client *resty.Client) (*ZigbeeStatus, *Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := Do(client, r, resp)
	return resp, raw, err
}
