// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// BLEConfigRPC is generated from the Shelly API documentation.
type BLEConfigRPC struct {
	// Enable true if rpc service is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// BLEConfig is generated from the Shelly API documentation.
type BLEConfig struct {
	RPC *BLEConfigRPC `json:"rpc,omitempty"`
}

// BLEGetConfigRequest requests the configuration of the BLE component.
type BLEGetConfigRequest struct {
}

func (r *BLEGetConfigRequest) Method() string { return "BLE.GetConfig" }

func (r *BLEGetConfigRequest) NewTypedResponse() *BLEConfig { return &BLEConfig{} }

func (r *BLEGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *BLEGetConfigRequest) Do(client *resty.Client) (*BLEConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// BLESetConfigRequest updates the configuration of the BLE component.
type BLESetConfigRequest struct {
	// Config that the method takes.
	Config BLEConfig `json:"config"`
}

func (r *BLESetConfigRequest) Method() string { return "BLE.SetConfig" }

func (r *BLESetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *BLESetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *BLESetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// BLEStatusPairing is generated from the Shelly API documentation.
type BLEStatusPairing struct {
	// StartedAt unix timestamp when pairing mode was enabled
	StartedAt *int `json:"started_at,omitempty"`

	// Duration duration in seconds for which pairing mode is enabled
	Duration *int `json:"duration,omitempty"`
}

// BLEStatusBlutrvAssoc is generated from the Shelly API documentation.
type BLEStatusBlutrvAssoc struct {
	// Duration duration of the current associations procedure in seconds
	Duration *int `json:"duration,omitempty"`

	// StartedAt unix timestamp of the start of the associations procedure
	StartedAt *int `json:"started_at,omitempty"`
}

// BLEStatus is generated from the Shelly API documentation.
type BLEStatus struct {
	// Addr the device's Bluetooth MAC address with type suffix: ,p (public), ,rs
	// (random static), ,rn (random non-resolvable), or ,rr (random resolvable).
	// Example: "AA:BB:CC:DD:EE:FF,p"
	Addr *string `json:"addr,omitempty"`

	// Flags (Since 2.0.0) When Bluetooth is active, contains one or more of:
	// "scanning", "advertising", "connected". When Bluetooth is idle, this property is
	// absent from the response. Status change notifications are emitted whenever the
	// flags array changes.
	Flags []string `json:"flags,omitempty"`

	Pairing     *BLEStatusPairing     `json:"pairing,omitempty"`
	BlutrvAssoc *BLEStatusBlutrvAssoc `json:"blutrv_assoc,omitempty"`
}

// BLEGetStatusRequest requests the status of the BLE component.
type BLEGetStatusRequest struct {
}

func (r *BLEGetStatusRequest) Method() string { return "BLE.GetStatus" }

func (r *BLEGetStatusRequest) NewTypedResponse() *BLEStatus { return &BLEStatus{} }

func (r *BLEGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *BLEGetStatusRequest) Do(client *resty.Client) (*BLEStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
