// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// CloudConfig is generated from the Shelly API documentation.
type CloudConfig struct {
	// Enable true if cloud connection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Server name of the server to which the device is connected
	Server *string `json:"server,omitempty"`
}

// CloudGetConfigRequest requests the configuration of the Cloud component.
type CloudGetConfigRequest struct {
}

func (r *CloudGetConfigRequest) Method() string { return "Cloud.GetConfig" }

func (r *CloudGetConfigRequest) NewTypedResponse() *CloudConfig { return &CloudConfig{} }

func (r *CloudGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CloudGetConfigRequest) Do(client *resty.Client) (*CloudConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// CloudSetConfigRequest updates the configuration of the Cloud component.
type CloudSetConfigRequest struct {
	// Config that the method takes.
	Config CloudConfig `json:"config"`
}

func (r *CloudSetConfigRequest) Method() string { return "Cloud.SetConfig" }

func (r *CloudSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *CloudSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CloudSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// CloudStatus is generated from the Shelly API documentation.
type CloudStatus struct {
	// Connected true if the device is connected to the Shelly cloud, false otherwise
	Connected *bool `json:"connected,omitempty"`
}

// CloudGetStatusRequest requests the status of the Cloud component.
type CloudGetStatusRequest struct {
}

func (r *CloudGetStatusRequest) Method() string { return "Cloud.GetStatus" }

func (r *CloudGetStatusRequest) NewTypedResponse() *CloudStatus { return &CloudStatus{} }

func (r *CloudGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CloudGetStatusRequest) Do(client *resty.Client) (*CloudStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
