// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// CoverConfigMotor is generated from the Shelly API documentation.
type CoverConfigMotor struct {
	// IdlePowerThr watts, threshold below which the motor is considered stopped
	IdlePowerThr *float64 `json:"idle_power_thr,omitempty"`

	// IdleConfirmPeriod seconds, the minimum period of time in idle state before the
	// state is confirmed
	IdleConfirmPeriod *float64 `json:"idle_confirm_period,omitempty"`
}

// CoverConfigObstructionDetection is generated from the Shelly API documentation.
type CoverConfigObstructionDetection struct {
	// Enable true when obstruction detection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Direction the direction of motion for which the safety switch should be
	// monitored, one of open, close, both
	Direction *string `json:"direction,omitempty"`

	// PowerThr watts, power consumption above this threshold should be interpreted as
	// objects obstructing Cover movement. This property is editable at any time, but
	// note that during the cover calibration procedure (Cover.Calibrate), power_thr
	// will be automatically set to the peak power consumption + 15%, overwriting the
	// current value. The automatic setup of power_thr during calibration will only
	// start tracking power values when the holdoff time (see below) has elapsed
	PowerThr *float64 `json:"power_thr,omitempty"`

	// Holdoff seconds, time to wait after Cover starts moving before obstruction
	// detection is activated (to avoid false detections because of the initial power
	// consumption spike)
	Holdoff *float64 `json:"holdoff,omitempty"`
}

// CoverConfigSafetySwitch is generated from the Shelly API documentation.
type CoverConfigSafetySwitch struct {
	// Enable true when the safety switch is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Direction the direction of motion for which the safety switch should be
	// monitored, one of open, close, both
	Direction *string `json:"direction,omitempty"`
}

// CoverConfigSlat is generated from the Shelly API documentation.
type CoverConfigSlat struct {
	// Enable true when slat control is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// OpenTime time it takes for slats to move from fully closed (0%) to fully open
	// (100%) position, seconds. Must be manually configured by the user. Accepted
	// range: [0.5..30]s
	OpenTime *float64 `json:"open_time,omitempty"`

	// CloseTime time it takes for slats to move from fully open (100%) to fully closed
	// (100%) position, seconds. Must be manually configured by the user. Accepted
	// range: [0.5..30]s
	CloseTime *float64 `json:"close_time,omitempty"`

	// Step single step movement spread, represented as % from the full range (used
	// only when slats are controlled via inputs). Accepted range: [1..100]%
	Step *float64 `json:"step,omitempty"`

	// RetainPos whether to retain slat position when cover (vertical) position is
	// changed
	RetainPos *bool `json:"retain_pos,omitempty"`

	// PreciseCtl this property only applies when cover (vertical) position is less
	// than one full slat rotation away from the fully closed position. If this
	// condition is met, any slat movement will always go through fully closed position
	// first. This improves slat positioning accuracy, yet is slower to execute.
	PreciseCtl *bool `json:"precise_ctl,omitempty"`
}

// CoverConfig is generated from the Shelly API documentation.
type CoverConfig struct {
	// ID the numeric ID of the Cover component instance
	ID int `json:"id"`

	// Name name of the Cover component instance
	Name *string `json:"name,omitempty"`

	// InLocked if True, all changes to physical inputs are ignored, regardless of
	// mode.
	InLocked *bool `json:"in_locked,omitempty"`

	// InitialState defines Cover target state on power-on, one of open (Cover will
	// fully open), closed (Cover will fully close) or stopped (Cover will not change
	// its position)
	InitialState *string `json:"initial_state,omitempty"`

	// PowerLimit watts, a limit that must be exceeded to trigger an overpower error
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit volts, a limit that must be exceeded to trigger an overvoltage
	// error
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`

	// UndervoltageLimit volts, a limit that must be subceeded to trigger an
	// undervoltage error
	UndervoltageLimit *float64 `json:"undervoltage_limit,omitempty"`

	// CurrentLimit amperes, a limit that must be exceeded to trigger an overcurrent
	// error
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	Motor *CoverConfigMotor `json:"motor,omitempty"`
	// MaxtimeOpen default timeout after which Cover will stop moving in open direction
	MaxtimeOpen *float64 `json:"maxtime_open,omitempty"`

	// MaxtimeClose default timeout after which Cover will stop moving in a close
	// direction
	MaxtimeClose *float64 `json:"maxtime_close,omitempty"`

	ObstructionDetection *CoverConfigObstructionDetection `json:"obstruction_detection,omitempty"`
	SafetySwitch         *CoverConfigSafetySwitch         `json:"safety_switch,omitempty"`
	Slat                 *CoverConfigSlat                 `json:"slat,omitempty"`
}

// CoverGetConfigRequest requests the configuration of the Cover component.
type CoverGetConfigRequest struct {
	// ID of the Cover component instance.
	ID int `json:"id"`
}

func (r *CoverGetConfigRequest) Method() string { return "Cover.GetConfig" }

func (r *CoverGetConfigRequest) NewTypedResponse() *CoverConfig { return &CoverConfig{} }

func (r *CoverGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CoverGetConfigRequest) Do(client *resty.Client) (*CoverConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// CoverSetConfigRequest updates the configuration of the Cover component.
type CoverSetConfigRequest struct {
	// ID of the Cover component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config CoverConfig `json:"config"`
}

func (r *CoverSetConfigRequest) Method() string { return "Cover.SetConfig" }

func (r *CoverSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *CoverSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CoverSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// CoverStatusAenergy is generated from the Shelly API documentation.
type CoverStatusAenergy struct {
	// Total total energy consumed in Watt-hours.
	Total *float64 `json:"total,omitempty"`

	// ByMinute energy consumption by minute (in Milliwatt-hours) for the last three
	// minutes.
	ByMinute []float64 `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp of the first second of the last minute.
	MinuteTs *int `json:"minute_ts,omitempty"`
}

// CoverStatusTemperature is generated from the Shelly API documentation.
type CoverStatusTemperature struct {
	// TC temperature in Celsius (null if temperature is out of the measurement range).
	TC *float64 `json:"tC,omitempty"`

	// TF temperature in Fahrenheit (null if temperature is out of the measurement
	// range).
	TF *float64 `json:"tF,omitempty"`
}

// CoverStatus is generated from the Shelly API documentation.
type CoverStatus struct {
	// ID the numeric ID of the Cover component instance
	ID int `json:"id"`

	// Source source of the last command
	Source *string `json:"source,omitempty"`

	// Tag tag used to identify the origin of a state change
	Tag *string `json:"tag,omitempty"`

	// State one of open (Cover is fully open), closed (Cover is fully closed), opening
	// (Cover is actively opening), closing (Cover is actively closing), stopped (Cover
	// is not moving, and is neither fully open nor fully closed, or the open/close
	// state is unknown), calibrating (Cover is performing a calibration procedure)
	State *string `json:"state,omitempty"`

	// Apower active power in Watts
	Apower *float64 `json:"apower,omitempty"`

	// Voltage volts
	Voltage *float64 `json:"voltage,omitempty"`

	// Current amperes
	Current *float64 `json:"current,omitempty"`

	// Pf power factor
	Pf *float64 `json:"pf,omitempty"`

	// Freq network frequency, Hz
	Freq *float64 `json:"freq,omitempty"`

	Aenergy *CoverStatusAenergy `json:"aenergy,omitempty"`
	// CurrentPos only present if Cover is calibrated. Represents current position in
	// percent from 0 (fully closed) to 100 (fully open); null if the position is
	// unknown
	CurrentPos *float64 `json:"current_pos,omitempty"`

	// TargetPos only present if Cover is calibrated and is actively moving to a
	// requested position in either open or closed directions. Represents the target
	// position in percent from 0 (fully closed) to 100 (fully open); null if target
	// position has been reached or the movement was canceled
	TargetPos *float64 `json:"target_pos,omitempty"`

	// MoveTimeout seconds, only present if Cover is actively moving in either open or
	// closed directions. Cover will automatically stop after the timeout expires
	MoveTimeout *float64 `json:"move_timeout,omitempty"`

	// MoveStartedAt only present if Cover is actively moving in either open or closed
	// directions. Represents the time at which the movement has begun
	MoveStartedAt *float64 `json:"move_started_at,omitempty"`

	// PosControl false if Cover is not calibrated and only discrete open/close is
	// possible; true if Cover is calibrated and can be commanded to go to arbitrary
	// positions between fully open and fully closed
	PosControl *bool `json:"pos_control,omitempty"`

	// LastDirection direction of the last movement: open/close or null when unknown
	LastDirection *string `json:"last_direction,omitempty"`

	Temperature *CoverStatusTemperature `json:"temperature,omitempty"`
	// SlatPos only present if slat control is supported and enabled. Represents
	// current slat position in percent from 0 (fully closed) to 100 (fully open); null
	// if the position is unknown
	SlatPos *float64 `json:"slat_pos,omitempty"`

	// Errors only present if an error condition has occurred
	Errors json.RawMessage `json:"errors,omitempty"`
}

// CoverGetStatusRequest requests the status of the Cover component.
type CoverGetStatusRequest struct {
	// ID of the Cover component instance.
	ID int `json:"id"`
}

func (r *CoverGetStatusRequest) Method() string { return "Cover.GetStatus" }

func (r *CoverGetStatusRequest) NewTypedResponse() *CoverStatus { return &CoverStatus{} }

func (r *CoverGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *CoverGetStatusRequest) Do(client *resty.Client) (*CoverStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
