// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// DALIConfigScan is generated from the Shelly API documentation.
type DALIConfigScan struct {
	// CgCount number of found control gears during scan
	CgCount *float64 `json:"cg_count,omitempty"`

	// StartedAt unix timestamp, start time of the scan process (in UTC)
	StartedAt *float64 `json:"started_at,omitempty"`
}

// DALIConfig is generated from the Shelly API documentation.
type DALIConfig struct {
	// CgCount number of scanned control gears (null if scan has never been executed)
	CgCount *float64 `json:"cg_count,omitempty"`

	Scan *DALIConfigScan `json:"scan,omitempty"`
	// Errors shown only if at least one error is present. May contain
	// control_gear_missing, driver
	Errors json.RawMessage `json:"errors,omitempty"`
}

// DALIGetConfigRequest requests the configuration of the DALI component.
type DALIGetConfigRequest struct {
}

func (r *DALIGetConfigRequest) Method() string { return "DALI.GetConfig" }

func (r *DALIGetConfigRequest) NewTypedResponse() *DALIConfig { return &DALIConfig{} }

func (r *DALIGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *DALIGetConfigRequest) Do(client *resty.Client) (*DALIConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// DALISetConfigRequest updates the configuration of the DALI component.
type DALISetConfigRequest struct {
	// Config that the method takes.
	Config DALIConfig `json:"config"`
}

func (r *DALISetConfigRequest) Method() string { return "DALI.SetConfig" }

func (r *DALISetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *DALISetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *DALISetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// DALIStatusScan is generated from the Shelly API documentation.
type DALIStatusScan struct {
	// CgCount number of found control gears during scan
	CgCount *float64 `json:"cg_count,omitempty"`

	// StartedAt unix timestamp, start time of the scan process (in UTC)
	StartedAt *float64 `json:"started_at,omitempty"`
}

// DALIStatus is generated from the Shelly API documentation.
type DALIStatus struct {
	// CgCount number of scanned control gears (null if scan has never been executed)
	CgCount *float64 `json:"cg_count,omitempty"`

	Scan *DALIStatusScan `json:"scan,omitempty"`
	// Errors shown only if at least one error is present. May contain
	// control_gear_missing, driver
	Errors json.RawMessage `json:"errors,omitempty"`
}

// DALIGetStatusRequest requests the status of the DALI component.
type DALIGetStatusRequest struct {
}

func (r *DALIGetStatusRequest) Method() string { return "DALI.GetStatus" }

func (r *DALIGetStatusRequest) NewTypedResponse() *DALIStatus { return &DALIStatus{} }

func (r *DALIGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *DALIGetStatusRequest) Do(client *resty.Client) (*DALIStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
