// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// DevicePowerConfigBattery is generated from the Shelly API documentation.
type DevicePowerConfigBattery struct {
	// Percent battery charge level in % (null if valid value could not be obtained)
	Percent *float64 `json:"percent,omitempty"`
}

// DevicePowerConfig is generated from the Shelly API documentation.
type DevicePowerConfig struct {
	// ID id of the DevicePower component instance
	ID int `json:"id"`

	Battery *DevicePowerConfigBattery `json:"battery,omitempty"`
	// External information about the external power source (only available if external
	// power source is supported)
	External json.RawMessage `json:"external,omitempty"`

	// Errors whether external power source is connected
	Errors json.RawMessage `json:"errors,omitempty"`
}

// DevicePowerGetConfigRequest requests the configuration of the DevicePower component.
type DevicePowerGetConfigRequest struct {
	// ID of the DevicePower component instance.
	ID int `json:"id"`
}

func (r *DevicePowerGetConfigRequest) Method() string { return "DevicePower.GetConfig" }

func (r *DevicePowerGetConfigRequest) NewTypedResponse() *DevicePowerConfig {
	return &DevicePowerConfig{}
}

func (r *DevicePowerGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *DevicePowerGetConfigRequest) Do(client *resty.Client) (*DevicePowerConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// DevicePowerSetConfigRequest updates the configuration of the DevicePower component.
type DevicePowerSetConfigRequest struct {
	// ID of the DevicePower component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config DevicePowerConfig `json:"config"`
}

func (r *DevicePowerSetConfigRequest) Method() string { return "DevicePower.SetConfig" }

func (r *DevicePowerSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *DevicePowerSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *DevicePowerSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
