// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// EM1DataConfig is generated from the Shelly API documentation.
type EM1DataConfig struct {
	// ID id of the EM1Data component instance
	ID int `json:"id"`

	// TotalActEnergy total active energy, Wh
	TotalActEnergy *float64 `json:"total_act_energy,omitempty"`

	// TotalActRetEnergy total active returned energy, Wh
	TotalActRetEnergy *float64 `json:"total_act_ret_energy,omitempty"`

	// Errors error condition occurred. May contain database_error or ct_type_not_set,
	// (shown if the error is present).
	Errors []string `json:"errors,omitempty"`
}

// EM1DataGetConfigRequest requests the configuration of the EM1Data component.
type EM1DataGetConfigRequest struct {
	// ID of the EM1Data component instance.
	ID int `json:"id"`
}

func (r *EM1DataGetConfigRequest) Method() string { return "EM1Data.GetConfig" }

func (r *EM1DataGetConfigRequest) NewTypedResponse() *EM1DataConfig { return &EM1DataConfig{} }

func (r *EM1DataGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1DataGetConfigRequest) Do(client *resty.Client) (*EM1DataConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// EM1DataSetConfigRequest updates the configuration of the EM1Data component.
type EM1DataSetConfigRequest struct {
	// ID of the EM1Data component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config EM1DataConfig `json:"config"`
}

func (r *EM1DataSetConfigRequest) Method() string { return "EM1Data.SetConfig" }

func (r *EM1DataSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *EM1DataSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1DataSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// EM1DataStatus is generated from the Shelly API documentation.
type EM1DataStatus struct {
	// ID id of the EM1Data component instance
	ID int `json:"id"`

	// TotalActEnergy total active energy, Wh
	TotalActEnergy *float64 `json:"total_act_energy,omitempty"`

	// TotalActRetEnergy total active returned energy, Wh
	TotalActRetEnergy *float64 `json:"total_act_ret_energy,omitempty"`

	// Errors error condition occurred. May contain database_error or ct_type_not_set,
	// (shown if the error is present).
	Errors []string `json:"errors,omitempty"`
}

// EM1DataGetStatusRequest requests the status of the EM1Data component.
type EM1DataGetStatusRequest struct {
	// ID of the EM1Data component instance.
	ID int `json:"id"`
}

func (r *EM1DataGetStatusRequest) Method() string { return "EM1Data.GetStatus" }

func (r *EM1DataGetStatusRequest) NewTypedResponse() *EM1DataStatus { return &EM1DataStatus{} }

func (r *EM1DataGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EM1DataGetStatusRequest) Do(client *resty.Client) (*EM1DataStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
