// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// EMConfigReverse is generated from the Shelly API documentation.
type EMConfigReverse struct {
	// A when set to true reverse CT measurement direction of active power and energy
	// for phase A. shown if true
	A *bool `json:"a,omitempty"`

	// B when set to true reverse CT measurement direction of active power and energy
	// for phase B. shown if true
	B *bool `json:"b,omitempty"`

	// C when set to true reverse CT measurement direction of active power and energy
	// for phase C. shown if true
	C *bool `json:"c,omitempty"`
}

// EMConfigAlarmsA is generated from the Shelly API documentation.
type EMConfigAlarmsA struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EMConfigAlarmsB is generated from the Shelly API documentation.
type EMConfigAlarmsB struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EMConfigAlarmsC is generated from the Shelly API documentation.
type EMConfigAlarmsC struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// EMConfigAlarms is generated from the Shelly API documentation.
type EMConfigAlarms struct {
	A *EMConfigAlarmsA `json:"a,omitempty"`
	B *EMConfigAlarmsB `json:"b,omitempty"`
	C *EMConfigAlarmsC `json:"c,omitempty"`
}

// EMConfig is generated from the Shelly API documentation.
type EMConfig struct {
	// ID id of the EM component instance
	ID int `json:"id"`

	// Name name of the energy meter instance
	Name *string `json:"name,omitempty"`

	// BlinkModeSelector select the electrical quantity that drives the LED. Range of
	// values: active_energy, apparent_energy
	BlinkModeSelector *string `json:"blink_mode_selector,omitempty"`

	// PhaseSelector select witch phase controls the LED. Range of values: a, b, c, all
	PhaseSelector *string `json:"phase_selector,omitempty"`

	// MonitorPhaseSequence set this to show phase_sequence error in GetStatus if
	// three-phase power system is used and the wires are not connected correctly to
	// the device.
	MonitorPhaseSequence *bool `json:"monitor_phase_sequence,omitempty"`

	Reverse *EMConfigReverse `json:"reverse,omitempty"`
	Alarms  *EMConfigAlarms  `json:"alarms,omitempty"`
	// CtType select the type of Shelly current transformer attached to the device.
	CtType *string `json:"ct_type,omitempty"`
}

// EMGetConfigRequest requests the configuration of the EM component.
type EMGetConfigRequest struct {
	// ID of the EM component instance.
	ID int `json:"id"`
}

func (r *EMGetConfigRequest) Method() string { return "EM.GetConfig" }

func (r *EMGetConfigRequest) NewTypedResponse() *EMConfig { return &EMConfig{} }

func (r *EMGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMGetConfigRequest) Do(client *resty.Client) (*EMConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// EMSetConfigRequest updates the configuration of the EM component.
type EMSetConfigRequest struct {
	// ID of the EM component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config EMConfig `json:"config"`
}

func (r *EMSetConfigRequest) Method() string { return "EM.SetConfig" }

func (r *EMSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *EMSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// EMStatus is generated from the Shelly API documentation.
type EMStatus struct {
	// ID id of the EM component instance
	ID int `json:"id"`

	// ACurrent phase A current measurement value, [A]
	ACurrent *float64 `json:"a_current,omitempty"`

	// AVoltage phase A voltage measurement value, [V]
	AVoltage *float64 `json:"a_voltage,omitempty"`

	// AActPower phase A active power measurement value, [W]
	AActPower *float64 `json:"a_act_power,omitempty"`

	// AAprtPower phase A apparent power measurement value, [VA]
	AAprtPower *float64 `json:"a_aprt_power,omitempty"`

	// APf phase A power factor measurement value
	APf *float64 `json:"a_pf,omitempty"`

	// AFreq phase A network frequency measurement value
	AFreq *float64 `json:"a_freq,omitempty"`

	// AErrors phase A error conditions occurred. May contain
	// out_of_range:active_power, out_of_range:apparent_power, out_of_range:voltage,
	// out_of_range:current,(shown if at least one error is present)
	AErrors json.RawMessage `json:"a_errors,omitempty"`

	// AFlags phase A flags. May contain: undervoltage, overvoltage, undercurrent,
	// overcurrent, underpower, overpower (shown if at least one flag is set)
	AFlags json.RawMessage `json:"a_flags,omitempty"`

	// BCurrent phase B current measurement value, [A]
	BCurrent *float64 `json:"b_current,omitempty"`

	// BVoltage phase B voltage measurement value, [V]
	BVoltage *float64 `json:"b_voltage,omitempty"`

	// BActPower phase B active power measurement value, [W]
	BActPower *float64 `json:"b_act_power,omitempty"`

	// BAprtPower phase B apparent power measurement value, [VA]
	BAprtPower *float64 `json:"b_aprt_power,omitempty"`

	// BPf phase B power factor measurement value
	BPf *float64 `json:"b_pf,omitempty"`

	// BFreq phase B network frequency measurement value
	BFreq *float64 `json:"b_freq,omitempty"`

	// BErrors phase B error conditions occurred. May contain
	// out_of_range:active_power, out_of_range:apparent_power, out_of_range:voltage,
	// out_of_range:current,(shown if at least one error is present)
	BErrors json.RawMessage `json:"b_errors,omitempty"`

	// BFlags phase B flags. May contain: undervoltage, overvoltage, undercurrent,
	// overcurrent, underpower, overpower (shown if at least one flag is set)
	BFlags json.RawMessage `json:"b_flags,omitempty"`

	// CCurrent phase C current measurement value, [A]
	CCurrent *float64 `json:"c_current,omitempty"`

	// CVoltage phase C voltage measurement value, [V]
	CVoltage *float64 `json:"c_voltage,omitempty"`

	// CActPower phase C active power measurement value, [W]
	CActPower *float64 `json:"c_act_power,omitempty"`

	// CAprtPower phase C apparent power measurement value, [VA]
	CAprtPower *float64 `json:"c_aprt_power,omitempty"`

	// CPf phase C power factor measurement value
	CPf *float64 `json:"c_pf,omitempty"`

	// CFreq phase C network frequency measurement value
	CFreq *float64 `json:"c_freq,omitempty"`

	// CErrors phase C error conditions occurred. May contain
	// out_of_range:active_power, out_of_range:apparent_power, out_of_range:voltage,
	// out_of_range:current,(shown if at least one error is present)
	CErrors json.RawMessage `json:"c_errors,omitempty"`

	// CFlags phase C flags. May contain: undervoltage, overvoltage, undercurrent,
	// overcurrent, underpower, overpower (shown if at least one flag is set)
	CFlags json.RawMessage `json:"c_flags,omitempty"`

	// NCurrent neutral current measurement value, [A] (if supported)
	NCurrent *float64 `json:"n_current,omitempty"`

	// NErrors neutral error conditions occurred. May contain
	// out_of_range:current,(shown if error is present)
	NErrors json.RawMessage `json:"n_errors,omitempty"`

	// TotalCurrent sum of the current on all phases(excluding neutral readings if
	// available)
	TotalCurrent *float64 `json:"total_current,omitempty"`

	// TotalActPower sum of the active power on all phases
	TotalActPower *float64 `json:"total_act_power,omitempty"`

	// TotalAprtPower sum of the apparent power on all phases
	TotalAprtPower *float64 `json:"total_aprt_power,omitempty"`

	// UserCalibratedPhase indicates which phase was user calibrated
	UserCalibratedPhase json.RawMessage `json:"user_calibrated_phase,omitempty"`

	// Errors eM component error conditions. May contain power_meter_failure,
	// phase_sequence or ct_type_not_set. Present in status only if not empty.
	Errors json.RawMessage `json:"errors,omitempty"`
}

// EMGetStatusRequest requests the status of the EM component.
type EMGetStatusRequest struct {
	// ID of the EM component instance.
	ID int `json:"id"`
}

func (r *EMGetStatusRequest) Method() string { return "EM.GetStatus" }

func (r *EMGetStatusRequest) NewTypedResponse() *EMStatus { return &EMStatus{} }

func (r *EMGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *EMGetStatusRequest) Do(client *resty.Client) (*EMStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
