// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// IlluminanceConfig is generated from the Shelly API documentation.
type IlluminanceConfig struct {
	// ID id of the Illuminance component instance
	ID int `json:"id"`

	// Name name of the Illuminance instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`

	// DarkThr threshold in lux. Accepted range is device-specific
	DarkThr *float64 `json:"dark_thr,omitempty"`

	// BrightThr bright threshold in lux. Accepted range is device-specific
	BrightThr *float64 `json:"bright_thr,omitempty"`
}

// IlluminanceGetConfigRequest requests the configuration of the Illuminance component.
type IlluminanceGetConfigRequest struct {
	// ID of the Illuminance component instance.
	ID int `json:"id"`
}

func (r *IlluminanceGetConfigRequest) Method() string { return "Illuminance.GetConfig" }

func (r *IlluminanceGetConfigRequest) NewTypedResponse() *IlluminanceConfig {
	return &IlluminanceConfig{}
}

func (r *IlluminanceGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *IlluminanceGetConfigRequest) Do(client *resty.Client) (*IlluminanceConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// IlluminanceSetConfigRequest updates the configuration of the Illuminance component.
type IlluminanceSetConfigRequest struct {
	// ID of the Illuminance component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config IlluminanceConfig `json:"config"`
}

func (r *IlluminanceSetConfigRequest) Method() string { return "Illuminance.SetConfig" }

func (r *IlluminanceSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *IlluminanceSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *IlluminanceSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// IlluminanceStatus is generated from the Shelly API documentation.
type IlluminanceStatus struct {
	// ID id of the Illuminance component instance
	ID int `json:"id"`

	// Lux illuminance in lux (null if valid value could not be obtained) (if
	// applicable)
	Lux *float64 `json:"lux,omitempty"`

	// Illumination illuminance level interpreted according to dark_thr/bright_thr
	// (null if valid value could not be obtained): lux below dark_thr is interpreted
	// as dark, lux between dark_thr and bright_thr is interpreted as twilight, lux
	// above bright_thr is interpreted as bright
	Illumination *string `json:"illumination,omitempty"`

	// Errors shown only if at least one error is present. May contain out_of_range,
	// read when there is problem reading sensor
	Errors json.RawMessage `json:"errors,omitempty"`
}

// IlluminanceGetStatusRequest requests the status of the Illuminance component.
type IlluminanceGetStatusRequest struct {
	// ID of the Illuminance component instance.
	ID int `json:"id"`
}

func (r *IlluminanceGetStatusRequest) Method() string { return "Illuminance.GetStatus" }

func (r *IlluminanceGetStatusRequest) NewTypedResponse() *IlluminanceStatus {
	return &IlluminanceStatus{}
}

func (r *IlluminanceGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *IlluminanceGetStatusRequest) Do(client *resty.Client) (*IlluminanceStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
