// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// InputConfigXpercent is generated from the Shelly API documentation.
type InputConfigXpercent struct {
	// Expr jS expression containing x, where x is the raw value to be transformed
	// (status.percent), for example "x+1". Accepted range: null or [0..100] chars.
	// Both null and "" mean value transformation is disabled.
	Expr *string `json:"expr,omitempty"`

	// Unit unit of the transformed value (status.xpercent), for example, "m/s".
	// Accepted range: null or [0..20] chars. Both null and "" mean value
	// transformation is disabled.
	Unit *string `json:"unit,omitempty"`
}

// InputConfigXcounts is generated from the Shelly API documentation.
type InputConfigXcounts struct {
	// Expr jS expression containing x, where x is the raw value to be transformed
	// (status.counts.total and status.counts.by_minute), for example "x+1". Accepted
	// range: null or [0..100] chars. Both null and "" mean value transformation is
	// disabled.
	Expr *string `json:"expr,omitempty"`

	// Unit unit of the transformed values (status.counts.xtotal and
	// status.counts.xby_minute), for example, "m/s". Accepted range: null or [0..20]
	// chars. Both null and "" mean value transformation is disabled.
	Unit *string `json:"unit,omitempty"`
}

// InputConfigXfreq is generated from the Shelly API documentation.
type InputConfigXfreq struct {
	// Expr jS expression containing x, where x is the raw value to be transformed
	// (status.freq), for example "x+1". Accepted range: null or [0..100] chars. Both
	// null and "" mean value transformation is disabled.
	Expr *string `json:"expr,omitempty"`

	// Unit unit of the transformed value (status.xfreq), for example, "m/s". Accepted
	// range: null or [0..20] chars. Both null and "" mean value transformation is
	// disabled.
	Unit *string `json:"unit,omitempty"`
}

// InputConfig is generated from the Shelly API documentation.
type InputConfig struct {
	// ID id of the Input component instance
	ID int `json:"id"`

	// Name name of the input instance
	Name *string `json:"name,omitempty"`

	// Type type of associated input. Range of values switch, button, analog, count
	// (only if applicable).
	Type *string `json:"type,omitempty"`

	// Enable global enable flag. When disabled, the input instance doesn't emit any
	// events and reports status properties as null. Applies for all input types
	Enable *bool `json:"enable,omitempty"`

	// Invert (only for type switch, button, analog) True if the logical state of the
	// associated input is inverted, false otherwise. For the change to be applied, the
	// physical switch has to be toggled once after invert is set. For type analog
	// inverts percent range - 100% becomes 0% and 0% becomes 100%
	Invert *bool `json:"invert,omitempty"`

	// FactoryReset (only for type switch, button) True if input-triggered factory
	// reset option is enabled, false otherwise (shown if applicable)
	FactoryReset *bool `json:"factory_reset,omitempty"`

	// ReportThr (only for type analog) Analog input report threshold in percent. The
	// accepted range is device-specific, default [1.0..50.0]% unless specified
	// otherwise
	ReportThr *float64 `json:"report_thr,omitempty"`

	// RangeMap (only for type analog) Remaps 0%-100% range to values in array. The
	// first value in the array is the min setting, and the second value is the max
	// setting. Array elements are of type number. Float values are supported. The
	// accepted range for values is from 0% to 100%. Default values are [0, 100]. max
	// must be greater than min. Equality is supported.
	RangeMap json.RawMessage `json:"range_map,omitempty"`

	// Range (only for type analog) Analog input range, which is device-specific. See
	// the table below.
	Range *float64 `json:"range,omitempty"`

	Xpercent *InputConfigXpercent `json:"xpercent,omitempty"`
	// CountRepThr (only for type count) Counts report threshold in number of pulses.
	// Accepted range [1 - 2147483647]
	CountRepThr *float64 `json:"count_rep_thr,omitempty"`

	// FreqWindow (only for type count) Reference time in seconds for base of frequency
	// measurement. Accepted range [1 - 3600]
	FreqWindow *float64 `json:"freq_window,omitempty"`

	// FreqRepThr (only for type count) Frequency report threshold in percent. Accepted
	// range [0 - 10000]
	FreqRepThr *float64 `json:"freq_rep_thr,omitempty"`

	Xcounts *InputConfigXcounts `json:"xcounts,omitempty"`
	Xfreq   *InputConfigXfreq   `json:"xfreq,omitempty"`
}

// InputGetConfigRequest requests the configuration of the Input component.
type InputGetConfigRequest struct {
	// ID of the Input component instance.
	ID int `json:"id"`
}

func (r *InputGetConfigRequest) Method() string { return "Input.GetConfig" }

func (r *InputGetConfigRequest) NewTypedResponse() *InputConfig { return &InputConfig{} }

func (r *InputGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *InputGetConfigRequest) Do(client *resty.Client) (*InputConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// InputSetConfigRequest updates the configuration of the Input component.
type InputSetConfigRequest struct {
	// ID of the Input component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config InputConfig `json:"config"`
}

func (r *InputSetConfigRequest) Method() string { return "Input.SetConfig" }

func (r *InputSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *InputSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *InputSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// InputStatusCounts is generated from the Shelly API documentation.
type InputStatusCounts struct {
	// Total total pulses counted.
	Total *float64 `json:"total,omitempty"`

	// Xtotal total transformed with config.xcounts.expr. Present only when both
	// config.xcounts.expr and config.xcounts.unit are set to non-empty values. null if
	// config.xcounts.expr can not be evaluated.
	Xtotal *float64 `json:"xtotal,omitempty"`

	// ByMinute pulse counts for the last three complete minutes. The 0-th element
	// indicates the counts accumulated during the minute preceding minute_ts. Present
	// only if the device clock is synced.
	ByMinute []float64 `json:"by_minute,omitempty"`

	// XbyMinute by_minute values transformed with config.xcounts.expr. Present only
	// when both config.xcounts.expr and config.xcounts.unit is set to non-empty values
	// and the device clock is synced. null if config.xcounts.expr can not be
	// evaluated.
	XbyMinute *float64 `json:"xby_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// InputStatus is generated from the Shelly API documentation.
type InputStatus struct {
	// ID id of the Input component instance
	ID int `json:"id"`

	// State (only for type switch, button) State of the input (null if the input
	// instance is stateless, i.e. for type button)
	State *bool `json:"state,omitempty"`

	// Percent (only for type analog) Analog value in percent (null if the valid value
	// could not be obtained)
	Percent *float64 `json:"percent,omitempty"`

	// Xpercent (only for type analog) percent transformed with config.xpercent.expr.
	// Present only when both config.xpercent.expr and config.xpercent.unit are set to
	// non-empty values. null if config.xpercent.expr can not be evaluated.
	Xpercent *float64 `json:"xpercent,omitempty"`

	Counts *InputStatusCounts `json:"counts,omitempty"`
	// Freq (only for type count) Measured frequency in Hz. Determined at every elapsed
	// freq_window period.
	Freq *float64 `json:"freq,omitempty"`

	// Xfreq (only for type count) freq transformed with config.xfreq.expr. Present
	// only when both config.xfreq.expr and config.xfreq.unit are set to non-empty
	// values. null if config.xfreq.expr can not be evaluated.
	Xfreq *float64 `json:"xfreq,omitempty"`

	// Errors shown only if at least one error is present. May contain out_of_range,
	// read
	Errors []string `json:"errors,omitempty"`
}

// InputGetStatusRequest requests the status of the Input component.
type InputGetStatusRequest struct {
	// ID of the Input component instance.
	ID int `json:"id"`
}

func (r *InputGetStatusRequest) Method() string { return "Input.GetStatus" }

func (r *InputGetStatusRequest) NewTypedResponse() *InputStatus { return &InputStatus{} }

func (r *InputGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *InputGetStatusRequest) Do(client *resty.Client) (*InputStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
