// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// LightConfigNightMode is generated from the Shelly API documentation.
type LightConfigNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit when night mode is active. Default value 50.
	Brightness *float64 `json:"brightness,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optinal leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// LightConfigButtonPresetsButtonDoublepush is generated from the Shelly API documentation.
type LightConfigButtonPresetsButtonDoublepush struct {
	// Brightness brightness level (in percent) set on double click (if applicable),
	// default: 100
	Brightness *float64 `json:"brightness,omitempty"`
}

// LightConfigButtonPresets is generated from the Shelly API documentation.
type LightConfigButtonPresets struct {
	ButtonDoublepush *LightConfigButtonPresetsButtonDoublepush `json:"button_doublepush,omitempty"`
}

// LightConfigWarmup is generated from the Shelly API documentation.
type LightConfigWarmup struct {
	// Enable when enabled warmup is applied on toogle from off to on and brightness
	// below 10%.
	Enable *bool `json:"enable,omitempty"`

	// Brightness warmup brightness in percent. Range 10-100%.
	Brightness *float64 `json:"brightness,omitempty"`

	// TimeMs time period during which warmup_brightness will be on. Range 20-1000
	// milliseconds.
	TimeMs *float64 `json:"time_ms,omitempty"`
}

// LightConfig is generated from the Shelly API documentation.
type LightConfig struct {
	// ID id of the Light component instance
	ID int `json:"id"`

	// Name name of the light instance
	Name *string `json:"name,omitempty"`

	// InMode mode of the associated input. Range of values: follow, flip, activate,
	// detached, dim (if applicable), dual_dim (if applicable)
	InMode *string `json:"in_mode,omitempty"`

	// OpMode operational mode (if applicable), which is device-specific. See the table
	// below.
	OpMode *float64 `json:"op_mode,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last, toggle
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// TransitionDuration transition time (in seconds) - time to change from 0% to 100%
	// of brightness (if applicable)
	TransitionDuration *float64 `json:"transition_duration,omitempty"`

	// Gamma gamma correction (dimensionless) - adjusts light intensity for perceptual
	// linearity. Range 0.4 to 4.0, default 1.0 (if applicable)
	Gamma *float64 `json:"gamma,omitempty"`

	// MinBrightnessOnToggle brightness level (in percent) applied when there is a
	// toggle and current brightness is lower than min_brightness_on_toggle.
	MinBrightnessOnToggle *float64 `json:"min_brightness_on_toggle,omitempty"`

	NightMode *LightConfigNightMode `json:"night_mode,omitempty"`
	// ButtonFadeRate controls how quickly the output level changes while a button is
	// held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is
	// fastest, 1 is slowest
	ButtonFadeRate *float64 `json:"button_fade_rate,omitempty"`

	ButtonPresets *LightConfigButtonPresets `json:"button_presets,omitempty"`
	// RangeMap remaps output 0%-100% range to values in array (if applicable). First
	// value in array is min setting, second value is max setting. Array elements are
	// of type number. Accepted range for values is from 0% to 100%. Default values are
	// [0, 100]. max must be greater than min.
	RangeMap json.RawMessage `json:"range_map,omitempty"`

	// PowerLimit limit (in Watts) over which overpower condition occurs (shown if
	// applicable)
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit limit (in Volts) over which overvoltage condition occurs (shown if
	// applicable)
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`

	// UndervoltageLimit limit (in Volts) under which undervoltage condition occurs
	// (shown if applicable)
	UndervoltageLimit *float64 `json:"undervoltage_limit,omitempty"`

	// CurrentLimit limit (in Amperes) over which overcurrent condition occurs (shown
	// if applicable). For PlusRGBWPM shown if device is calibrated.
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	Warmup *LightConfigWarmup `json:"warmup,omitempty"`
}

// LightGetConfigRequest requests the configuration of the Light component.
type LightGetConfigRequest struct {
	// ID of the Light component instance.
	ID int `json:"id"`
}

func (r *LightGetConfigRequest) Method() string { return "Light.GetConfig" }

func (r *LightGetConfigRequest) NewTypedResponse() *LightConfig { return &LightConfig{} }

func (r *LightGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *LightGetConfigRequest) Do(client *resty.Client) (*LightConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// LightSetConfigRequest updates the configuration of the Light component.
type LightSetConfigRequest struct {
	// ID of the Light component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config LightConfig `json:"config"`
}

func (r *LightSetConfigRequest) Method() string { return "Light.SetConfig" }

func (r *LightSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *LightSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *LightSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// LightStatusTransitionTarget is generated from the Shelly API documentation.
type LightStatusTransitionTarget struct {
	// Output true if the output channel becomes on, false otherwise
	Output *bool `json:"output,omitempty"`

	// Brightness brightness level (in percent)
	Brightness *float64 `json:"brightness,omitempty"`
}

// LightStatusTransition is generated from the Shelly API documentation.
type LightStatusTransition struct {
	Target *LightStatusTransitionTarget `json:"target,omitempty"`
	// StartedAt unix timestamp, start time of the transition (in UTC)
	StartedAt *float64 `json:"started_at,omitempty"`

	// Duration duration of the transition in seconds
	Duration *float64 `json:"duration,omitempty"`
}

// LightStatusTemperature is generated from the Shelly API documentation.
type LightStatusTemperature struct {
	// TC temperature in Celsius (null if temperature is out of the measurement range)
	TC *float64 `json:"tC,omitempty"`

	// TF temperature in Fahrenheit (null if temperature is out of the measurement
	// range)
	TF *float64 `json:"tF,omitempty"`
}

// LightStatusAenergy is generated from the Shelly API documentation.
type LightStatusAenergy struct {
	// Total total energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute energy consumption in Milliwatt-hours for the last three complete
	// minutes. The 0-th element indicates the counts accumulated during the minute
	// preceding minute_ts. Present only if the device clock is synced.
	ByMinute []float64 `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// LightStatusCalibration is generated from the Shelly API documentation.
type LightStatusCalibration struct {
	// Progess calibration progress in percent
	Progess *float64 `json:"progess,omitempty"`
}

// LightStatus is generated from the Shelly API documentation.
type LightStatus struct {
	// ID id of the Light component instance
	ID int `json:"id"`

	// Source source of the last command, for example: init, WS_in, http, ...
	Source *string `json:"source,omitempty"`

	// Tag tag used to identify the origin of a state change
	Tag *string `json:"tag,omitempty"`

	// Output true if the output channel is currently on, false otherwise
	Output *bool `json:"output,omitempty"`

	// Brightness current brightness level (in percent)
	Brightness *float64 `json:"brightness,omitempty"`

	// TimerStartedAt unix timestamp, start time of the timer (in UTC) (shown if the
	// timer is triggered)
	TimerStartedAt *float64 `json:"timer_started_at,omitempty"`

	// TimerDuration duration of the timer in seconds (shown if the timer is triggered)
	TimerDuration *float64 `json:"timer_duration,omitempty"`

	Transition  *LightStatusTransition  `json:"transition,omitempty"`
	Temperature *LightStatusTemperature `json:"temperature,omitempty"`
	Aenergy     *LightStatusAenergy     `json:"aenergy,omitempty"`
	// Apower last measured instantaneous active power (in Watts) delivered to the
	// attached load (shown if applicable)
	Apower *float64 `json:"apower,omitempty"`

	// Voltage last measured voltage in Volts (shown if applicable)
	Voltage *float64 `json:"voltage,omitempty"`

	// Current last measured current in Amperes (shown if applicable)
	Current *float64 `json:"current,omitempty"`

	Calibration *LightStatusCalibration `json:"calibration,omitempty"`
	// Errors error conditions occurred, shown if at least one error is present.
	// Depending on component capabilities may contain: overtemp, overpower,
	// overvoltage, undervoltage, overcurrent, unsupported_load, cal_abort:interrupted,
	// cal_abort:power_read, cal_abort:no_load, cal_abort:no_synchro,
	// cal_abort:non_dimmable, cal_abort:overpower, cal_abort:unsupported_load
	Errors []string `json:"errors,omitempty"`

	// Flags communicates present conditions, shown if at least one flag is set.
	// Depending on component capabilites may contain: no_load, uncalibrated
	Flags []string `json:"flags,omitempty"`
}

// LightGetStatusRequest requests the status of the Light component.
type LightGetStatusRequest struct {
	// ID of the Light component instance.
	ID int `json:"id"`
}

func (r *LightGetStatusRequest) Method() string { return "Light.GetStatus" }

func (r *LightGetStatusRequest) NewTypedResponse() *LightStatus { return &LightStatus{} }

func (r *LightGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *LightGetStatusRequest) Do(client *resty.Client) (*LightStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
