// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// MatterConfig is generated from the Shelly API documentation.
type MatterConfig struct {
	// Enable set true to enable.
	Enable *bool `json:"enable,omitempty"`
}

// MatterGetConfigRequest requests the configuration of the Matter component.
type MatterGetConfigRequest struct {
}

func (r *MatterGetConfigRequest) Method() string { return "Matter.GetConfig" }

func (r *MatterGetConfigRequest) NewTypedResponse() *MatterConfig { return &MatterConfig{} }

func (r *MatterGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MatterGetConfigRequest) Do(client *resty.Client) (*MatterConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// MatterSetConfigRequest updates the configuration of the Matter component.
type MatterSetConfigRequest struct {
	// Config that the method takes.
	Config MatterConfig `json:"config"`
}

func (r *MatterSetConfigRequest) Method() string { return "Matter.SetConfig" }

func (r *MatterSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *MatterSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MatterSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// MatterStatus is generated from the Shelly API documentation.
type MatterStatus struct {
	// NumFabrics the number of Matter fabrics that the device has joined.
	NumFabrics *float64 `json:"num_fabrics,omitempty"`

	// Commissionable true if the device can be joined to an existing Matter fabric.
	// false means that the device is either already joined, or the commissioning
	// window is closed due to timeout. In the latter case, the device should be
	// restarted before adding to a fabric.
	Commissionable *bool `json:"commissionable,omitempty"`
}

// MatterGetStatusRequest requests the status of the Matter component.
type MatterGetStatusRequest struct {
}

func (r *MatterGetStatusRequest) Method() string { return "Matter.GetStatus" }

func (r *MatterGetStatusRequest) NewTypedResponse() *MatterStatus { return &MatterStatus{} }

func (r *MatterGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MatterGetStatusRequest) Do(client *resty.Client) (*MatterStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
