// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// MbRtuClientConfig is generated from the Shelly API documentation.
type MbRtuClientConfig struct {
}

// MbRtuClientGetConfigRequest requests the configuration of the MbRtuClient component.
type MbRtuClientGetConfigRequest struct {
}

func (r *MbRtuClientGetConfigRequest) Method() string { return "MbRtuClient.GetConfig" }

func (r *MbRtuClientGetConfigRequest) NewTypedResponse() *MbRtuClientConfig {
	return &MbRtuClientConfig{}
}

func (r *MbRtuClientGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MbRtuClientGetConfigRequest) Do(client *resty.Client) (*MbRtuClientConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// MbRtuClientSetConfigRequest updates the configuration of the MbRtuClient component.
type MbRtuClientSetConfigRequest struct {
	// Config that the method takes.
	Config MbRtuClientConfig `json:"config"`
}

func (r *MbRtuClientSetConfigRequest) Method() string { return "MbRtuClient.SetConfig" }

func (r *MbRtuClientSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *MbRtuClientSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MbRtuClientSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// MbRtuClientStatus is generated from the Shelly API documentation.
type MbRtuClientStatus struct {
}

// MbRtuClientGetStatusRequest requests the status of the MbRtuClient component.
type MbRtuClientGetStatusRequest struct {
}

func (r *MbRtuClientGetStatusRequest) Method() string { return "MbRtuClient.GetStatus" }

func (r *MbRtuClientGetStatusRequest) NewTypedResponse() *MbRtuClientStatus {
	return &MbRtuClientStatus{}
}

func (r *MbRtuClientGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MbRtuClientGetStatusRequest) Do(client *resty.Client) (*MbRtuClientStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
