// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// ModbusConfig is generated from the Shelly API documentation.
type ModbusConfig struct {
	// Enable set true to enable.
	Enable *bool `json:"enable,omitempty"`
}

// ModbusGetConfigRequest requests the configuration of the Modbus component.
type ModbusGetConfigRequest struct {
}

func (r *ModbusGetConfigRequest) Method() string { return "Modbus.GetConfig" }

func (r *ModbusGetConfigRequest) NewTypedResponse() *ModbusConfig { return &ModbusConfig{} }

func (r *ModbusGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ModbusGetConfigRequest) Do(client *resty.Client) (*ModbusConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// ModbusSetConfigRequest updates the configuration of the Modbus component.
type ModbusSetConfigRequest struct {
	// Config that the method takes.
	Config ModbusConfig `json:"config"`
}

func (r *ModbusSetConfigRequest) Method() string { return "Modbus.SetConfig" }

func (r *ModbusSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *ModbusSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ModbusSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// ModbusStatus is generated from the Shelly API documentation.
type ModbusStatus struct {
	// Enabled true if enabled, false if disabled.
	Enabled *bool `json:"enabled,omitempty"`
}

// ModbusGetStatusRequest requests the status of the Modbus component.
type ModbusGetStatusRequest struct {
}

func (r *ModbusGetStatusRequest) Method() string { return "Modbus.GetStatus" }

func (r *ModbusGetStatusRequest) NewTypedResponse() *ModbusStatus { return &ModbusStatus{} }

func (r *ModbusGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ModbusGetStatusRequest) Do(client *resty.Client) (*ModbusStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
