// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// MQTTConfig is generated from the Shelly API documentation.
type MQTTConfig struct {
	// Enable true if MQTT connection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Server host name of the MQTT server. Can be followed by port number - host:port
	Server *string `json:"server,omitempty"`

	// ClientID identifies each MQTT client that connects to an MQTT brokers
	ClientID *string `json:"client_id,omitempty"`

	// User username
	User *string `json:"user,omitempty"`

	// SSLCA type of the TCP sockets
	SSLCA *string `json:"ssl_ca,omitempty"`

	// TopicPrefix prefix of the topics on which device publish/subscribe. Limited to
	// 300 characters. Could not start with $ and #, +, %, ? are not allowed.
	TopicPrefix *string `json:"topic_prefix,omitempty"`

	// RPCNtf enables RPC notifications (NotifyStatus and NotifyEvent) to be published
	// on <device_id|topic_prefix>/events/rpc (<topic_prefix> when a custom prefix is
	// set, <device_id> otherwise). Default value: true.
	RPCNtf *bool `json:"rpc_ntf,omitempty"`

	// StatusNtf enables publishing the complete component status on
	// <device_id|topic_prefix>/status/<component>:<id> (<topic_prefix> when a custom
	// prefix is set, <device_id> otherwise). The complete status will be published if
	// a signifficant change occurred. Default value: false
	StatusNtf *bool `json:"status_ntf,omitempty"`

	// UseClientCert enable or diable usage of client certifactes to use MQTT with
	// encription, default: false
	UseClientCert *bool `json:"use_client_cert,omitempty"`

	// EnableControl enable the MQTT control feature. Defalut value: true
	EnableControl *bool `json:"enable_control,omitempty"`
}

// MQTTGetConfigRequest requests the configuration of the Mqtt component.
type MQTTGetConfigRequest struct {
}

func (r *MQTTGetConfigRequest) Method() string { return "MQTT.GetConfig" }

func (r *MQTTGetConfigRequest) NewTypedResponse() *MQTTConfig { return &MQTTConfig{} }

func (r *MQTTGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MQTTGetConfigRequest) Do(client *resty.Client) (*MQTTConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// MQTTSetConfigRequest updates the configuration of the Mqtt component.
type MQTTSetConfigRequest struct {
	// Config that the method takes.
	Config MQTTConfig `json:"config"`
}

func (r *MQTTSetConfigRequest) Method() string { return "MQTT.SetConfig" }

func (r *MQTTSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *MQTTSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MQTTSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// MQTTStatus is generated from the Shelly API documentation.
type MQTTStatus struct {
	// Connected true if the device is MQTT connected, false otherwise
	Connected *bool `json:"connected,omitempty"`
}

// MQTTGetStatusRequest requests the status of the Mqtt component.
type MQTTGetStatusRequest struct {
}

func (r *MQTTGetStatusRequest) Method() string { return "MQTT.GetStatus" }

func (r *MQTTGetStatusRequest) NewTypedResponse() *MQTTStatus { return &MQTTStatus{} }

func (r *MQTTGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *MQTTGetStatusRequest) Do(client *resty.Client) (*MQTTStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
