// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// PillConfig is generated from the Shelly API documentation.
type PillConfig struct {
	// Mode device mode. Range of values onewire, dht22, analog_in, ssr, digital_io
	Mode *string `json:"mode,omitempty"`

	// Pin0Mode pin 0 mode. Range of values none, reserved, digital_in, digital_out
	Pin0Mode *string `json:"pin0_mode,omitempty"`

	// Pin1Mode pin 1 mode. Range of values none, reserved, digital_in, digital_out
	Pin1Mode *string `json:"pin1_mode,omitempty"`

	// Pin2Mode pin 2 mode. Range of values none, reserved, digital_in, digital_out
	Pin2Mode *string `json:"pin2_mode,omitempty"`
}

// PillGetConfigRequest requests the configuration of the Pill component.
type PillGetConfigRequest struct {
}

func (r *PillGetConfigRequest) Method() string { return "Pill.GetConfig" }

func (r *PillGetConfigRequest) NewTypedResponse() *PillConfig { return &PillConfig{} }

func (r *PillGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PillGetConfigRequest) Do(client *resty.Client) (*PillConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// PillSetConfigRequest updates the configuration of the Pill component.
type PillSetConfigRequest struct {
	// Config that the method takes.
	Config PillConfig `json:"config"`
}

func (r *PillSetConfigRequest) Method() string { return "Pill.SetConfig" }

func (r *PillSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *PillSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PillSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// PillStatus is generated from the Shelly API documentation.
type PillStatus struct {
}

// PillGetStatusRequest requests the status of the Pill component.
type PillGetStatusRequest struct {
}

func (r *PillGetStatusRequest) Method() string { return "Pill.GetStatus" }

func (r *PillGetStatusRequest) NewTypedResponse() *PillStatus { return &PillStatus{} }

func (r *PillGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PillGetStatusRequest) Do(client *resty.Client) (*PillStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
