// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// PM1ConfigAlarms is generated from the Shelly API documentation.
type PM1ConfigAlarms struct {
	// Voltage ['under','over'] thresholds
	Voltage json.RawMessage `json:"voltage,omitempty"`

	// Current ['under','over'] thresholds
	Current json.RawMessage `json:"current,omitempty"`

	// Power ['under','over'] thresholds
	Power json.RawMessage `json:"power,omitempty"`
}

// PM1Config is generated from the Shelly API documentation.
type PM1Config struct {
	// ID id of the PM1 component instance
	ID int `json:"id"`

	// Name name of the PM1 instance
	Name *string `json:"name,omitempty"`

	// Reverse reverse measurement direction of active power and energy for the PM1
	// component. setting the reverse option requires restart
	Reverse *bool `json:"reverse,omitempty"`

	Alarms *PM1ConfigAlarms `json:"alarms,omitempty"`
}

// PM1GetConfigRequest requests the configuration of the PM1 component.
type PM1GetConfigRequest struct {
	// ID of the PM1 component instance.
	ID int `json:"id"`
}

func (r *PM1GetConfigRequest) Method() string { return "PM1.GetConfig" }

func (r *PM1GetConfigRequest) NewTypedResponse() *PM1Config { return &PM1Config{} }

func (r *PM1GetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PM1GetConfigRequest) Do(client *resty.Client) (*PM1Config, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// PM1SetConfigRequest updates the configuration of the PM1 component.
type PM1SetConfigRequest struct {
	// ID of the PM1 component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config PM1Config `json:"config"`
}

func (r *PM1SetConfigRequest) Method() string { return "PM1.SetConfig" }

func (r *PM1SetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *PM1SetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PM1SetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// PM1StatusAenergy is generated from the Shelly API documentation.
type PM1StatusAenergy struct {
	// Total total energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute energy consumption in Milliwatt-hours for the last three complete
	// minutes. The 0-th element indicates the counts accumulated during the minute
	// preceding minute_ts. Present only if the device clock is synced.
	ByMinute json.RawMessage `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// PM1StatusRetAenergy is generated from the Shelly API documentation.
type PM1StatusRetAenergy struct {
	// Total total returned energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute returned energy consumption by minute (in Milliwatt-hours) for the last
	// three minutes (the lower the index of the element in the array, the closer to
	// the current moment the minute)
	ByMinute json.RawMessage `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// PM1Status is generated from the Shelly API documentation.
type PM1Status struct {
	// ID id of the PM1 component instance
	ID int `json:"id"`

	// Voltage last measured voltage in Volts
	Voltage *float64 `json:"voltage,omitempty"`

	// Current last measured current in Amperes
	Current *float64 `json:"current,omitempty"`

	// Apower last measured instantaneous active power (in Watts) delivered to the
	// attached load
	Apower *float64 `json:"apower,omitempty"`

	// Aprtpower last measured instantaneous apparent power (in Volt-Amperes) delivered
	// to the attached load (shown if applicable)
	Aprtpower *float64 `json:"aprtpower,omitempty"`

	// Pf last measured power factor (shown if applicable)
	Pf *float64 `json:"pf,omitempty"`

	// Freq last measured network frequency (shown if applicable)
	Freq *float64 `json:"freq,omitempty"`

	Aenergy    *PM1StatusAenergy    `json:"aenergy,omitempty"`
	RetAenergy *PM1StatusRetAenergy `json:"ret_aenergy,omitempty"`
	// Errors error conditions occurred. May contain power_meter_failure,
	// out_of_range:voltage, out_of_range:current, out_of_range:aprtpower,
	// out_of_range:apower(shown if at least one error is present)
	Errors json.RawMessage `json:"errors,omitempty"`

	// Flags communicates present conditions, shown if at least one flag is set. May
	// contain: undervoltage, overvoltage, undercurrent, overcurrent, underpower,
	// overpower
	Flags json.RawMessage `json:"flags,omitempty"`
}

// PM1GetStatusRequest requests the status of the PM1 component.
type PM1GetStatusRequest struct {
	// ID of the PM1 component instance.
	ID int `json:"id"`
}

func (r *PM1GetStatusRequest) Method() string { return "PM1.GetStatus" }

func (r *PM1GetStatusRequest) NewTypedResponse() *PM1Status { return &PM1Status{} }

func (r *PM1GetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *PM1GetStatusRequest) Do(client *resty.Client) (*PM1Status, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
