// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// RGBConfigNightMode is generated from the Shelly API documentation.
type RGBConfigNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit (in percent) when night mode is active. null
	// overrides night_mode.brightness with current brightness when night mode starts.
	// Default value 50.
	Brightness *float64 `json:"brightness,omitempty"`

	// RGB color level when night mode is active. Red, Green, Blue [r,g,b] - each value
	// represents level between 0..255. null overrides night_mode.rgb array with
	// current rgb array when night mode starts. Default value 255 for each color
	RGB json.RawMessage `json:"rgb,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optinal leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// RGBConfigButtonPresetsButtonDoublepush is generated from the Shelly API documentation.
type RGBConfigButtonPresetsButtonDoublepush struct {
	// Brightness brightness level (in percent) set on double click (if applicable).
	// null overrides brightness with current brightness when preset is applied.
	// Default 100
	Brightness *float64 `json:"brightness,omitempty"`

	// RGB color level set on double click (if applicable). Red, Green, Blue [r,g,b] -
	// each value represents level between 0..255. null overrides rgb array with
	// current rgb array when preset is applied. Default value 255 for each color
	RGB json.RawMessage `json:"rgb,omitempty"`
}

// RGBConfigButtonPresets is generated from the Shelly API documentation.
type RGBConfigButtonPresets struct {
	ButtonDoublepush *RGBConfigButtonPresetsButtonDoublepush `json:"button_doublepush,omitempty"`
}

// RGBConfig is generated from the Shelly API documentation.
type RGBConfig struct {
	// ID id of the RGB component instance
	ID int `json:"id"`

	// Name name of the RGB instance
	Name *string `json:"name,omitempty"`

	// InMode mode of the associated input. Range of values: follow, flip, activate,
	// detached, dim
	InMode *string `json:"in_mode,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// TransitionDuration transition time (in seconds) - time to change from 0% to 100%
	// of brightness or RGB levels
	TransitionDuration *float64 `json:"transition_duration,omitempty"`

	// MinBrightnessOnToggle brightness level (in percent) applied when there is a
	// toggle and current brightness is lower than min_brightness_on_toggle.
	MinBrightnessOnToggle *float64 `json:"min_brightness_on_toggle,omitempty"`

	NightMode *RGBConfigNightMode `json:"night_mode,omitempty"`
	// ButtonFadeRate controls how quickly the output level changes while a button is
	// held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is
	// fastest, 1 is slowest
	ButtonFadeRate *float64 `json:"button_fade_rate,omitempty"`

	ButtonPresets *RGBConfigButtonPresets `json:"button_presets,omitempty"`
	// CurrentLimit limit (in Amperes) over which overcurrent condition occurs (shown
	// if applicable). For specific devices applies for color channels, not RGB
	// component
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	// PowerLimit limit (in Watts) over which overpower condition occurs (shown if
	// applicable)
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit limit (in Volts) over which overvoltage condition occurs (shown if
	// applicable)
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`
}

// RGBGetConfigRequest requests the configuration of the RGB component.
type RGBGetConfigRequest struct {
	// ID of the RGB component instance.
	ID int `json:"id"`
}

func (r *RGBGetConfigRequest) Method() string { return "RGB.GetConfig" }

func (r *RGBGetConfigRequest) NewTypedResponse() *RGBConfig { return &RGBConfig{} }

func (r *RGBGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBGetConfigRequest) Do(client *resty.Client) (*RGBConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// RGBSetConfigRequest updates the configuration of the RGB component.
type RGBSetConfigRequest struct {
	// ID of the RGB component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config RGBConfig `json:"config"`
}

func (r *RGBSetConfigRequest) Method() string { return "RGB.SetConfig" }

func (r *RGBSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *RGBSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// RGBStatusTransitionTarget is generated from the Shelly API documentation.
type RGBStatusTransitionTarget struct {
	// Output true if the output channel becomes on, false otherwise
	Output *bool `json:"output,omitempty"`

	// RGB red, Green, Blue [r,g,b] level 0..255
	RGB json.RawMessage `json:"rgb,omitempty"`

	// Brightness brightness level (in percent)
	Brightness *float64 `json:"brightness,omitempty"`
}

// RGBStatusTransition is generated from the Shelly API documentation.
type RGBStatusTransition struct {
	Target *RGBStatusTransitionTarget `json:"target,omitempty"`
	// StartedAt unix timestamp, start time of the transition (in UTC)
	StartedAt *float64 `json:"started_at,omitempty"`

	// Duration duration of the transition in seconds
	Duration *float64 `json:"duration,omitempty"`
}

// RGBStatusAenergy is generated from the Shelly API documentation.
type RGBStatusAenergy struct {
	// Total total energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute energy consumption in Milliwatt-hours for the last three complete
	// minutes. The 0-th element indicates the counts accumulated during the minute
	// preceding minute_ts. Present only if the device clock is synced.
	ByMinute json.RawMessage `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// RGBStatus is generated from the Shelly API documentation.
type RGBStatus struct {
	// ID id of the RGB component instance
	ID int `json:"id"`

	// Source source of the last command, for example: init, WS_in, http, ...
	Source *string `json:"source,omitempty"`

	// Tag tag used to identify the origin of a state change
	Tag *string `json:"tag,omitempty"`

	// Output true if the output channel is currently on, false otherwise
	Output *bool `json:"output,omitempty"`

	// RGB current Red, Green, Blue [r,g,b] level 0..255
	RGB json.RawMessage `json:"rgb,omitempty"`

	// Brightness current brightness level (in percent)
	Brightness *float64 `json:"brightness,omitempty"`

	// TimerStartedAt unix timestamp, start time of the timer (in UTC) (shown if the
	// timer is triggered)
	TimerStartedAt *float64 `json:"timer_started_at,omitempty"`

	// TimerDuration duration of the timer in seconds (shown if the timer is triggered)
	TimerDuration *float64 `json:"timer_duration,omitempty"`

	Transition *RGBStatusTransition `json:"transition,omitempty"`
	Aenergy    *RGBStatusAenergy    `json:"aenergy,omitempty"`
	// Apower last measured instantaneous active power (in Watts) delivered to the
	// attached load (shown if applicable)
	Apower *float64 `json:"apower,omitempty"`

	// Voltage last measured voltage in Volts (shown if applicable)
	Voltage *float64 `json:"voltage,omitempty"`

	// Current last measured current in Amperes (shown if applicable)
	Current *float64 `json:"current,omitempty"`

	// Errors error conditions occurred. May contain overtemp, (shown if at least one
	// error is present)
	Errors json.RawMessage `json:"errors,omitempty"`
}

// RGBGetStatusRequest requests the status of the RGB component.
type RGBGetStatusRequest struct {
	// ID of the RGB component instance.
	ID int `json:"id"`
}

func (r *RGBGetStatusRequest) Method() string { return "RGB.GetStatus" }

func (r *RGBGetStatusRequest) NewTypedResponse() *RGBStatus { return &RGBStatus{} }

func (r *RGBGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBGetStatusRequest) Do(client *resty.Client) (*RGBStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
