// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// RGBCCTConfigNightMode is generated from the Shelly API documentation.
type RGBCCTConfigNightMode struct {
	// Enable enable or disable night mode
	Enable *bool `json:"enable,omitempty"`

	// Brightness brightness level limit (in percent) when night mode is active. null
	// overrides night_mode.brightness with current brightness when night mode starts.
	// Default value 50.
	Brightness *float64 `json:"brightness,omitempty"`

	// RGB color level when night mode is active. Red, Green, Blue [r,g,b] - each value
	// represents level between 0..255. null overrides night_mode.rgb array with
	// current rgb array when night mode starts. Default value 255 for each color
	RGB json.RawMessage `json:"rgb,omitempty"`

	// Ct color temperature level limit (in Kelvin) when night mode is active. null
	// overrides night_mode.ct value with current ct value when night mode starts.
	// Default value: 50% of ct_range. For DuoBulbG3: 4600
	Ct *float64 `json:"ct,omitempty"`

	// Mode operating mode of the light output when night mode is active. Range of
	// values: rgb, cct or null. null overrides night_mode.mode value with current mode
	// when night mode starts. Default value: rgb
	Mode *string `json:"mode,omitempty"`

	// ActiveBetween containing 2 elements of type string, the first element indicates
	// the start of the period during which the night mode will be active, the second
	// indicates the end of that period. Both start and end are strings in the format
	// HH:MM, where HH and MM are hours and minutes with optinal leading zeros
	ActiveBetween json.RawMessage `json:"active_between,omitempty"`
}

// RGBCCTConfig is generated from the Shelly API documentation.
type RGBCCTConfig struct {
	// ID id of the RGBCCT component instance
	ID int `json:"id"`

	// Name name of the RGBCCT instance
	Name *string `json:"name,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// TransitionDuration transition time (in seconds) - time to change from 0% to 100%
	// of brightness, RGB levels or color temperature value
	TransitionDuration *float64 `json:"transition_duration,omitempty"`

	// MinBrightnessOnToggle brightness level (in percent) applied when there is a
	// toggle and current brightness is lower than min_brightness_on_toggle.
	MinBrightnessOnToggle *float64 `json:"min_brightness_on_toggle,omitempty"`

	NightMode *RGBCCTConfigNightMode `json:"night_mode,omitempty"`
}

// RGBCCTGetConfigRequest requests the configuration of the RGBCCT component.
type RGBCCTGetConfigRequest struct {
	// ID of the RGBCCT component instance.
	ID int `json:"id"`
}

func (r *RGBCCTGetConfigRequest) Method() string { return "RGBCCT.GetConfig" }

func (r *RGBCCTGetConfigRequest) NewTypedResponse() *RGBCCTConfig { return &RGBCCTConfig{} }

func (r *RGBCCTGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBCCTGetConfigRequest) Do(client *resty.Client) (*RGBCCTConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// RGBCCTSetConfigRequest updates the configuration of the RGBCCT component.
type RGBCCTSetConfigRequest struct {
	// ID of the RGBCCT component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config RGBCCTConfig `json:"config"`
}

func (r *RGBCCTSetConfigRequest) Method() string { return "RGBCCT.SetConfig" }

func (r *RGBCCTSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *RGBCCTSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBCCTSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// RGBCCTStatusTransitionTarget is generated from the Shelly API documentation.
type RGBCCTStatusTransitionTarget struct {
	// Output true if the output channel becomes on, false otherwise
	Output *bool `json:"output,omitempty"`

	// RGB red, Green, Blue [r,g,b] level 0..255
	RGB json.RawMessage `json:"rgb,omitempty"`

	// Ct color temperature level (in Kelvin)
	Ct *float64 `json:"ct,omitempty"`

	// Brightness brightness level (in percent)
	Brightness *float64 `json:"brightness,omitempty"`
}

// RGBCCTStatusTransition is generated from the Shelly API documentation.
type RGBCCTStatusTransition struct {
	Target *RGBCCTStatusTransitionTarget `json:"target,omitempty"`
	// StartedAt unix timestamp, start time of the transition (in UTC)
	StartedAt *float64 `json:"started_at,omitempty"`

	// Duration duration of the transition in seconds
	Duration *float64 `json:"duration,omitempty"`
}

// RGBCCTStatusAenergy is generated from the Shelly API documentation.
type RGBCCTStatusAenergy struct {
	// Total total energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute energy consumption in Milliwatt-hours for the last three complete
	// minutes. The 0-th element indicates the counts accumulated during the minute
	// preceding minute_ts. Present only if the device clock is synced.
	ByMinute json.RawMessage `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// RGBCCTStatus is generated from the Shelly API documentation.
type RGBCCTStatus struct {
	// ID id of the RGBCCT component instance
	ID int `json:"id"`

	// Source source of the last command, for example: init, WS_in, http, ...
	Source *string `json:"source,omitempty"`

	// Tag tag used to identify the origin of a state change
	Tag *string `json:"tag,omitempty"`

	// Mode current operating mode of the light output, rgb or cct
	Mode *string `json:"mode,omitempty"`

	// Output true if the output channel is currently on, false otherwise
	Output *bool `json:"output,omitempty"`

	// RGB current Red, Green, Blue [r,g,b] level 0..255
	RGB json.RawMessage `json:"rgb,omitempty"`

	// Ct current color temperature level (in Kelvin)
	Ct *float64 `json:"ct,omitempty"`

	// Brightness current brightness level (in percent)
	Brightness *float64 `json:"brightness,omitempty"`

	// TimerStartedAt unix timestamp, start time of the timer (in UTC) (shown if the
	// timer is triggered)
	TimerStartedAt *float64 `json:"timer_started_at,omitempty"`

	// TimerDuration duration of the timer in seconds (shown if the timer is triggered)
	TimerDuration *float64 `json:"timer_duration,omitempty"`

	Transition *RGBCCTStatusTransition `json:"transition,omitempty"`
	Aenergy    *RGBCCTStatusAenergy    `json:"aenergy,omitempty"`
	// Apower last measured instantaneous active power (in Watts) delivered to the
	// attached load (shown if applicable)
	Apower *float64 `json:"apower,omitempty"`
}

// RGBCCTGetStatusRequest requests the status of the RGBCCT component.
type RGBCCTGetStatusRequest struct {
	// ID of the RGBCCT component instance.
	ID int `json:"id"`
}

func (r *RGBCCTGetStatusRequest) Method() string { return "RGBCCT.GetStatus" }

func (r *RGBCCTGetStatusRequest) NewTypedResponse() *RGBCCTStatus { return &RGBCCTStatus{} }

func (r *RGBCCTGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *RGBCCTGetStatusRequest) Do(client *resty.Client) (*RGBCCTStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
