// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// ScriptConfig is generated from the Shelly API documentation.
type ScriptConfig struct {
	// ID id of the script
	ID int `json:"id"`

	// Name name of the script
	Name *string `json:"name,omitempty"`

	// Enable true if the script runs by default on boot, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// ScriptGetConfigRequest requests the configuration of the Script component.
type ScriptGetConfigRequest struct {
	// ID of the Script component instance.
	ID int `json:"id"`
}

func (r *ScriptGetConfigRequest) Method() string { return "Script.GetConfig" }

func (r *ScriptGetConfigRequest) NewTypedResponse() *ScriptConfig { return &ScriptConfig{} }

func (r *ScriptGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ScriptGetConfigRequest) Do(client *resty.Client) (*ScriptConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// ScriptSetConfigRequest updates the configuration of the Script component.
type ScriptSetConfigRequest struct {
	// ID of the Script component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config ScriptConfig `json:"config"`
}

func (r *ScriptSetConfigRequest) Method() string { return "Script.SetConfig" }

func (r *ScriptSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *ScriptSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ScriptSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// ScriptStatus is generated from the Shelly API documentation.
type ScriptStatus struct {
	// ID id of the script
	ID int `json:"id"`

	// Running true if the script is currently running, false otherwise
	Running *bool `json:"running,omitempty"`

	// MemUsed bytes of memory currently used by this script
	MemUsed *float64 `json:"mem_used,omitempty"`

	// MemPeak peak memory used by this script since it was started
	MemPeak *float64 `json:"mem_peak,omitempty"`

	// MemFree available memory for all scripts (memory pool for JS is shared among
	// script instances)
	MemFree *float64 `json:"mem_free,omitempty"`

	// CPU (since 1.7.0) Portion of time spent in the JS interpreter of this script
	// instance, calculated every 10 seconds
	CPU *float64 `json:"cpu,omitempty"`
}

// ScriptGetStatusRequest requests the status of the Script component.
type ScriptGetStatusRequest struct {
	// ID of the Script component instance.
	ID int `json:"id"`
}

func (r *ScriptGetStatusRequest) Method() string { return "Script.GetStatus" }

func (r *ScriptGetStatusRequest) NewTypedResponse() *ScriptStatus { return &ScriptStatus{} }

func (r *ScriptGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *ScriptGetStatusRequest) Do(client *resty.Client) (*ScriptStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
