// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// SerialConfigSerial is generated from the Shelly API documentation.
type SerialConfigSerial struct {
	// Baud baud rate
	Baud *int `json:"baud,omitempty"`

	// Format a 3-character string indicating the serial frame format to use, e.g. 8N1
	Format *string `json:"format,omitempty"`

	// Hd optional. Half-duplex mode. Only present on devices where the underlying
	// hardware supports it. true = enabled, false = disabled.
	Hd *bool `json:"hd,omitempty"`

	// DeAl optional. Driver Enable (DE) active level. Only present on devices where
	// the underlying hardware supports it. true = active high, false = active low.
	DeAl *bool `json:"de_al,omitempty"`
}

// SerialConfigMbServer is generated from the Shelly API documentation.
type SerialConfigMbServer struct {
	// Addr rTU Server Address, between 1 and 247
	Addr *int `json:"addr,omitempty"`
}

// SerialConfig is generated from the Shelly API documentation.
type SerialConfig struct {
	// ID id of the Serial component instance
	ID int `json:"id"`

	// Mode operating mode for the serial port. Supported modes are listed in the modes
	// attribute.
	Mode *string `json:"mode,omitempty"`

	Serial   *SerialConfigSerial   `json:"serial,omitempty"`
	MbServer *SerialConfigMbServer `json:"mb_server,omitempty"`
	// MbClient modbus RTU Client configuration. Reserved for future use.
	MbClient json.RawMessage `json:"mb_client,omitempty"`
}

// SerialGetConfigRequest requests the configuration of the Serial component.
type SerialGetConfigRequest struct {
	// ID of the Serial component instance.
	ID int `json:"id"`
}

func (r *SerialGetConfigRequest) Method() string { return "Serial.GetConfig" }

func (r *SerialGetConfigRequest) NewTypedResponse() *SerialConfig { return &SerialConfig{} }

func (r *SerialGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SerialGetConfigRequest) Do(client *resty.Client) (*SerialConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SerialSetConfigRequest updates the configuration of the Serial component.
type SerialSetConfigRequest struct {
	// ID of the Serial component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config SerialConfig `json:"config"`
}

func (r *SerialSetConfigRequest) Method() string { return "Serial.SetConfig" }

func (r *SerialSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *SerialSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SerialSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
