// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// SmokeConfig is generated from the Shelly API documentation.
type SmokeConfig struct {
	// ID id of the Smoke component instance
	ID int `json:"id"`

	// Name name of the Smoke instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`
}

// SmokeGetConfigRequest requests the configuration of the Smoke component.
type SmokeGetConfigRequest struct {
	// ID of the Smoke component instance.
	ID int `json:"id"`
}

func (r *SmokeGetConfigRequest) Method() string { return "Smoke.GetConfig" }

func (r *SmokeGetConfigRequest) NewTypedResponse() *SmokeConfig { return &SmokeConfig{} }

func (r *SmokeGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SmokeGetConfigRequest) Do(client *resty.Client) (*SmokeConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SmokeSetConfigRequest updates the configuration of the Smoke component.
type SmokeSetConfigRequest struct {
	// ID of the Smoke component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config SmokeConfig `json:"config"`
}

func (r *SmokeSetConfigRequest) Method() string { return "Smoke.SetConfig" }

func (r *SmokeSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *SmokeSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SmokeSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SmokeStatus is generated from the Shelly API documentation.
type SmokeStatus struct {
	// ID id of the Smoke component instance
	ID int `json:"id"`

	// Alarm alarm state
	Alarm *bool `json:"alarm,omitempty"`

	// Mute mute state
	Mute *bool `json:"mute,omitempty"`
}

// SmokeGetStatusRequest requests the status of the Smoke component.
type SmokeGetStatusRequest struct {
	// ID of the Smoke component instance.
	ID int `json:"id"`
}

func (r *SmokeGetStatusRequest) Method() string { return "Smoke.GetStatus" }

func (r *SmokeGetStatusRequest) NewTypedResponse() *SmokeStatus { return &SmokeStatus{} }

func (r *SmokeGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SmokeGetStatusRequest) Do(client *resty.Client) (*SmokeStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
