// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// SwitchConfigCounts is generated from the Shelly API documentation.
type SwitchConfigCounts struct {
	// Enable enable or disable the switch counters (shown if applicable)
	Enable *bool `json:"enable,omitempty"`

	// PowerThr active power threshold (in Watts) over which on_above_thr counter is
	// incremented. Default value 100. (shown if applicable)
	PowerThr *float64 `json:"power_thr,omitempty"`
}

// SwitchConfig is generated from the Shelly API documentation.
type SwitchConfig struct {
	// ID id of the Switch component instance
	ID int `json:"id"`

	// Name name of the switch instance
	Name *string `json:"name,omitempty"`

	// InMode mode of the associated input. Range of values: momentary, follow, flip,
	// detached, cycle (if applicable), activate (if applicable)
	InMode *string `json:"in_mode,omitempty"`

	// InLocked if True, all changes to physical inputs are ignored, regardless of
	// mode.
	InLocked *bool `json:"in_locked,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last, match_input
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// AutorecoverVoltageErrors true if switch output state should be restored after
	// over/undervoltage error is cleared, false otherwise (shown if applicable)
	AutorecoverVoltageErrors *bool `json:"autorecover_voltage_errors,omitempty"`

	// InputID id of the Input component which controls the Switch. Applicable only to
	// Pro1, Pro1PM and 1LG3 devices. Valid values: 0, 1
	InputID *float64 `json:"input_id,omitempty"`

	// PowerLimit limit (in Watts) over which overpower condition occurs (shown if
	// applicable)
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit limit (in Volts) over which overvoltage condition occurs (shown if
	// applicable)
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`

	// UndervoltageLimit limit (in Volts) under which undervoltage condition occurs
	// (shown if applicable)
	UndervoltageLimit *float64 `json:"undervoltage_limit,omitempty"`

	// CurrentLimit number, limit (in Amperes) over which overcurrent condition occurs
	// (shown if applicable)
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	// Reverse reverse measurement direction of active power and energy. setting the
	// reverse option requires restart (shown if applicable)
	Reverse *bool `json:"reverse,omitempty"`

	Counts *SwitchConfigCounts `json:"counts,omitempty"`
}

// SwitchGetConfigRequest requests the configuration of the Switch component.
type SwitchGetConfigRequest struct {
	// ID of the Switch component instance.
	ID int `json:"id"`
}

func (r *SwitchGetConfigRequest) Method() string { return "Switch.GetConfig" }

func (r *SwitchGetConfigRequest) NewTypedResponse() *SwitchConfig { return &SwitchConfig{} }

func (r *SwitchGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SwitchGetConfigRequest) Do(client *resty.Client) (*SwitchConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SwitchSetConfigRequest updates the configuration of the Switch component.
type SwitchSetConfigRequest struct {
	// ID of the Switch component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config SwitchConfig `json:"config"`
}

func (r *SwitchSetConfigRequest) Method() string { return "Switch.SetConfig" }

func (r *SwitchSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *SwitchSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SwitchSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
