// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// SwitchConfigCounts is generated from the Shelly API documentation.
type SwitchConfigCounts struct {
	// Enable enable or disable the switch counters (shown if applicable)
	Enable *bool `json:"enable,omitempty"`

	// PowerThr active power threshold (in Watts) over which on_above_thr counter is
	// incremented. Default value 100. (shown if applicable)
	PowerThr *float64 `json:"power_thr,omitempty"`
}

// SwitchConfig is generated from the Shelly API documentation.
type SwitchConfig struct {
	// ID id of the Switch component instance
	ID int `json:"id"`

	// Name name of the switch instance
	Name *string `json:"name,omitempty"`

	// InMode mode of the associated input. Range of values: momentary, follow, flip,
	// detached, cycle (if applicable), activate (if applicable)
	InMode *string `json:"in_mode,omitempty"`

	// InLocked if True, all changes to physical inputs are ignored, regardless of
	// mode.
	InLocked *bool `json:"in_locked,omitempty"`

	// InitialState output state to set on power_on. Range of values: off, on,
	// restore_last, match_input
	InitialState *string `json:"initial_state,omitempty"`

	// AutoOn true if the "Automatic ON" function is enabled, false otherwise
	AutoOn *bool `json:"auto_on,omitempty"`

	// AutoOnDelay seconds to pass until the component is switched back on
	AutoOnDelay *float64 `json:"auto_on_delay,omitempty"`

	// AutoOff true if the "Automatic OFF" function is enabled, false otherwise
	AutoOff *bool `json:"auto_off,omitempty"`

	// AutoOffDelay seconds to pass until the component is switched back off
	AutoOffDelay *float64 `json:"auto_off_delay,omitempty"`

	// AutorecoverVoltageErrors true if switch output state should be restored after
	// over/undervoltage error is cleared, false otherwise (shown if applicable)
	AutorecoverVoltageErrors *bool `json:"autorecover_voltage_errors,omitempty"`

	// InputID id of the Input component which controls the Switch. Applicable only to
	// Pro1, Pro1PM and 1LG3 devices. Valid values: 0, 1
	InputID *float64 `json:"input_id,omitempty"`

	// PowerLimit limit (in Watts) over which overpower condition occurs (shown if
	// applicable)
	PowerLimit *float64 `json:"power_limit,omitempty"`

	// VoltageLimit limit (in Volts) over which overvoltage condition occurs (shown if
	// applicable)
	VoltageLimit *float64 `json:"voltage_limit,omitempty"`

	// UndervoltageLimit limit (in Volts) under which undervoltage condition occurs
	// (shown if applicable)
	UndervoltageLimit *float64 `json:"undervoltage_limit,omitempty"`

	// CurrentLimit number, limit (in Amperes) over which overcurrent condition occurs
	// (shown if applicable)
	CurrentLimit *float64 `json:"current_limit,omitempty"`

	// Reverse reverse measurement direction of active power and energy. setting the
	// reverse option requires restart (shown if applicable)
	Reverse *bool `json:"reverse,omitempty"`

	Counts *SwitchConfigCounts `json:"counts,omitempty"`
}

// SwitchGetConfigRequest requests the configuration of the Switch component.
type SwitchGetConfigRequest struct {
	// ID of the Switch component instance.
	ID int `json:"id"`
}

func (r *SwitchGetConfigRequest) Method() string { return "Switch.GetConfig" }

func (r *SwitchGetConfigRequest) NewTypedResponse() *SwitchConfig { return &SwitchConfig{} }

func (r *SwitchGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SwitchGetConfigRequest) Do(client *resty.Client) (*SwitchConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SwitchSetConfigRequest updates the configuration of the Switch component.
type SwitchSetConfigRequest struct {
	// ID of the Switch component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config SwitchConfig `json:"config"`
}

func (r *SwitchSetConfigRequest) Method() string { return "Switch.SetConfig" }

func (r *SwitchSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *SwitchSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SwitchSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SwitchInMode* are the documented values of Switch.in_mode. They are advisory: the
// field accepts any string, since the documented set may be incomplete.
const (
	SwitchInModeMomentary = "momentary"
	SwitchInModeFollow    = "follow"
	SwitchInModeFlip      = "flip"
	SwitchInModeDetached  = "detached"
	SwitchInModeCycle     = "cycle"
)

// SwitchInitialState* are the documented values of Switch.initial_state. They are advisory: the
// field accepts any string, since the documented set may be incomplete.
const (
	SwitchInitialStateOff         = "off"
	SwitchInitialStateOn          = "on"
	SwitchInitialStateRestoreLast = "restore_last"
	SwitchInitialStateMatchInput  = "match_input"
)

// SwitchStatusAenergy is generated from the Shelly API documentation.
type SwitchStatusAenergy struct {
	// Total total energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute total energy flow in Milliwatt-hours for the last three complete
	// minutes. The 0-th element indicates the counts accumulated during the minute
	// preceding minute_ts. Present only if the device clock is synced.
	ByMinute []float64 `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// SwitchStatusRetAenergy is generated from the Shelly API documentation.
type SwitchStatusRetAenergy struct {
	// Total total returned energy consumed in Watt-hours
	Total *float64 `json:"total,omitempty"`

	// ByMinute returned energy in Milliwatt-hours for the last three complete minutes.
	// The 0-th element indicates the counts accumulated during the minute preceding
	// minute_ts. Present only if the device clock is synced.
	ByMinute []float64 `json:"by_minute,omitempty"`

	// MinuteTs unix timestamp marking the start of the current minute (in UTC).
	MinuteTs *float64 `json:"minute_ts,omitempty"`
}

// SwitchStatusCounts is generated from the Shelly API documentation.
type SwitchStatusCounts struct {
	// OnTime total accumulated ON time in minutes
	OnTime *float64 `json:"on_time,omitempty"`

	// OnTimeRstTs unix timestamp marking the last reset of the on_time counter (in
	// UTC).
	OnTimeRstTs *float64 `json:"on_time_rst_ts,omitempty"`

	// SwitchOn total accumulated OFF to ON cycles
	SwitchOn *float64 `json:"switch_on,omitempty"`

	// SwitchOnRstTs unix timestamp marking the last reset of the switch_on counter (in
	// UTC).
	SwitchOnRstTs *float64 `json:"switch_on_rst_ts,omitempty"`

	// OnAboveThr total accumulated ON time above power threshold in minutes
	OnAboveThr *float64 `json:"on_above_thr,omitempty"`

	// OnAboveThrRstTs unix timestamp marking the last reset of the on_above_thr
	// counter (in UTC).
	OnAboveThrRstTs *float64 `json:"on_above_thr_rst_ts,omitempty"`
}

// SwitchStatusTemperature is generated from the Shelly API documentation.
type SwitchStatusTemperature struct {
	// TC temperature in Celsius (null if the temperature is out of the measurement
	// range)
	TC *float64 `json:"tC,omitempty"`

	// TF temperature in Fahrenheit (null if the temperature is out of the measurement
	// range)
	TF *float64 `json:"tF,omitempty"`
}

// SwitchStatus is generated from the Shelly API documentation.
type SwitchStatus struct {
	// ID id of the Switch component instance
	ID int `json:"id"`

	// Source source of the last command, for example: init, WS_in, http, ...
	Source *string `json:"source,omitempty"`

	// Tag tag used to identify the origin of a state change
	Tag *string `json:"tag,omitempty"`

	// Output true if the output channel is currently on, false otherwise
	Output *bool `json:"output,omitempty"`

	// TimerStartedAt unix timestamp, start time of the timer (in UTC) (shown if the
	// timer is triggered)
	TimerStartedAt *float64 `json:"timer_started_at,omitempty"`

	// TimerDuration duration of the timer in seconds (shown if the timer is triggered)
	TimerDuration *float64 `json:"timer_duration,omitempty"`

	// Apower last measured instantaneous active power (in Watts) delivered to the
	// attached load (shown if applicable)
	Apower *float64 `json:"apower,omitempty"`

	// Voltage last measured voltage in Volts (shown if applicable)
	Voltage *float64 `json:"voltage,omitempty"`

	// Current last measured current in Amperes (shown if applicable)
	Current *float64 `json:"current,omitempty"`

	// Pf last measured power factor (shown if applicable)
	Pf *float64 `json:"pf,omitempty"`

	// Freq last measured network frequency in Hz (shown if applicable)
	Freq *float64 `json:"freq,omitempty"`

	Aenergy     *SwitchStatusAenergy     `json:"aenergy,omitempty"`
	RetAenergy  *SwitchStatusRetAenergy  `json:"ret_aenergy,omitempty"`
	Counts      *SwitchStatusCounts      `json:"counts,omitempty"`
	Temperature *SwitchStatusTemperature `json:"temperature,omitempty"`
	// Errors error conditions occurred. May contain overtemp, overpower, overvoltage,
	// undervoltage, (shown if at least one error is present)
	Errors []string `json:"errors,omitempty"`
}

// SwitchGetStatusRequest requests the status of the Switch component.
type SwitchGetStatusRequest struct {
	// ID of the Switch component instance.
	ID int `json:"id"`
}

func (r *SwitchGetStatusRequest) Method() string { return "Switch.GetStatus" }

func (r *SwitchGetStatusRequest) NewTypedResponse() *SwitchStatus { return &SwitchStatus{} }

func (r *SwitchGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SwitchGetStatusRequest) Do(client *resty.Client) (*SwitchStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
