// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// SysConfigDevice is generated from the Shelly API documentation.
type SysConfigDevice struct {
	// Name name of the device
	Name *string `json:"name,omitempty"`

	// EcoMode experimental Decreases power consumption when set to true, at the cost
	// of reduced execution speed and increased network latency
	EcoMode *bool `json:"eco_mode,omitempty"`

	// MAC read-only base MAC address of the device
	MAC *string `json:"mac,omitempty"`

	// FWID read-only build identifier of the current firmware image
	FWID *string `json:"fw_id,omitempty"`

	// Profile name of the device profile (only applicable for multi-profile devices)
	Profile *string `json:"profile,omitempty"`

	// Discoverable if true, device is shown in 'Discovered devices'. If false, the
	// device is hidden.
	Discoverable *bool `json:"discoverable,omitempty"`

	// AddonType enable/disable addon board (if supported). Range of values:
	// sensor(SensorAddon), sensor(ProSensorAddon), prooutput, LoRa; null to disable.
	AddonType *string `json:"addon_type,omitempty"`

	// SysBtnToggle enable/disable outputs toggle when the system (reset) button is
	// pressed (shown if applicable).
	SysBtnToggle *bool `json:"sys_btn_toggle,omitempty"`

	// TLSCheckCertValidityTime (Since 2.0.0) When true, TLS certificate date/time
	// validation is enforced for outbound connections. Can only be set to false when
	// enhanced_security is false. This is a temporary option for users experiencing
	// certificate validation issues due to time synchronization problems; subject to
	// deprecation in future releases.
	TLSCheckCertValidityTime *bool `json:"tls_check_cert_validity_time,omitempty"`

	// EnhancedSecurity (Since 2.0.0) Read-only on devices shipped with firmware 2.0.0+
	// from factory (always true). On devices with factory firmware prior to 2.0.0, can
	// be set to true but can only be reset to false via factory reset. When enabled,
	// enforces additional security measures (see Enhanced Security section below).
	EnhancedSecurity *bool `json:"enhanced_security,omitempty"`
}

// SysConfigLocation is generated from the Shelly API documentation.
type SysConfigLocation struct {
	// Tz timezone (null if unavailable)
	Tz *string `json:"tz,omitempty"`

	// Lat latitude in degrees (null if unavailable)
	Lat *float64 `json:"lat,omitempty"`

	// Lon longitude in degrees (null if unavailable)
	Lon *float64 `json:"lon,omitempty"`
}

// SysConfigDebugMQTT is generated from the Shelly API documentation.
type SysConfigDebugMQTT struct {
	// Enable true if enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// SysConfigDebugWebsocket is generated from the Shelly API documentation.
type SysConfigDebugWebsocket struct {
	// Enable true if enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// SysConfigDebugUdp is generated from the Shelly API documentation.
type SysConfigDebugUdp struct {
	// Addr address that the device log is streamed to (null to disable logs)
	Addr *string `json:"addr,omitempty"`
}

// SysConfigDebugFileLog is generated from the Shelly API documentation.
type SysConfigDebugFileLog struct {
	// Enable true if enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// SysConfigDebug is generated from the Shelly API documentation.
type SysConfigDebug struct {
	MQTT      *SysConfigDebugMQTT      `json:"mqtt,omitempty"`
	Websocket *SysConfigDebugWebsocket `json:"websocket,omitempty"`
	Udp       *SysConfigDebugUdp       `json:"udp,omitempty"`
	FileLog   *SysConfigDebugFileLog   `json:"file_log,omitempty"`
}

// SysConfigRPCUdp is generated from the Shelly API documentation.
type SysConfigRPCUdp struct {
	// DstAddr is generated from the Shelly API documentation.
	DstAddr *string `json:"dst_addr,omitempty"`

	// ListenPort port number for inbound UDP RPC channel, null disables. Restart is
	// required for changes to apply
	ListenPort *float64 `json:"listen_port,omitempty"`
}

// SysConfigSntp is generated from the Shelly API documentation.
type SysConfigSntp struct {
	// Server name of the sntp server
	Server *string `json:"server,omitempty"`
}

// SysConfig is generated from the Shelly API documentation.
type SysConfig struct {
	Device   *SysConfigDevice   `json:"device,omitempty"`
	Location *SysConfigLocation `json:"location,omitempty"`
	Debug    *SysConfigDebug    `json:"debug,omitempty"`
	// UIData user interface data
	UIData json.RawMessage `json:"ui_data,omitempty"`

	RPCUdp *SysConfigRPCUdp `json:"rpc_udp,omitempty"`
	Sntp   *SysConfigSntp   `json:"sntp,omitempty"`
	// CfgRev configuration revision. This number will be incremented for every
	// configuration change of a device component. If the new config value is the same
	// as the old one there will be no change of this property. Can not be modified
	// explicitly by a call to Sys.SetConfig
	CfgRev *float64 `json:"cfg_rev,omitempty"`
}

// SysGetConfigRequest requests the configuration of the Sys component.
type SysGetConfigRequest struct {
}

func (r *SysGetConfigRequest) Method() string { return "Sys.GetConfig" }

func (r *SysGetConfigRequest) NewTypedResponse() *SysConfig { return &SysConfig{} }

func (r *SysGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SysGetConfigRequest) Do(client *resty.Client) (*SysConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SysSetConfigRequest updates the configuration of the Sys component.
type SysSetConfigRequest struct {
	// Config that the method takes.
	Config SysConfig `json:"config"`
}

func (r *SysSetConfigRequest) Method() string { return "Sys.SetConfig" }

func (r *SysSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *SysSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SysSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// SysStatusAvailableUpdatesBeta is generated from the Shelly API documentation.
type SysStatusAvailableUpdatesBeta struct {
	// Version version of the new firmware
	Version *string `json:"version,omitempty"`
}

// SysStatusAvailableUpdatesStable is generated from the Shelly API documentation.
type SysStatusAvailableUpdatesStable struct {
	// Version version of the new firmware
	Version *string `json:"version,omitempty"`
}

// SysStatusAvailableUpdates is generated from the Shelly API documentation.
type SysStatusAvailableUpdates struct {
	Beta   *SysStatusAvailableUpdatesBeta   `json:"beta,omitempty"`
	Stable *SysStatusAvailableUpdatesStable `json:"stable,omitempty"`
}

// SysStatusWakeupReason is generated from the Shelly API documentation.
type SysStatusWakeupReason struct {
	// Boot boot type, one of: poweron, software_restart, deepsleep_wake, internal,
	// unknown.
	Boot *string `json:"boot,omitempty"`

	// Cause boot cause, one of: button, usb, periodic, status_update, alarm,
	// alarm_test, undefined.
	Cause *string `json:"cause,omitempty"`
}

// SysStatus is generated from the Shelly API documentation.
type SysStatus struct {
	// MAC mac address of the device
	MAC *string `json:"mac,omitempty"`

	// RestartRequired true if restart is required, false otherwise
	RestartRequired *bool `json:"restart_required,omitempty"`

	// Time current time in the format HH:MM (24-hour time format in the current
	// timezone with leading zero). null when time is not synced from NTP server.
	Time *string `json:"time,omitempty"`

	// Unixtime unix timestamp (in UTC), null when time is not synced from NTP server.
	Unixtime *float64 `json:"unixtime,omitempty"`

	// LastSyncTs last time the system synced time from NTP server (in UTC), null when
	// time is not synced from NTP server.
	LastSyncTs *float64 `json:"last_sync_ts,omitempty"`

	// Uptime time in seconds since last reboot
	Uptime *float64 `json:"uptime,omitempty"`

	// RamSize total size of the RAM in the system in Bytes
	RamSize *float64 `json:"ram_size,omitempty"`

	// RamFree size of the free RAM in the system in Bytes
	RamFree *float64 `json:"ram_free,omitempty"`

	// FsSize total size of the file system in Bytes
	FsSize *float64 `json:"fs_size,omitempty"`

	// FsFree size of the free file system in Bytes
	FsFree *float64 `json:"fs_free,omitempty"`

	// CfgRev configuration revision number
	CfgRev *float64 `json:"cfg_rev,omitempty"`

	// KvsRev kVS (Key-Value Store) revision number
	KvsRev *float64 `json:"kvs_rev,omitempty"`

	// ScheduleRev schedules revision number, present if schedules are enabled
	ScheduleRev *float64 `json:"schedule_rev,omitempty"`

	// WebhookRev webhooks revision number, present if webhooks are enabled
	WebhookRev *float64 `json:"webhook_rev,omitempty"`

	// KnxRev kNX configuration revision number, present on devices supporting KNX with
	// KNX enabled
	KnxRev *float64 `json:"knx_rev,omitempty"`

	// BtrelayRev bLE cloud relay configuration revision number, present on devices
	// supporting BLE cloud relay functionality
	BtrelayRev *float64 `json:"btrelay_rev,omitempty"`

	// BthcRev bTHomeControl configuration revision number, present when device
	// supports control with BLU devices
	BthcRev *float64 `json:"bthc_rev,omitempty"`

	AvailableUpdates *SysStatusAvailableUpdates `json:"available_updates,omitempty"`
	// WakeupPeriod period (in seconds) at which device wakes up and sends "keep-alive"
	// packet to cloud, readonly. Count starts from last full wakeup
	WakeupPeriod *float64 `json:"wakeup_period,omitempty"`

	// UTCOffset time offset (in seconds). This is the difference between the device
	// local time and UTC
	UTCOffset *float64 `json:"utc_offset,omitempty"`

	WakeupReason *SysStatusWakeupReason `json:"wakeup_reason,omitempty"`
	// ResetReason numeric reset reason. Not documented by Shelly; appears in firmware
	// responses.
	ResetReason *int `json:"reset_reason,omitempty"`

	// SafeMode true if the device is operating in Safe Mode; present only in that
	// mode. Not documented by Shelly.
	SafeMode *bool `json:"safe_mode,omitempty"`
}

// SysGetStatusRequest requests the status of the Sys component.
type SysGetStatusRequest struct {
}

func (r *SysGetStatusRequest) Method() string { return "Sys.GetStatus" }

func (r *SysGetStatusRequest) NewTypedResponse() *SysStatus { return &SysStatus{} }

func (r *SysGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *SysGetStatusRequest) Do(client *resty.Client) (*SysStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
