// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// TemperatureConfig is generated from the Shelly API documentation.
type TemperatureConfig struct {
	// ID id of the Temperature component instance
	ID int `json:"id"`

	// Name name of the Temperature instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`
}

// TemperatureGetConfigRequest requests the configuration of the Temperature component.
type TemperatureGetConfigRequest struct {
	// ID of the Temperature component instance.
	ID int `json:"id"`
}

func (r *TemperatureGetConfigRequest) Method() string { return "Temperature.GetConfig" }

func (r *TemperatureGetConfigRequest) NewTypedResponse() *TemperatureConfig {
	return &TemperatureConfig{}
}

func (r *TemperatureGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *TemperatureGetConfigRequest) Do(client *resty.Client) (*TemperatureConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// TemperatureSetConfigRequest updates the configuration of the Temperature component.
type TemperatureSetConfigRequest struct {
	// ID of the Temperature component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config TemperatureConfig `json:"config"`
}

func (r *TemperatureSetConfigRequest) Method() string { return "Temperature.SetConfig" }

func (r *TemperatureSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *TemperatureSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *TemperatureSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
