// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// TemperatureConfig is generated from the Shelly API documentation.
type TemperatureConfig struct {
	// ID id of the Temperature component instance
	ID int `json:"id"`

	// Name name of the Temperature instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`

	// ReportThrC temperature report threshold in Celsius. Accepted range is
	// device-specific, default [0.5..5.0]C unless specified otherwise
	ReportThrC *float64 `json:"report_thr_C,omitempty"`

	// OffsetC offset in Celsius to be applied to the measured temperature. Accepted
	// range is device-specific, default [-50.0 .. 50.0] unless specified otherwise
	OffsetC *float64 `json:"offset_C,omitempty"`
}

// TemperatureGetConfigRequest requests the configuration of the Temperature component.
type TemperatureGetConfigRequest struct {
	// ID of the Temperature component instance.
	ID int `json:"id"`
}

func (r *TemperatureGetConfigRequest) Method() string { return "Temperature.GetConfig" }

func (r *TemperatureGetConfigRequest) NewTypedResponse() *TemperatureConfig {
	return &TemperatureConfig{}
}

func (r *TemperatureGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *TemperatureGetConfigRequest) Do(client *resty.Client) (*TemperatureConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// TemperatureSetConfigRequest updates the configuration of the Temperature component.
type TemperatureSetConfigRequest struct {
	// ID of the Temperature component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config TemperatureConfig `json:"config"`
}

func (r *TemperatureSetConfigRequest) Method() string { return "Temperature.SetConfig" }

func (r *TemperatureSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *TemperatureSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *TemperatureSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// TemperatureStatus is generated from the Shelly API documentation.
type TemperatureStatus struct {
	// ID id of the Temperature component instance
	ID int `json:"id"`

	// TC temperature in Celsius (null if valid value could not be obtained)
	TC *float64 `json:"tC,omitempty"`

	// TF temperature in Fahrenheit (null if valid value could not be obtained)
	TF *float64 `json:"tF,omitempty"`

	// Errors shown only if at least one error is present. May contain out_of_range,
	// read when there is problem reading sensor
	Errors []string `json:"errors,omitempty"`
}

// TemperatureGetStatusRequest requests the status of the Temperature component.
type TemperatureGetStatusRequest struct {
	// ID of the Temperature component instance.
	ID int `json:"id"`
}

func (r *TemperatureGetStatusRequest) Method() string { return "Temperature.GetStatus" }

func (r *TemperatureGetStatusRequest) NewTypedResponse() *TemperatureStatus {
	return &TemperatureStatus{}
}

func (r *TemperatureGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *TemperatureGetStatusRequest) Do(client *resty.Client) (*TemperatureStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
