// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// VoltmeterConfigXvoltage is generated from the Shelly API documentation.
type VoltmeterConfigXvoltage struct {
	// Expr jS expression containg x, where x is the raw value to be transformed
	// (status.voltage), for example "x+1". Accepted range: null or [0..100] chars.
	// Both null and "" mean value transformation is disabled.
	Expr *string `json:"expr,omitempty"`

	// Unit unit of the transformed value (status.xvoltage), for example "m/s".
	// Accepted range: null or [0..20] chars. Both null and "" mean value
	// transformation is disabled.
	Unit *string `json:"unit,omitempty"`
}

// VoltmeterConfig is generated from the Shelly API documentation.
type VoltmeterConfig struct {
	// ID id of the Voltmeter component instance
	ID int `json:"id"`

	// Name name of the Voltmeter instance. name length should not exceed 64 chars
	Name *string `json:"name,omitempty"`

	// ReportThr voltmeter report threshold in volts. Accepted range is device-specific
	ReportThr *float64 `json:"report_thr,omitempty"`

	// Range input range, which is device-specific. See the table below.
	Range *float64 `json:"range,omitempty"`

	Xvoltage *VoltmeterConfigXvoltage `json:"xvoltage,omitempty"`
}

// VoltmeterGetConfigRequest requests the configuration of the Voltmeter component.
type VoltmeterGetConfigRequest struct {
	// ID of the Voltmeter component instance.
	ID int `json:"id"`
}

func (r *VoltmeterGetConfigRequest) Method() string { return "Voltmeter.GetConfig" }

func (r *VoltmeterGetConfigRequest) NewTypedResponse() *VoltmeterConfig { return &VoltmeterConfig{} }

func (r *VoltmeterGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *VoltmeterGetConfigRequest) Do(client *resty.Client) (*VoltmeterConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// VoltmeterSetConfigRequest updates the configuration of the Voltmeter component.
type VoltmeterSetConfigRequest struct {
	// ID of the Voltmeter component instance.
	ID int `json:"id"`

	// Config that the method takes.
	Config VoltmeterConfig `json:"config"`
}

func (r *VoltmeterSetConfigRequest) Method() string { return "Voltmeter.SetConfig" }

func (r *VoltmeterSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *VoltmeterSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *VoltmeterSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// VoltmeterStatus is generated from the Shelly API documentation.
type VoltmeterStatus struct {
	// ID id of the Voltmeter component instance
	ID int `json:"id"`

	// Voltage voltage in volts (null if valid value could not be obtained)
	Voltage *float64 `json:"voltage,omitempty"`

	// Xvoltage voltage transformed with config.xvoltage.expr. Present only when both
	// config.xvoltage.expr and config.xvoltage.unit are set to non-empty values. null
	// if config.xvoltage.expr can not be evaluated.
	Xvoltage *float64 `json:"xvoltage,omitempty"`

	// Errors shown only if at least one error is present. May contain out_of_range,
	// read when there is problem reading sensor
	Errors json.RawMessage `json:"errors,omitempty"`
}

// VoltmeterGetStatusRequest requests the status of the Voltmeter component.
type VoltmeterGetStatusRequest struct {
	// ID of the Voltmeter component instance.
	ID int `json:"id"`
}

func (r *VoltmeterGetStatusRequest) Method() string { return "Voltmeter.GetStatus" }

func (r *VoltmeterGetStatusRequest) NewTypedResponse() *VoltmeterStatus { return &VoltmeterStatus{} }

func (r *VoltmeterGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *VoltmeterGetStatusRequest) Do(client *resty.Client) (*VoltmeterStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
