// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"encoding/json"
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// WifiConfigAPRangeExtender is generated from the Shelly API documentation.
type WifiConfigAPRangeExtender struct {
	// Enable true if range extender functionality is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`
}

// WifiConfigAP is generated from the Shelly API documentation.
type WifiConfigAP struct {
	// SSID sSID of the access point (up to 29 symbols). Default is the deviceID, set
	// to null to restore default. optional
	SSID *string `json:"ssid,omitempty"`

	// Pass password for the AP network, writeonly. Default is open network, set to
	// null to restore default. optional
	Pass *string `json:"pass,omitempty"`

	// IsOpen true if the access point is open, false otherwise
	IsOpen *bool `json:"is_open,omitempty"`

	// Enable true if the access point is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	RangeExtender *WifiConfigAPRangeExtender `json:"range_extender,omitempty"`
}

// WifiConfigSta is generated from the Shelly API documentation.
type WifiConfigSta struct {
	// SSID sSID of the network.
	SSID *string `json:"ssid,omitempty"`

	// Pass password for the SSID, writeonly. Must be provided if you provide ssid
	Pass *string `json:"pass,omitempty"`

	// IsOpen true if the network is open, i.e. no password is set, false otherwise,
	// readonly
	IsOpen *bool `json:"is_open,omitempty"`

	// Enable true if the configuration is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Ipv4mode iPv4 mode. Range of values: dhcp, static
	Ipv4mode *string `json:"ipv4mode,omitempty"`

	// IP ip to use when ipv4mode is static
	IP *string `json:"ip,omitempty"`

	// Netmask netmask to use when ipv4mode is static
	Netmask *string `json:"netmask,omitempty"`

	// Gw gateway to use when ipv4mode is static
	Gw *string `json:"gw,omitempty"`

	// Nameserver nameserver to use when ipv4mode is static
	Nameserver *string `json:"nameserver,omitempty"`
}

// WifiConfigRoam is generated from the Shelly API documentation.
type WifiConfigRoam struct {
	// RssiThr rssi threshold - when reached will trigger the access point roaming.
	// Default value: -80
	RssiThr *float64 `json:"rssi_thr,omitempty"`

	// Interval interval at which to scan for better access points. Enabled if set to
	// positive number, disabled if set to 0. Default value: 60
	Interval *float64 `json:"interval,omitempty"`
}

// WifiConfig is generated from the Shelly API documentation.
type WifiConfig struct {
	AP  *WifiConfigAP  `json:"ap,omitempty"`
	Sta *WifiConfigSta `json:"sta,omitempty"`
	// Sta1 identical to sta. It will be used as fallback when the device is unable to
	// connect to the sta network.
	Sta1 json.RawMessage `json:"sta1,omitempty"`

	Roam *WifiConfigRoam `json:"roam,omitempty"`
}

// WifiGetConfigRequest requests the configuration of the WiFi component.
type WifiGetConfigRequest struct {
}

func (r *WifiGetConfigRequest) Method() string { return "Wifi.GetConfig" }

func (r *WifiGetConfigRequest) NewTypedResponse() *WifiConfig { return &WifiConfig{} }

func (r *WifiGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WifiGetConfigRequest) Do(client *resty.Client) (*WifiConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// WifiSetConfigRequest updates the configuration of the WiFi component.
type WifiSetConfigRequest struct {
	// Config that the method takes.
	Config WifiConfig `json:"config"`
}

func (r *WifiSetConfigRequest) Method() string { return "Wifi.SetConfig" }

func (r *WifiSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *WifiSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WifiSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// WifiStatus is generated from the Shelly API documentation.
type WifiStatus struct {
	// StaIP ip of the device in the network (null if disconnected)
	StaIP *string `json:"sta_ip,omitempty"`

	// Status status of the connection. Range of values: disconnected, connecting,
	// connected, got ip
	Status *string `json:"status,omitempty"`

	// SSID sSID of the network (null if disconnected)
	SSID *string `json:"ssid,omitempty"`

	// BSSID bSSID of the currently connected AP, only when connected
	BSSID *string `json:"bssid,omitempty"`

	// Channel channel of the network (only present when connected)
	Channel *float64 `json:"channel,omitempty"`

	// Rssi strength of the signal in dBms
	Rssi *float64 `json:"rssi,omitempty"`

	// APClientCount number of clients connected to the access point. Present only when
	// AP is enabled and range extender functionality is present and enabled.
	APClientCount *float64 `json:"ap_client_count,omitempty"`
}

// WifiGetStatusRequest requests the status of the WiFi component.
type WifiGetStatusRequest struct {
}

func (r *WifiGetStatusRequest) Method() string { return "Wifi.GetStatus" }

func (r *WifiGetStatusRequest) NewTypedResponse() *WifiStatus { return &WifiStatus{} }

func (r *WifiGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WifiGetStatusRequest) Do(client *resty.Client) (*WifiStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
