// Code generated by cmd/gen from the Shelly API docs. DO NOT EDIT.

package components

import (
	"github.com/DonRobo/shelly-go/rpc"
	"resty.dev/v3"
)

// WsConfig is generated from the Shelly API documentation.
type WsConfig struct {
	// Enable true if websocket outbound connection is enabled, false otherwise
	Enable *bool `json:"enable,omitempty"`

	// Server name of the server to which the device is connected. When prefixed with
	// wss:// a TLS socket will be used
	Server *string `json:"server,omitempty"`
}

// WsGetConfigRequest requests the configuration of the Ws component.
type WsGetConfigRequest struct {
}

func (r *WsGetConfigRequest) Method() string { return "Ws.GetConfig" }

func (r *WsGetConfigRequest) NewTypedResponse() *WsConfig { return &WsConfig{} }

func (r *WsGetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WsGetConfigRequest) Do(client *resty.Client) (*WsConfig, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// WsSetConfigRequest updates the configuration of the Ws component.
type WsSetConfigRequest struct {
	// Config that the method takes.
	Config WsConfig `json:"config"`
}

func (r *WsSetConfigRequest) Method() string { return "Ws.SetConfig" }

func (r *WsSetConfigRequest) NewTypedResponse() *rpc.SetConfigResponse {
	return &rpc.SetConfigResponse{}
}

func (r *WsSetConfigRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WsSetConfigRequest) Do(client *resty.Client) (*rpc.SetConfigResponse, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}

// WsStatus is generated from the Shelly API documentation.
type WsStatus struct {
	// Connected true if device is connected to a websocket outbound connection or
	// false otherwise.
	Connected *bool `json:"connected,omitempty"`
}

// WsGetStatusRequest requests the status of the Ws component.
type WsGetStatusRequest struct {
}

func (r *WsGetStatusRequest) Method() string { return "Ws.GetStatus" }

func (r *WsGetStatusRequest) NewTypedResponse() *WsStatus { return &WsStatus{} }

func (r *WsGetStatusRequest) NewResponse() any { return r.NewTypedResponse() }

func (r *WsGetStatusRequest) Do(client *resty.Client) (*WsStatus, *rpc.Frame, error) {
	resp := r.NewTypedResponse()
	raw, err := rpc.Do(client, r, resp)
	return resp, raw, err
}
